"""
Seed quantitative questions extracted from Gagan Pratap PDFs.
Run: python seed_quant_questions.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))

from app.database.connection import SessionLocal
from app.models.question_model import Question

# ─── QUESTIONS DATA ────────────────────────────────────────────────────────────
# subject_code="quant", phase="main"
# difficulty: "easy" | "medium" | "hard"

QUESTIONS = [

# ══════════════════════════════════════════════════════
# TOPIC: Coordinate Geometry
# ══════════════════════════════════════════════════════
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"If the ordinate of point (2k-3, 5k+1) is twice of its abscissa, then find the value of the abscissa?",
  "question_text_hi":"यदि किसी निर्देशांक बिंदु (2k-3, 5k+1) की कोटि उसके भुज की दोगुना है। तो भुज का मान ज्ञात करें?",
  "option_a":"-34","option_a_hi":"-34",
  "option_b":"-17","option_b_hi":"-17",
  "option_c":"-19/3","option_c_hi":"-19/3",
  "option_d":"-17/8","option_d_hi":"-17/8",
  "correct_answer":"b",
  "explanation":"5k+1 = 2(2k-3) → k = -7; abscissa = 2(-7)-3 = -17",
  "explanation_hi":"5k+1 = 2(2k-3) → k = -7; भुज = 2(-7)-3 = -17",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"Which of the following points lies on the x-axis?",
  "question_text_hi":"निम्नलिखित में से कौन सा बिंदु x-अक्ष पर स्थित है?",
  "option_a":"(2, 3)","option_a_hi":"(2, 3)",
  "option_b":"(2, 0)","option_b_hi":"(2, 0)",
  "option_c":"(1, 2)","option_c_hi":"(1, 2)",
  "option_d":"(0, 4)","option_d_hi":"(0, 4)",
  "correct_answer":"b",
  "explanation":"A point on x-axis has y-coordinate = 0. So (2, 0) lies on x-axis.",
  "explanation_hi":"x-अक्ष पर स्थित बिंदु का y-निर्देशांक 0 होता है। अतः (2, 0) x-अक्ष पर है।",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"The graph of the equation x = a (a ≠ 0) is a _____.",
  "question_text_hi":"समीकरण x = a (a ≠ 0) का ग्राफ ____ है।",
  "option_a":"line parallel to x-axis","option_a_hi":"x-अक्ष के समांतर रेखा",
  "option_b":"line parallel to y-axis","option_b_hi":"y-अक्ष के समांतर रेखा",
  "option_c":"line at 45° to y-axis","option_c_hi":"y-अक्ष से 45° पर रेखा",
  "option_d":"line at 45° to x-axis","option_d_hi":"x-अक्ष से 45° पर रेखा",
  "correct_answer":"b",
  "explanation":"x = a (constant) is a vertical line, i.e., parallel to y-axis.",
  "explanation_hi":"x = a (नियतांक) एक ऊर्ध्वाधर रेखा है जो y-अक्ष के समांतर होती है।",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"Which of the following equations represent a line parallel to y-axis?",
  "question_text_hi":"निम्नलिखित में से कौन सा समीकरण y-अक्ष के समांतर एक रेखा का प्रतिनिधित्व करता है?",
  "option_a":"y = 3","option_a_hi":"y = 3",
  "option_b":"x + 3 = 4 - 2x","option_b_hi":"x + 3 = 4 - 2x",
  "option_c":"2x + y = 0","option_c_hi":"2x + y = 0",
  "option_d":"y - 2 = 1","option_d_hi":"y - 2 = 1",
  "correct_answer":"b",
  "explanation":"x + 3 = 4 - 2x → 3x = 1 → x = 1/3, a vertical line parallel to y-axis.",
  "explanation_hi":"x + 3 = 4 - 2x → x = 1/3, यह y-अक्ष के समांतर ऊर्ध्वाधर रेखा है।",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"Give the coordinates of the middle point of the segment joining the points (-4, 7) and (2, 3).",
  "question_text_hi":"बिंदुओं (-4, 7) और (2, 3) को मिलाने वाले रेखाखंड के मध्य बिंदु के निर्देशांक ज्ञात कीजिए।",
  "option_a":"(1, -5)","option_a_hi":"(1, -5)",
  "option_b":"(-1, 5)","option_b_hi":"(-1, 5)",
  "option_c":"(2, 4)","option_c_hi":"(2, 4)",
  "option_d":"(-2, 3)","option_d_hi":"(-2, 3)",
  "correct_answer":"b",
  "explanation":"Midpoint = ((-4+2)/2, (7+3)/2) = (-1, 5)",
  "explanation_hi":"मध्य बिंदु = ((-4+2)/2, (7+3)/2) = (-1, 5)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"Point P(8, 5) is the midpoint of segment AB. Coordinates of A are (5, y) and B are (x, -3). What is the value of x?",
  "question_text_hi":"बिंदु P(8, 5) रेखाखंड AB का मध्यबिंदु है। A के निर्देशांक (5, y) और B के (x, -3) हैं। x का मान क्या है?",
  "option_a":"-11","option_a_hi":"-11",
  "option_b":"11","option_b_hi":"11",
  "option_c":"7","option_c_hi":"7",
  "option_d":"-7","option_d_hi":"-7",
  "correct_answer":"b",
  "explanation":"(5+x)/2 = 8 → x = 11",
  "explanation_hi":"(5+x)/2 = 8 → x = 11",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"Point P is the midpoint of segment AB. Coordinates of P are (1, 3) and A are (-3, 8). What are the coordinates of point B?",
  "question_text_hi":"बिंदु P रेखाखंड AB का मध्यबिंदु है। P के निर्देशांक (1, 3) हैं और A के (-3, 8) हैं। बिंदु B के निर्देशांक क्या हैं?",
  "option_a":"(-5, -2)","option_a_hi":"(-5, -2)",
  "option_b":"(-5, 2)","option_b_hi":"(-5, 2)",
  "option_c":"(5, 2)","option_c_hi":"(5, 2)",
  "option_d":"(5, -2)","option_d_hi":"(5, -2)",
  "correct_answer":"d",
  "explanation":"(-3+x)/2=1 → x=5; (8+y)/2=3 → y=-2. B = (5, -2)",
  "explanation_hi":"x = 5, y = -2 → B = (5, -2)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"What is the distance between the points (3, 6) and (-2, -6)?",
  "question_text_hi":"बिंदु (3, 6) और (-2, -6) के बीच की दूरी कितनी है?",
  "option_a":"15","option_a_hi":"15",
  "option_b":"13","option_b_hi":"13",
  "option_c":"11","option_c_hi":"11",
  "option_d":"12","option_d_hi":"12",
  "correct_answer":"b",
  "explanation":"d = √((3-(-2))² + (6-(-6))²) = √(25+144) = √169 = 13",
  "explanation_hi":"d = √(5² + 12²) = √(25+144) = 13",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"The distance between two points (a cosα, 0) and (0, a sinα) is:",
  "question_text_hi":"दो बिंदुओं (a cosα, 0) और (0, a sinα) के बीच की दूरी कितनी है?",
  "option_a":"a","option_a_hi":"a",
  "option_b":"|a|","option_b_hi":"|a|",
  "option_c":"|2a|","option_c_hi":"|2a|",
  "option_d":"2a","option_d_hi":"2a",
  "correct_answer":"b",
  "explanation":"d = √(a²cos²α + a²sin²α) = √(a²) = |a|",
  "explanation_hi":"d = √(a²cos²α + a²sin²α) = |a|",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"If (2, -2) and (5, 2) are two consecutive vertices of a square, then the length of each side of the square will be:",
  "question_text_hi":"यदि (2, -2) और (5, 2) एक वर्ग के लगातार दो शीर्ष हैं, तो वर्ग की प्रत्येक भुजा की लंबाई होगी:",
  "option_a":"5 units","option_a_hi":"5 इकाई",
  "option_b":"5√2 units","option_b_hi":"5√2 इकाई",
  "option_c":"55/√2 units","option_c_hi":"55/√2 इकाई",
  "option_d":"√5 units","option_d_hi":"√5 इकाई",
  "correct_answer":"a",
  "explanation":"Side = √((5-2)²+(2-(-2))²) = √(9+16) = √25 = 5",
  "explanation_hi":"भुजा = √(9+16) = 5 इकाई",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"If the distance between two points (4, 8) and (k, -4) is 13 units, find the value of k.",
  "question_text_hi":"यदि दो बिंदुओं (4, 8) और (k, -4) के बीच की दूरी 13 इकाई है, तो k का मान ज्ञात कीजिए।",
  "option_a":"-1","option_a_hi":"-1",
  "option_b":"9","option_b_hi":"9",
  "option_c":"Both -1 and 9","option_c_hi":"-1 और 9 दोनों",
  "option_d":"3","option_d_hi":"3",
  "correct_answer":"c",
  "explanation":"(k-4)²+144=169 → (k-4)²=25 → k-4=±5 → k=9 or k=-1",
  "explanation_hi":"(k-4)²=25 → k=9 या k=-1",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"If the distance between two points (x, 7) and (1, 15) is 10 units, then the possible values of x =?",
  "question_text_hi":"यदि दो बिंदुओं (x, 7) और (1, 15) के बीच की दूरी 10 इकाई है, तो x का संभावित मान = ?",
  "option_a":"7, -5","option_a_hi":"7, -5",
  "option_b":"4, 5","option_b_hi":"4, 5",
  "option_c":"5, -7","option_c_hi":"5, -7",
  "option_d":"3, 7","option_d_hi":"3, 7",
  "correct_answer":"a",
  "explanation":"(x-1)²+64=100 → (x-1)²=36 → x=7 or x=-5",
  "explanation_hi":"(x-1)²=36 → x=7 या x=-5",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"Which point on the X-axis is equidistant from (2, -5) and (-2, 9)?",
  "question_text_hi":"X-अक्ष पर वह कौन सा बिंदु है जो (2, -5) और (-2, 9) से समदूरस्थ है?",
  "option_a":"(-7, 0)","option_a_hi":"(-7, 0)",
  "option_b":"(-14, 0)","option_b_hi":"(-14, 0)",
  "option_c":"(14, 0)","option_c_hi":"(14, 0)",
  "option_d":"(7, 0)","option_d_hi":"(7, 0)",
  "correct_answer":"a",
  "explanation":"Let point be (x,0). (x-2)²+25=(x+2)²+81 → x²-4x+29=x²+4x+85 → -8x=56 → x=-7. Point: (-7, 0)",
  "explanation_hi":"(x-2)²+25=(x+2)²+81 → x=-7; बिंदु (-7, 0)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"The coordinates of the point that divides the line segment joining (-5, 5) and (7, -3) internally in the ratio 3:1 are:",
  "question_text_hi":"बिंदुओं (-5, 5) और (7, -3) वाले रेखाखंड को 3:1 के अनुपात में आंतरिक रूप से विभाजित करने वाले बिंदु के निर्देशांक हैं:",
  "option_a":"(-2, 3)","option_a_hi":"(-2, 3)",
  "option_b":"(5/2, 0)","option_b_hi":"(5/2, 0)",
  "option_c":"(1, 1)","option_c_hi":"(1, 1)",
  "option_d":"(4, -1)","option_d_hi":"(4, -1)",
  "correct_answer":"d",
  "explanation":"x=(3×7+1×(-5))/(3+1)=16/4=4; y=(3×(-3)+1×5)/4=-4/4=-1",
  "explanation_hi":"x=(21-5)/4=4, y=(-9+5)/4=-1 → (4, -1)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"Find the coordinates of the point which will divide the line joining (2, 4) and (7, 9) internally in the ratio 1:2.",
  "question_text_hi":"उस बिंदु के निर्देशांक ज्ञात कीजिए जो बिंदु (2, 4) और (7, 9) को मिलाने वाली रेखा को 1:2 के अनुपात में विभाजित करेगा।",
  "option_a":"(5/3, 1/3)","option_a_hi":"(5/3, 1/3)",
  "option_b":"(11/3, 17/3)","option_b_hi":"(11/3, 17/3)",
  "option_c":"(3/8, 3/11)","option_c_hi":"(3/8, 3/11)",
  "option_d":"(8/34, 11/3)","option_d_hi":"(8/34, 11/3)",
  "correct_answer":"b",
  "explanation":"x=(1×7+2×2)/(1+2)=11/3; y=(1×9+2×4)/3=17/3",
  "explanation_hi":"x=11/3, y=17/3",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"The ratio in which point (4, 5) divides the line joining two points (2, 3) and (7, 8) is:",
  "question_text_hi":"वह अनुपात जिसमें बिंदु (4, 5) दो बिंदुओं (2, 3) और (7, 8) को मिलाने वाली रेखा को विभाजित करता है:",
  "option_a":"2:3","option_a_hi":"2:3",
  "option_b":"1:2","option_b_hi":"1:2",
  "option_c":"4:5","option_c_hi":"4:5",
  "option_d":"3:4","option_d_hi":"3:4",
  "correct_answer":"a",
  "explanation":"4=(m×7+n×2)/(m+n) → 4m+4n=7m+2n → 2n=3m → m:n=2:3",
  "explanation_hi":"4m+4n=7m+2n → m:n=2:3",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"In what ratio does the X-axis divide the line segment joining points (9, 14) and (4, -6)?",
  "question_text_hi":"X अक्ष उस रेखा को किस अनुपात में विभाजित करेगा जो बिंदु (9, 14) और बिंदु (4, -6) को मिलाने से प्राप्त होती है?",
  "option_a":"9:4","option_a_hi":"9:4",
  "option_b":"7:3","option_b_hi":"7:3",
  "option_c":"2:7","option_c_hi":"2:7",
  "option_d":"3:2","option_d_hi":"3:2",
  "correct_answer":"b",
  "explanation":"For y=0: 0=(m×(-6)+n×14)/(m+n) → 6m=14n → m/n=7/3",
  "explanation_hi":"y=0 रखने पर: m/n=14/6=7/3",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"At what point does the line 2x + 5y = -6 cut the X-axis?",
  "question_text_hi":"रेखा 2x + 5y = -6, X-अक्ष को किस बिंदु पर प्रतिच्छेद करेगी?",
  "option_a":"(3, 0)","option_a_hi":"(3, 0)",
  "option_b":"(-3, 0)","option_b_hi":"(-3, 0)",
  "option_c":"(0, 3)","option_c_hi":"(0, 3)",
  "option_d":"(0, -3)","option_d_hi":"(0, -3)",
  "correct_answer":"b",
  "explanation":"Put y=0: 2x=-6 → x=-3. Point: (-3, 0)",
  "explanation_hi":"y=0 रखने पर: x=-3 → बिंदु (-3, 0)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"The straight line kx - 3y = 6 passes through the point (3, 2). What is the value of k?",
  "question_text_hi":"एक सरल रेखा kx - 3y = 6, बिंदु (3, 2) से होकर गुजरती है। k का मान ज्ञात कीजिए।",
  "option_a":"3","option_a_hi":"3",
  "option_b":"4","option_b_hi":"4",
  "option_c":"6","option_c_hi":"6",
  "option_d":"2","option_d_hi":"2",
  "correct_answer":"b",
  "explanation":"k(3) - 3(2) = 6 → 3k = 12 → k = 4",
  "explanation_hi":"3k - 6 = 6 → k = 4",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"Find the slope of the line joining the points (3, -4) and (5, 2).",
  "question_text_hi":"बिंदुओं (3, -4) और (5, 2) को मिलाने वाली रेखा का ढलान (slope) ज्ञात कीजिए।",
  "option_a":"1/3","option_a_hi":"1/3",
  "option_b":"2","option_b_hi":"2",
  "option_c":"3","option_c_hi":"3",
  "option_d":"1/2","option_d_hi":"1/2",
  "correct_answer":"c",
  "explanation":"Slope = (2-(-4))/(5-3) = 6/2 = 3",
  "explanation_hi":"ढलान = (2+4)/(5-3) = 6/2 = 3",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"Find the slope of the line represented by the equation 4x + 6y = 9.",
  "question_text_hi":"समीकरण 4x + 6y = 9 द्वारा प्रदर्शित रेखा का ढाल (स्लोप) ज्ञात कीजिए।",
  "option_a":"3/2","option_a_hi":"3/2",
  "option_b":"-2/3","option_b_hi":"-2/3",
  "option_c":"-3/2","option_c_hi":"-3/2",
  "option_d":"2/3","option_d_hi":"2/3",
  "correct_answer":"b",
  "explanation":"6y = -4x + 9 → y = (-2/3)x + 3/2; slope = -2/3",
  "explanation_hi":"y = (-2/3)x + 3/2 → ढलान = -2/3",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"What is the slope of line 2x - 5y = 12?",
  "question_text_hi":"रेखा 2x - 5y = 12 की प्रवणता ज्ञात करें?",
  "option_a":"2/5","option_a_hi":"2/5",
  "option_b":"5/2","option_b_hi":"5/2",
  "option_c":"-5/2","option_c_hi":"-5/2",
  "option_d":"-2/5","option_d_hi":"-2/5",
  "correct_answer":"a",
  "explanation":"-5y = -2x + 12 → y = (2/5)x - 12/5; slope = 2/5",
  "explanation_hi":"ढलान = 2/5",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"The measure of the angle between the graph of linear equation 35x - 35y + 15 = 0 and the x-axis is:",
  "question_text_hi":"रैखिक समीकरण 35x - 35y + 15 = 0 और x-अक्ष के ग्राफ के बीच के कोण का माप है:",
  "option_a":"55°","option_a_hi":"55°",
  "option_b":"35°","option_b_hi":"35°",
  "option_c":"50°","option_c_hi":"50°",
  "option_d":"45°","option_d_hi":"45°",
  "correct_answer":"d",
  "explanation":"35y = 35x + 15 → y = x + 15/35; slope = 1 → angle = tan⁻¹(1) = 45°",
  "explanation_hi":"ढलान = 1 → कोण = 45°",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"What is the slope of the line parallel to the line passing through the points (3, -4) and (-2, 5)?",
  "question_text_hi":"बिंदुओं (3, -4) और (-2, 5) से गुजरने वाली रेखा के समानांतर रेखा की ढाल क्या है?",
  "option_a":"9/5","option_a_hi":"9/5",
  "option_b":"-5/9","option_b_hi":"-5/9",
  "option_c":"-9/5","option_c_hi":"-9/5",
  "option_d":"5/9","option_d_hi":"5/9",
  "correct_answer":"c",
  "explanation":"Slope = (5-(-4))/(-2-3) = 9/(-5) = -9/5; parallel line has same slope",
  "explanation_hi":"ढलान = (5+4)/(-2-3) = -9/5",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"What is the slope of the line perpendicular to the line passing through the points (3, -2) and (4, 2)?",
  "question_text_hi":"(3, -2) और (4, 2) बिंदुओं से गुजरने वाली रेखा के अभिलंब रेखा की ढाल क्या है?",
  "option_a":"1/4","option_a_hi":"1/4",
  "option_b":"4","option_b_hi":"4",
  "option_c":"-4","option_c_hi":"-4",
  "option_d":"-1/4","option_d_hi":"-1/4",
  "correct_answer":"d",
  "explanation":"Slope of line = (2-(-2))/(4-3) = 4; perpendicular slope = -1/4",
  "explanation_hi":"रेखा की ढाल = 4; लम्बवत ढाल = -1/4",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"The equation of a straight line passing through (-2, 5) and (1, 3) is:",
  "question_text_hi":"(-2, 5) और (1, 3) से गुजरने वाली एक सीधी रेखा का समीकरण है:",
  "option_a":"3x - 2y - 11 = 0","option_a_hi":"3x - 2y - 11 = 0",
  "option_b":"2x - 3y - 19 = 0","option_b_hi":"2x - 3y - 19 = 0",
  "option_c":"3x + 2y + 19 = 0","option_c_hi":"3x + 2y + 19 = 0",
  "option_d":"2x + 3y - 11 = 0","option_d_hi":"2x + 3y - 11 = 0",
  "correct_answer":"d",
  "explanation":"Slope=(-2/3); y-3=(-2/3)(x-1) → 3y-9=-2x+2 → 2x+3y=11",
  "explanation_hi":"ढलान=-2/3; 2x+3y=11",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"Find the equation of a line having slope -6 and an intercept of 10 units on Y-axis.",
  "question_text_hi":"उस रेखा का समीकरण ज्ञात करें जिसकी प्रवणता -6 है और जो Y-अक्ष पर 10 यूनिट का अंतःखंड काटती है।",
  "option_a":"6x - y - 10 = 0","option_a_hi":"6x - y - 10 = 0",
  "option_b":"6x + y - 10 = 0","option_b_hi":"6x + y - 10 = 0",
  "option_c":"6x + y + 10 = 0","option_c_hi":"6x + y + 10 = 0",
  "option_d":"6x - y + 10 = 0","option_d_hi":"6x - y + 10 = 0",
  "correct_answer":"b",
  "explanation":"y = -6x + 10 → 6x + y - 10 = 0",
  "explanation_hi":"y = -6x + 10 → 6x + y - 10 = 0",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"What is the equation of a line which has 3 as x-intercept and -5 as y-intercept?",
  "question_text_hi":"एक रेखा के समीकरण का पता लगाएं जिसका x-प्रतिच्छेद 3 और y-प्रतिच्छेद -5 है।",
  "option_a":"3x - 5y = 15","option_a_hi":"3x - 5y = 15",
  "option_b":"5x - 3y = 15","option_b_hi":"5x - 3y = 15",
  "option_c":"5x + 3y = 15","option_c_hi":"5x + 3y = 15",
  "option_d":"3x + 5y = 15","option_d_hi":"3x + 5y = 15",
  "correct_answer":"b",
  "explanation":"x/3 + y/(-5) = 1 → 5x - 3y = 15",
  "explanation_hi":"x/3 + y/(-5) = 1 → 5x - 3y = 15",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"Find the area of the triangle whose vertices are A(2, 4), B(3, -1) and C(-3, 3).",
  "question_text_hi":"त्रिभुज का क्षेत्रफल ज्ञात कीजिए जिसके निर्देशांक A(2, 4), B(3, -1) और C(-3, 3) हैं।",
  "option_a":"13 sq units","option_a_hi":"13 वर्ग इकाई",
  "option_b":"12 sq units","option_b_hi":"12 वर्ग इकाई",
  "option_c":"10 sq units","option_c_hi":"10 वर्ग इकाई",
  "option_d":"14 sq units","option_d_hi":"14 वर्ग इकाई",
  "correct_answer":"a",
  "explanation":"Area = ½|x₁(y₂-y₃)+x₂(y₃-y₁)+x₃(y₁-y₂)| = ½|2(-4)+3(-1)+(-3)(5)| = ½|−8−3−15| = 13",
  "explanation_hi":"क्षेत्रफल = ½|2(-4)+3(-1)+(-3)(5)| = 13 वर्ग इकाई",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"The area, in square units, of a triangle formed by the coordinate axis and the straight line 5x + 7y = 35 is:",
  "question_text_hi":"निर्देशांक अक्ष और सीधी रेखा 5x + 7y = 35 द्वारा बनाया गया त्रिभुज का क्षेत्रफल वर्ग इकाई में है:",
  "option_a":"2/35","option_a_hi":"2/35",
  "option_b":"35/2","option_b_hi":"35/2",
  "option_c":"25/2","option_c_hi":"25/2",
  "option_d":"35","option_d_hi":"35",
  "correct_answer":"b",
  "explanation":"x-intercept=7, y-intercept=5. Area = ½×7×5 = 35/2",
  "explanation_hi":"x-अंतःखंड=7, y-अंतःखंड=5. क्षेत्रफल=½×7×5=35/2",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"Find the centroid of triangle ABC with coordinates A(5, -3), B(4, 6) and C(8, 2).",
  "question_text_hi":"त्रिभुज ABC के बिंदुओं A(5, -3), B(4, 6) और C(8, 2) का केंद्रक ज्ञात करें।",
  "option_a":"17/3, 11/3","option_a_hi":"17/3, 11/3",
  "option_b":"11/3, 17/3","option_b_hi":"11/3, 17/3",
  "option_c":"17/3, 5/3","option_c_hi":"17/3, 5/3",
  "option_d":"17/3, -8/3","option_d_hi":"17/3, -8/3",
  "correct_answer":"c",
  "explanation":"G = ((5+4+8)/3, (-3+6+2)/3) = (17/3, 5/3)",
  "explanation_hi":"G = (17/3, 5/3)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"What is the reflection of the point (3, -2) in the origin?",
  "question_text_hi":"मूल बिंदु पर बिंदु (3, -2) का प्रतिबिंब क्या है?",
  "option_a":"(3, -2)","option_a_hi":"(3, -2)",
  "option_b":"(-2, -3)","option_b_hi":"(-2, -3)",
  "option_c":"(-3, 2)","option_c_hi":"(-3, 2)",
  "option_d":"(3, 2)","option_d_hi":"(3, 2)",
  "correct_answer":"c",
  "explanation":"Reflection in origin: (x, y) → (-x, -y). So (3, -2) → (-3, 2)",
  "explanation_hi":"मूल बिंदु में प्रतिबिंब: (x, y) → (-x, -y) → (-3, 2)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"What is the reflection of the point (-0.5, 6) in the line X-axis?",
  "question_text_hi":"X-अक्ष में बिंदु (-0.5, 6) का प्रतिबिंब क्या है?",
  "option_a":"(0.5, -6)","option_a_hi":"(0.5, -6)",
  "option_b":"(-6, -0.5)","option_b_hi":"(-6, -0.5)",
  "option_c":"(6, -0.5)","option_c_hi":"(6, -0.5)",
  "option_d":"(-0.5, -6)","option_d_hi":"(-0.5, -6)",
  "correct_answer":"d",
  "explanation":"Reflection in X-axis: (x, y) → (x, -y). So (-0.5, 6) → (-0.5, -6)",
  "explanation_hi":"X-अक्ष में प्रतिबिंब: y का चिह्न बदलता है → (-0.5, -6)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"What is the reflection of the point (2, -3.5) in the line Y-axis?",
  "question_text_hi":"Y-अक्ष में बिंदु (2, -3.5) का प्रतिबिंब क्या है?",
  "option_a":"(-2, 3.5)","option_a_hi":"(-2, 3.5)",
  "option_b":"(-2, -3.5)","option_b_hi":"(-2, -3.5)",
  "option_c":"(-3.5, -2)","option_c_hi":"(-3.5, -2)",
  "option_d":"(3.5, -2)","option_d_hi":"(3.5, -2)",
  "correct_answer":"b",
  "explanation":"Reflection in Y-axis: (x, y) → (-x, y). So (2, -3.5) → (-2, -3.5)",
  "explanation_hi":"Y-अक्ष में प्रतिबिंब: x का चिह्न बदलता है → (-2, -3.5)",
},

# ══════════════════════════════════════════════════════
# TOPIC: Average
# ══════════════════════════════════════════════════════
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"easy","phase":"main",
  "question_text":"The sum of 8 numbers is 912. Find their average.",
  "question_text_hi":"8 संख्याओं का योगफल 912 है। उनका औसत ज्ञात कीजिए।",
  "option_a":"112","option_a_hi":"112",
  "option_b":"115","option_b_hi":"115",
  "option_c":"114","option_c_hi":"114",
  "option_d":"113","option_d_hi":"113",
  "correct_answer":"c",
  "explanation":"Average = 912 ÷ 8 = 114",
  "explanation_hi":"औसत = 912 ÷ 8 = 114",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"easy","phase":"main",
  "question_text":"The average of 48, 39 and y is 40. Find the value of y.",
  "question_text_hi":"48, 39 और y का औसत 40 है। y का मान ज्ञात कीजिए।",
  "option_a":"33","option_a_hi":"33",
  "option_b":"32","option_b_hi":"32",
  "option_c":"35","option_c_hi":"35",
  "option_d":"31","option_d_hi":"31",
  "correct_answer":"a",
  "explanation":"(48 + 39 + y)/3 = 40 → 87 + y = 120 → y = 33",
  "explanation_hi":"(48 + 39 + y)/3 = 40 → y = 33",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"A shopkeeper has a sale of ₹5,445, ₹5,937, ₹5,865 and ₹6,562 for 4 consecutive days. If he gets an average sale of ₹6,050 for 5 days, find his sale on the fifth day.",
  "question_text_hi":"एक दुकानदार की 4 क्रमागत दिनों की बिक्री ₹5,445, ₹5,937, ₹5,865 और ₹6,562 है। यदि 5 दिनों की औसत बिक्री ₹6,050 हो, तो पांचवें दिन की बिक्री ज्ञात कीजिए।",
  "option_a":"₹6,131","option_a_hi":"₹6,131",
  "option_b":"₹6,441","option_b_hi":"₹6,441",
  "option_c":"₹6,231","option_c_hi":"₹6,231",
  "option_d":"₹6,341","option_d_hi":"₹6,341",
  "correct_answer":"b",
  "explanation":"5th day = 5×6050 - (5445+5937+5865+6562) = 30250 - 23809 = 6441",
  "explanation_hi":"5वें दिन = 30250 - 23809 = 6441",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"Find the average of all prime numbers up to 40. (Correct to 2 decimal places)",
  "question_text_hi":"40 तक की सभी अभाज्य संख्याओं का औसत ज्ञात कीजिए। (दशमलव के दो स्थान तक)",
  "option_a":"18.42","option_a_hi":"18.42",
  "option_b":"17.42","option_b_hi":"17.42",
  "option_c":"16.42","option_c_hi":"16.42",
  "option_d":"19.42","option_d_hi":"19.42",
  "correct_answer":"c",
  "explanation":"Primes ≤ 40: 2,3,5,7,11,13,17,19,23,29,31,37. Sum=197. Average=197/12≈16.42",
  "explanation_hi":"40 तक की अभाज्य संख्याओं का योग=197, औसत=197/12≈16.42",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"easy","phase":"main",
  "question_text":"Find the average of first 125 natural numbers.",
  "question_text_hi":"प्रथम 125 प्राकृत संख्याओं का औसत ज्ञात कीजिए।",
  "option_a":"62.5","option_a_hi":"62.5",
  "option_b":"63","option_b_hi":"63",
  "option_c":"62","option_c_hi":"62",
  "option_d":"63.5","option_d_hi":"63.5",
  "correct_answer":"b",
  "explanation":"Average of first n natural numbers = (n+1)/2 = 126/2 = 63",
  "explanation_hi":"प्रथम n प्राकृत संख्याओं का औसत = (n+1)/2 = 63",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"easy","phase":"main",
  "question_text":"Find the average of the arithmetic series whose first term is 45 and the last term is 57.",
  "question_text_hi":"अंकगणितीय समांतर श्रेणी का औसत ज्ञात करें जिसका पहला पद 45 है और अंतिम पद 57 है।",
  "option_a":"49","option_a_hi":"49",
  "option_b":"53","option_b_hi":"53",
  "option_c":"55","option_c_hi":"55",
  "option_d":"51","option_d_hi":"51",
  "correct_answer":"d",
  "explanation":"Average of AP = (first term + last term)/2 = (45+57)/2 = 51",
  "explanation_hi":"AP का औसत = (45+57)/2 = 51",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"Find the average of cubes of first five natural numbers.",
  "question_text_hi":"प्रथम पांच प्राकृतिक संख्याओ के घनों का औसत ज्ञात कीजिए।",
  "option_a":"35","option_a_hi":"35",
  "option_b":"40","option_b_hi":"40",
  "option_c":"45","option_c_hi":"45",
  "option_d":"50","option_d_hi":"50",
  "correct_answer":"c",
  "explanation":"(1³+2³+3³+4³+5³)/5 = (1+8+27+64+125)/5 = 225/5 = 45",
  "explanation_hi":"(1+8+27+64+125)/5 = 225/5 = 45",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"easy","phase":"main",
  "question_text":"The average of odd numbers up to 100 is:",
  "question_text_hi":"100 तक की सभी विषम संख्याओं का औसत होगा:",
  "option_a":"50.5","option_a_hi":"50.5",
  "option_b":"50","option_b_hi":"50",
  "option_c":"49.5","option_c_hi":"49.5",
  "option_d":"49","option_d_hi":"49",
  "correct_answer":"b",
  "explanation":"Odd numbers up to 100: 1,3,...,99. Average = (1+99)/2 = 50",
  "explanation_hi":"1 से 99 तक की विषम संख्याओं का औसत = (1+99)/2 = 50",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"Average of all even numbers between 104 and 148 is:",
  "question_text_hi":"104 और 148 के बीच की सभी सम संख्याओं का औसत कितना होगा?",
  "option_a":"128","option_a_hi":"128",
  "option_b":"130","option_b_hi":"130",
  "option_c":"124","option_c_hi":"124",
  "option_d":"126","option_d_hi":"126",
  "correct_answer":"d",
  "explanation":"Even numbers between 104 and 148: average = (106+146)/2 = 252/2 = 126",
  "explanation_hi":"104 और 148 के बीच सम संख्याओं का औसत = (106+146)/2 = 126",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average of 9 consecutive positive integers is 63. Find the product of the largest and smallest integer.",
  "question_text_hi":"9 लगातार धनात्मक पूर्णांकों का औसत 63 है। सबसे बड़े एवं सबसे छोटे पूर्णांक का गुणनफल ज्ञात करें।",
  "option_a":"3935","option_a_hi":"3935",
  "option_b":"3953","option_b_hi":"3953",
  "option_c":"3853","option_c_hi":"3853",
  "option_d":"3845","option_d_hi":"3845",
  "correct_answer":"b",
  "explanation":"Middle number = 63. Smallest = 59, Largest = 67. Product = 59×67 = 3953",
  "explanation_hi":"मध्य संख्या=63, न्यूनतम=59, अधिकतम=67, गुणनफल=59×67=3953",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average of 37 consecutive numbers is 54. The largest of these numbers is:",
  "question_text_hi":"37 लगातार संख्याओं का औसत 54 है। इन संख्याओं में सबसे बड़ी संख्या क्या है?",
  "option_a":"74","option_a_hi":"74",
  "option_b":"73","option_b_hi":"73",
  "option_c":"72","option_c_hi":"72",
  "option_d":"71","option_d_hi":"71",
  "correct_answer":"c",
  "explanation":"Middle number = 54 (18th term). Largest = 54 + 18 = 72",
  "explanation_hi":"मध्य संख्या=54, अधिकतम = 54 + 18 = 72",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average of four consecutive odd numbers is 58. What is the lowest number?",
  "question_text_hi":"चार क्रमागत विषम संख्याओं का औसत 58 है। सबसे छोटी संख्या कौन-सी है?",
  "option_a":"51","option_a_hi":"51",
  "option_b":"57","option_b_hi":"57",
  "option_c":"55","option_c_hi":"55",
  "option_d":"53","option_d_hi":"53",
  "correct_answer":"c",
  "explanation":"Let numbers be n, n+2, n+4, n+6. Average=(4n+12)/4=n+3=58 → n=55",
  "explanation_hi":"n+3=58 → n=55",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average of 28 numbers is 110. If we add a number 'B' to each number, then the average becomes 128. What is the value of B?",
  "question_text_hi":"28 संख्याओं का औसत 110 है। यदि हम प्रत्येक संख्या में एक संख्या 'B' जोड़ें, तो औसत 128 हो जाता है। B का मान क्या है?",
  "option_a":"12","option_a_hi":"12",
  "option_b":"24","option_b_hi":"24",
  "option_c":"18","option_c_hi":"18",
  "option_d":"14","option_d_hi":"14",
  "correct_answer":"c",
  "explanation":"New average = old average + B → 128 = 110 + B → B = 18",
  "explanation_hi":"नया औसत = पुराना औसत + B → B = 18",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"If the average of 50 numbers N₁, N₂, ... N₅₀ is M, then the average of N₁-100, N₂-100, ... N₅₀-100 will be:",
  "question_text_hi":"यदि 50 संख्याओं N₁, N₂, ... N₅₀ का औसत M है, तो N₁-100, N₂-100, ... N₅₀-100 का औसत क्या होगा?",
  "option_a":"100M","option_a_hi":"100M",
  "option_b":"M-50","option_b_hi":"M-50",
  "option_c":"50M","option_c_hi":"50M",
  "option_d":"M-100","option_d_hi":"M-100",
  "correct_answer":"d",
  "explanation":"When 100 is subtracted from each number, average decreases by 100. New avg = M - 100",
  "explanation_hi":"प्रत्येक से 100 घटाने पर औसत 100 कम होता है → M - 100",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average of 7 consecutive natural numbers is K. The next three natural numbers are also included. How much more than K will the average of these 10 numbers be?",
  "question_text_hi":"7 प्राकृतिक संख्याओं का औसत K है। यदि अगली 3 प्राकृतिक संख्याओं को भी सम्मिलित कर लिया जाए, तो नया औसत K से कितना अधिक होगा?",
  "option_a":"1","option_a_hi":"1",
  "option_b":"1.5","option_b_hi":"1.5",
  "option_c":"2","option_c_hi":"2",
  "option_d":"2.5","option_d_hi":"2.5",
  "correct_answer":"b",
  "explanation":"If middle number of 7 is K, sum of 10 = sum of 7 + (K+4)+(K+5)+(K+6). New avg = (7K+3K+15)/10 = K+1.5",
  "explanation_hi":"नया औसत K से 1.5 अधिक होगा",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average weight of the first thirteen persons among fourteen persons is 78 kg. The weight of the 14th person is 39 kg more than the average weight of all fourteen persons. Find the weight of the 14th person.",
  "question_text_hi":"चौदह व्यक्तियों में से पहले तेरह व्यक्तियों का औसत वजन 78 किलोग्राम है। 14वें व्यक्ति का वजन सभी चौदह व्यक्तियों के औसत वजन से 39 किलोग्राम अधिक है। 14वें व्यक्ति का वजन ज्ञात कीजिए।",
  "option_a":"110 kg","option_a_hi":"110 kg",
  "option_b":"118 kg","option_b_hi":"118 kg",
  "option_c":"98 kg","option_c_hi":"98 kg",
  "option_d":"120 kg","option_d_hi":"120 kg",
  "correct_answer":"d",
  "explanation":"Let avg of all 14 = A. 13×78+(A+39)=14A → 1053+39=13A → A=81. 14th = 81+39 = 120",
  "explanation_hi":"A=81; 14वाँ = 81+39 = 120",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"In a class of 60 students, 40% are girls. The average weight of the whole class is 59.2 kg and the average weight of the girls is 55 kg. What is the average weight of the boys?",
  "question_text_hi":"60 विद्यार्थियों की कक्षा में 40% लड़कियां हैं। पूरी कक्षा का औसत वजन 59.2 kg और लड़कियों का औसत वजन 55 kg है। लड़कों का औसत वजन कितना होगा?",
  "option_a":"63 kg","option_a_hi":"63 kg",
  "option_b":"60 kg","option_b_hi":"60 kg",
  "option_c":"61 kg","option_c_hi":"61 kg",
  "option_d":"62 kg","option_d_hi":"62 kg",
  "correct_answer":"d",
  "explanation":"Girls=24, Boys=36. Total=59.2×60=3552. Girls sum=24×55=1320. Boys sum=3552-1320=2232. Boys avg=2232/36=62",
  "explanation_hi":"लड़कियां=24, लड़के=36. लड़कों का औसत=2232/36=62",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"A batsman makes 96 runs in the 13th innings and thus his average increases by 3. Find his average after 13 innings.",
  "question_text_hi":"एक बल्लेबाज 13वीं पारी में 96 रन बनाता है और इस प्रकार उसके औसत में 3 की वृद्धि हो जाती है। 13 पारियों के बाद उसका औसत ज्ञात कीजिए।",
  "option_a":"65","option_a_hi":"65",
  "option_b":"50","option_b_hi":"50",
  "option_c":"70","option_c_hi":"70",
  "option_d":"60","option_d_hi":"60",
  "correct_answer":"d",
  "explanation":"Let avg after 12 innings = x. 12x + 96 = 13(x+3) → x=57. After 13 innings = 57+3=60",
  "explanation_hi":"12x + 96 = 13(x+3) → x=57. 13 पारी बाद = 60",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"The average weight of A, B and C is 77 kg. If the average weight of A and B is 68 kg and that of B and C is 83 kg, then the weight (in kg) of B is:",
  "question_text_hi":"A, B और C का औसत वजन 77 kg है। यदि A और B का औसत वजन 68 kg है, तथा B और C का औसत वजन 83 kg है, तो B का वजन (kg में) कितना होगा?",
  "option_a":"71","option_a_hi":"71",
  "option_b":"74","option_b_hi":"74",
  "option_c":"67","option_c_hi":"67",
  "option_d":"73","option_d_hi":"73",
  "correct_answer":"a",
  "explanation":"A+B+C=231, A+B=136, B+C=166. B=(A+B)+(B+C)-(A+B+C)=136+166-231=71",
  "explanation_hi":"A+B+C=231, A+B=136, B+C=166 → B=71",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average monthly income of P and Q is Rs 55,050. The average monthly income of Q and R is Rs 62,250 and of P and R is Rs 54,200. The monthly income of P is:",
  "question_text_hi":"P और Q की औसत मासिक आय 55050 रुपये है। Q और R की औसत मासिक आय 62250 रुपये है और P और R की औसत मासिक आय 54200 रुपये है। P की मासिक आय है:",
  "option_a":"Rs 47,000","option_a_hi":"₹47,000",
  "option_b":"Rs 48,200","option_b_hi":"₹48,200",
  "option_c":"Rs 45,600","option_c_hi":"₹45,600",
  "option_d":"Rs 51,220","option_d_hi":"₹51,220",
  "correct_answer":"a",
  "explanation":"P+Q=110100, Q+R=124500, P+R=108400. P+Q+R=(110100+124500+108400)/2=171500. P=171500-124500=47000",
  "explanation_hi":"P=171500-124500=47000",
},

# ══════════════════════════════════════════════════════
# TOPIC: Train-Race-Boat-Stream (Boat and Stream)
# ══════════════════════════════════════════════════════
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Train-Race-Boat-Stream","difficulty":"easy","phase":"main",
  "question_text":"The effective speed of a boat is 15.2 km/h against the stream and 20.8 km/h along the stream. Find the speed of the stream.",
  "question_text_hi":"एक नाव की प्रभावी चाल धारा के विरुद्ध दिशा में 15.2 km/h है और धारा की दिशा में 20.8 km/h है। धारा की चाल ज्ञात कीजिए।",
  "option_a":"18 km/h","option_a_hi":"18 km/h",
  "option_b":"1.8 km/h","option_b_hi":"1.8 km/h",
  "option_c":"2.8 km/h","option_c_hi":"2.8 km/h",
  "option_d":"3 km/h","option_d_hi":"3 km/h",
  "correct_answer":"c",
  "explanation":"Speed of stream = (downstream - upstream)/2 = (20.8-15.2)/2 = 5.6/2 = 2.8 km/h",
  "explanation_hi":"धारा की चाल = (20.8-15.2)/2 = 2.8 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Train-Race-Boat-Stream","difficulty":"easy","phase":"main",
  "question_text":"A boat covers a certain distance downstream at 33 km/hr and upstream at 14 km/hr. Find the speed of boat in still water.",
  "question_text_hi":"एक नाव एक निश्चित दूरी धारा के अनुकूल 33 किमी/घंटे और धारा के प्रतिकूल 14 किमी/घंटे की चाल से तय करती है। शांत जल में नाव की चाल ज्ञात कीजिए।",
  "option_a":"9.5 km/hr and 23.5 km/hr","option_a_hi":"9.5 km/hr और 23.5 km/hr",
  "option_b":"23.5 km/hr and 9.5 km/hr","option_b_hi":"23.5 km/hr और 9.5 km/hr",
  "option_c":"28.5 km/hr and 4.5 km/hr","option_c_hi":"28.5 km/hr और 4.5 km/hr",
  "option_d":"4.5 km/hr and 28.5 km/hr","option_d_hi":"4.5 km/hr और 28.5 km/hr",
  "correct_answer":"b",
  "explanation":"Still water speed = (33+14)/2 = 23.5; Stream speed = (33-14)/2 = 9.5",
  "explanation_hi":"शांत जल चाल = 23.5, धारा चाल = 9.5",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Train-Race-Boat-Stream","difficulty":"medium","phase":"main",
  "question_text":"A man rows 25.8 km upstream in 8.6 hours and 20 km downstream in 4 hours. What is the speed of the man in still water?",
  "question_text_hi":"एक आदमी धारा के विपरीत 25.8 किमी की दूरी 8.6 घंटे में तय करता है और धारा के अनुकूल 20 किमी की दूरी 4 घंटे में तय करता है। शांत पानी में आदमी की गति क्या है?",
  "option_a":"2 km/h","option_a_hi":"2 km/h",
  "option_b":"4 km/h","option_b_hi":"4 km/h",
  "option_c":"6 km/h","option_c_hi":"6 km/h",
  "option_d":"5 km/h","option_d_hi":"5 km/h",
  "correct_answer":"b",
  "explanation":"Upstream speed=25.8/8.6=3 km/h. Downstream=20/4=5 km/h. Still water=(3+5)/2=4 km/h",
  "explanation_hi":"अनुप्रवाह=3 km/h, अनुकूल=5 km/h, शांत जल=(3+5)/2=4 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Train-Race-Boat-Stream","difficulty":"medium","phase":"main",
  "question_text":"The speed of a boat in still water is 15 km/h and the speed of the current is 9 km/h. The distance travelled by the boat downstream in 25 minutes is:",
  "question_text_hi":"शांत जल में एक नाव की चाल 15 km/h है और धारा की चाल 9 km/h है। नाव द्वारा धारा के अनुकूल 25 मिनट में तय की गई दूरी कितनी है?",
  "option_a":"8 km","option_a_hi":"8 km",
  "option_b":"10 km","option_b_hi":"10 km",
  "option_c":"12 km","option_c_hi":"12 km",
  "option_d":"9 km","option_d_hi":"9 km",
  "correct_answer":"b",
  "explanation":"Downstream speed = 15+9 = 24 km/h. Distance = 24 × 25/60 = 10 km",
  "explanation_hi":"अनुकूल चाल = 24 km/h, दूरी = 24 × 25/60 = 10 km",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Train-Race-Boat-Stream","difficulty":"easy","phase":"main",
  "question_text":"A boat at 10 km/h in still water. If the speed of the stream is 7 km/h, what is the time taken to row a distance of 85 km downstream?",
  "question_text_hi":"एक नाव शांत जल में 10 km/h की चाल से चलती है। यदि धारा की चाल 7 km/h हो, तो धाराप्रवाह की दिशा में 85 km की दूरी तय करने में कितना समय लगता है?",
  "option_a":"5 hours","option_a_hi":"5 घंटे",
  "option_b":"4 hours","option_b_hi":"4 घंटे",
  "option_c":"6 hours","option_c_hi":"6 घंटे",
  "option_d":"3 hours","option_d_hi":"3 घंटे",
  "correct_answer":"a",
  "explanation":"Downstream speed = 10+7 = 17 km/h. Time = 85/17 = 5 hours",
  "explanation_hi":"अनुकूल चाल=17 km/h, समय=85/17=5 घंटे",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Train-Race-Boat-Stream","difficulty":"medium","phase":"main",
  "question_text":"A boat covers a distance of 375 metres upstream in 30 min, and returns back to the starting point in 18 min. Find the ratio of the speed of the boat in still water to the speed of the stream.",
  "question_text_hi":"एक नाव धारा के विपरीत दिशा में 375 मीटर की एक दूरी को 30 मिनट में तय करती है और 18 मिनट में वापस प्रारंभिक बिंदु पर आ जाती है। शांत जल में नाव की चाल और धारा की चाल का अनुपात ज्ञात करें।",
  "option_a":"5:6","option_a_hi":"5:6",
  "option_b":"7:13","option_b_hi":"7:13",
  "option_c":"13:7","option_c_hi":"13:7",
  "option_d":"4:1","option_d_hi":"4:1",
  "correct_answer":"d",
  "explanation":"Upstream=375/30=12.5 m/min; Downstream=375/18≈20.83 m/min. Still=(12.5+20.83)/2=16.67; Stream=(20.83-12.5)/2=4.17. Ratio≈4:1",
  "explanation_hi":"शांत:धारा = 4:1",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Train-Race-Boat-Stream","difficulty":"medium","phase":"main",
  "question_text":"A boat running upstream takes 8 hours 48 mins to cover a certain distance, while it takes 4 hours downstream. The speed of current is how much percentage less than speed of boat in still water?",
  "question_text_hi":"धारा के प्रतिकूल चलने वाली एक नाव को एक निश्चित दूरी तय करने में 8 घंटे 48 मिनट लगते हैं, जबकि धारा के अनुकूल 4 घंटे लगते हैं। धारा की गति शांत पानी में नाव की गति से कितना प्रतिशत कम है?",
  "option_a":"62.5%","option_a_hi":"62.5%",
  "option_b":"60%","option_b_hi":"60%",
  "option_c":"66.66%","option_c_hi":"66.66%",
  "option_d":"58.33%","option_d_hi":"58.33%",
  "correct_answer":"a",
  "explanation":"Upstream time=44/5 hr, Downstream=4 hr. Speed ratio v_u:v_d = 4:(44/5) = 5:11. Still=(5+11)/2=8 units; Stream=(11-5)/2=3 units. % by which stream < still = (8-3)/8×100 = 62.5%",
  "explanation_hi":"v_u:v_d=5:11, शांत=8 इकाई, धारा=3 इकाई। (8-3)/8×100=62.5%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Train-Race-Boat-Stream","difficulty":"hard","phase":"main",
  "question_text":"A boat takes 60% more time to cover a certain distance upstream than downstream. If the speed of current is 9 km/hr, in how much time will it cover 504 km downstream?",
  "question_text_hi":"किसी नाव के द्वारा एक निश्चित दूरी धारा के प्रतिकूल तय करने में लगा समय, धारा के अनुकूल लगने वाले समय से 60% अधिक है। यदि धारा की चाल 9 किमी./घंटे है, तो यह धारा के अनुकूल 504 किमी. की दूरी कितने समय में तय करेगी?",
  "option_a":"10 hr","option_a_hi":"10 घंटे",
  "option_b":"10.5 hr","option_b_hi":"10.5 घंटे",
  "option_c":"12 hr","option_c_hi":"12 घंटे",
  "option_d":"12.5 hr","option_d_hi":"12.5 घंटे",
  "correct_answer":"b",
  "explanation":"Time upstream = 1.6 × time downstream → distance/v_u = 1.6 × distance/v_d → v_d = 1.6 v_u. v_d-v_u=18 → 0.6 v_u=18 → v_u=30, v_d=48. Time=504/48=10.5 hr",
  "explanation_hi":"v_d=48 km/h, समय=504/48=10.5 घंटे",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Train-Race-Boat-Stream","difficulty":"hard","phase":"main",
  "question_text":"A boat starting from point P goes downstream to point Q in 3 hours and returns from Q to P in 4 hours. If the speed of water is 3 km/h, find the speed of the boat in still water.",
  "question_text_hi":"एक नाव बिंदु P से धारा की दिशा में चलना शुरू करती है और बिंदु Q तक 3 घंटे में पहुंचती है और बिंदु Q से बिंदु P पर 4 घंटे में वापस आती है। यदि जल की चाल 3 km/h है, तो शांत जल में नाव की चाल (km/h में) ज्ञात कीजिए।",
  "option_a":"12","option_a_hi":"12",
  "option_b":"20","option_b_hi":"20",
  "option_c":"21","option_c_hi":"21",
  "option_d":"32","option_d_hi":"32",
  "correct_answer":"c",
  "explanation":"Let still water speed=v. 3(v+3)=4(v-3) → 3v+9=4v-12 → v=21 km/h",
  "explanation_hi":"3(v+3)=4(v-3) → v=21 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Train-Race-Boat-Stream","difficulty":"hard","phase":"main",
  "question_text":"A boat goes 112 km downstream and comes back to the starting point in 11.5 hours. If the speed of the current is 9 km/hr, find the speed of the boat in still water.",
  "question_text_hi":"एक नाव धारा की दिशा में 112 कि.मी. दूरी तय करती है तथा आरंभिक बिंदु पर 11.5 घंटे में वापस आ जाती है। यदि धारा की चाल 9 कि.मी./घंटा है, तो शांत जल में नाव की चाल ज्ञात करें?",
  "option_a":"17 km/h","option_a_hi":"17 km/h",
  "option_b":"19 km/h","option_b_hi":"19 km/h",
  "option_c":"29 km/h","option_c_hi":"29 km/h",
  "option_d":"23 km/h","option_d_hi":"23 km/h",
  "correct_answer":"d",
  "explanation":"112/(v+9) + 112/(v-9) = 11.5. Let v=23: 112/32+112/14=3.5+8=11.5 ✓",
  "explanation_hi":"v=23 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Train-Race-Boat-Stream","difficulty":"hard","phase":"main",
  "question_text":"A boat can travel at 15.5 km/h in still water. If speed of stream is 4.5 km/h, how much time will it take to go 76 km downstream and 104.5 km upstream?",
  "question_text_hi":"एक नाव शांत जल में 15.5 km/h की चाल से यात्रा कर सकती है। यदि धारा की चाल 4.5 km/h है, तो धारा की दिशा में 76 km और धारा की विपरीत दिशा में 104.5 km जाने में कितना समय लगेगा?",
  "option_a":"15 hours 20 minutes","option_a_hi":"15 घंटे 20 मिनट",
  "option_b":"13 hours 18 minutes","option_b_hi":"13 घंटे 18 मिनट",
  "option_c":"12 hours 30 minutes","option_c_hi":"12 घंटे 30 मिनट",
  "option_d":"18 hours 13 minutes","option_d_hi":"18 घंटे 13 मिनट",
  "correct_answer":"b",
  "explanation":"Downstream=15.5+4.5=20 km/h. Upstream=15.5-4.5=11 km/h. Time=76/20+104.5/11=3.8+9.5=13.3 hr=13 hr 18 min",
  "explanation_hi":"समय=76/20+104.5/11=13 घंटे 18 मिनट",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Train-Race-Boat-Stream","difficulty":"hard","phase":"main",
  "question_text":"A boat can go 40 km downstream and 25 km upstream in 7 hours 30 minutes. It can go 48 km downstream and 36 km upstream in 10 hours. What is the speed (km/h) of the boat in still water?",
  "question_text_hi":"एक नाव 7 घंटे 30 मिनट में 40 किमी. धारा की दिशा में और 25 किमी. धारा की विपरीत दिशा में जा सकती है। यह 10 घंटे में 48 किमी. धारा की दिशा में और 36 किमी. धारा की विपरीत दिशा में जा सकती है। शांत जल में नाव की चाल (किमी/घं.) कितनी होगी?",
  "option_a":"6","option_a_hi":"6",
  "option_b":"12","option_b_hi":"12",
  "option_c":"9","option_c_hi":"9",
  "option_d":"15","option_d_hi":"15",
  "correct_answer":"c",
  "explanation":"Let d=downstream speed, u=upstream speed. 40/d+25/u=7.5; 48/d+36/u=10. Solving: 1/d=1/10, 1/u=1/6 → d=10, u=6... wait let me redo. 40/d+25/u=7.5 → multiply by 4: 160/d+100/u=30. 48/d+36/u=10 → multiply by 25/9: 400/3d+100/u=250/9. Subtract: (160-400/3)/d=30-250/9=(270-250)/9=20/9. (480-400)/3d=20/9 → 80/3d=20/9 → d=12. 40/12+25/u=7.5 → 25/u=7.5-3.33=4.17→u=6. Still water=(12+6)/2=9",
  "explanation_hi":"d=12, u=6, शांत जल चाल=(12+6)/2=9",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Train-Race-Boat-Stream","difficulty":"hard","phase":"main",
  "question_text":"A motorboat's speed is 16 km/h in still water. It takes 72 minutes more to go 36 km upstream than to return downstream to the same spot. The speed (in km/h) of the stream is:",
  "question_text_hi":"शांत जल में एक मोटरबोट की गति 16 किमी/घंटा है। धारा के प्रतिकूल 36 किमी जाने में धारा के अनुकूल समान स्थान पर लौटने की तुलना में 72 मिनट अधिक लगते हैं। धारा की गति (किमी/घंटा में) है:",
  "option_a":"8","option_a_hi":"8",
  "option_b":"10","option_b_hi":"10",
  "option_c":"4","option_c_hi":"4",
  "option_d":"5","option_d_hi":"5",
  "correct_answer":"c",
  "explanation":"36/(16-s) - 36/(16+s) = 72/60 = 1.2. 36×2s/(256-s²)=1.2. 72s=1.2(256-s²) → 60s=256-s² → s²+60s-256=0 → (s+64)(s-4)=0 → s=4",
  "explanation_hi":"s=4 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Train-Race-Boat-Stream","difficulty":"hard","phase":"main",
  "question_text":"A boat covers 24 km upstream and 36 km downstream in 10 hours, and 36 km upstream and 24 km downstream in 12 hours. The speed of the current is:",
  "question_text_hi":"एक नाव धारा के प्रतिकूल 24 km और धारा के अनुकूल 36 km की दूरी 10 घंटे में तय करती है, और धारा के प्रतिकूल 36 km और धारा के अनुकूल 24 km की दूरी 12 घंटे में तय करती है। धारा की चाल ज्ञात करें।",
  "option_a":"26/9 km/h","option_a_hi":"26/9 km/h",
  "option_b":"33/13 km/h","option_b_hi":"33/13 km/h",
  "option_c":"25/8 km/h","option_c_hi":"25/8 km/h",
  "option_d":"24/7 km/h","option_d_hi":"24/7 km/h",
  "correct_answer":"c",
  "explanation":"Let 1/u=a, 1/d=b. 24a+36b=10; 36a+24b=12. Subtracting after scaling: 60b=6 → b=1/10 → d=10. a=6.4/24=4/15 → u=3.75. Stream=(d-u)/2=(10-3.75)/2=3.125=25/8",
  "explanation_hi":"d=10, u=3.75, धारा चाल=(10-3.75)/2=25/8 km/h",
},

# ══════════════════════════════════════════════════════
# TOPIC: Compound Interest
# ══════════════════════════════════════════════════════
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"A certain sum of money becomes 2.25 times of itself in 2 years. Find the rate of interest if compounded annually.",
  "question_text_hi":"एक निश्चित धनराशि 2 वर्षों में अपने का 2.25 गुना हो जाती है। यदि चक्रवृद्धि ब्याज वार्षिक संयोजित हो, तो ब्याज दर ज्ञात करें।",
  "option_a":"25%","option_a_hi":"25%",
  "option_b":"50%","option_b_hi":"50%",
  "option_c":"15%","option_c_hi":"15%",
  "option_d":"75%","option_d_hi":"75%",
  "correct_answer":"b",
  "explanation":"2.25 = (1+r)² → 1+r = 1.5 → r = 0.5 = 50%",
  "explanation_hi":"2.25 = (1+r)² → r = 50%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"What is the rate of compound interest if a sum becomes 1331/729 times of itself in 3 years?",
  "question_text_hi":"यदि कोई राशि 3 वर्षों में स्वयं की 1331/729 गुना हो जाती है तो चक्रवृद्धि ब्याज की दर क्या है?",
  "option_a":"22 2/9%","option_a_hi":"22 2/9%",
  "option_b":"33 1/9%","option_b_hi":"33 1/9%",
  "option_c":"21 7/9%","option_c_hi":"21 7/9%",
  "option_d":"11 7/9%","option_d_hi":"11 7/9%",
  "correct_answer":"a",
  "explanation":"1331/729 = (11/9)³ → 1+r = 11/9 → r = 2/9 = 22.22% = 22 2/9%",
  "explanation_hi":"(11/9)³ → r = 2/9 = 22 2/9%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"If the amount on a certain principal in 3 years at 12% rate of interest compounded annually is Rs. 12,000, what will be the amount after the 4th year?",
  "question_text_hi":"यदि किसी मूलधन 3 वर्षो के लिए 12% की दर से बढ़कर 12,000 रुपये है, तो चौथे वर्ष के बाद राशि (रु में) क्या होगी?",
  "option_a":"13440","option_a_hi":"13440",
  "option_b":"14440","option_b_hi":"14440",
  "option_c":"15440","option_c_hi":"15440",
  "option_d":"12440","option_d_hi":"12440",
  "correct_answer":"a",
  "explanation":"Amount after 4th year = Amount after 3rd year × 1.12 = 12000 × 1.12 = 13440",
  "explanation_hi":"4 वर्ष बाद = 12000 × 1.12 = 13440",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"If the amount received at the end of 2nd and 3rd year at compound interest on a certain Principal is Rs. 9,600 and Rs. 10,272 respectively, what is the rate of interest (in %)?",
  "question_text_hi":"यदि किसी मूलधन पर दूसरे और तीसरे वर्ष में मिलने वाले मिश्रधन, चक्रवृद्धि ब्याज की दर से क्रमशः 9,600 रूपये और 10,272 रूपये है तो ब्याज की दर (% में) क्या होगी?",
  "option_a":"7","option_a_hi":"7",
  "option_b":"8","option_b_hi":"8",
  "option_c":"6","option_c_hi":"6",
  "option_d":"5","option_d_hi":"5",
  "correct_answer":"a",
  "explanation":"Rate = (10272-9600)/9600 × 100 = 672/9600 × 100 = 7%",
  "explanation_hi":"दर = (10272-9600)/9600 × 100 = 7%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"At what rate per cent per annum will a sum of Rs 15,625 amount to Rs 21,952 in three years, if the interest is compounded annually?",
  "question_text_hi":"15,625 रुपये की धनराशि, वार्षिक रूप से चक्रवृद्धि किये जाने वाले कितने प्रतिशत ब्याज दर पर 3 वर्षों में 21,952 रुपये हो जाएगी?",
  "option_a":"12%","option_a_hi":"12%",
  "option_b":"8%","option_b_hi":"8%",
  "option_c":"9%","option_c_hi":"9%",
  "option_d":"10%","option_d_hi":"10%",
  "correct_answer":"a",
  "explanation":"21952/15625 = (28/25)³ → 1+r = 28/25 → r = 3/25 = 12%",
  "explanation_hi":"21952 = 28³ और 15625 = 25³ → r = 12%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"If at compound interest a certain sum becomes 2 times itself in 5 years, in how many years will it become 8 times itself?",
  "question_text_hi":"यदि चक्रवृद्धि ब्याज पर एक निश्चित धनराशि 5 वर्षों में स्वयं की 2 गुनी हो जाती है, तो कितने वर्षों में वह स्वयं की 8 गुनी हो जाएगी?",
  "option_a":"15 years","option_a_hi":"15 वर्ष",
  "option_b":"18 years","option_b_hi":"18 वर्ष",
  "option_c":"12 years","option_c_hi":"12 वर्ष",
  "option_d":"20 years","option_d_hi":"20 वर्ष",
  "correct_answer":"a",
  "explanation":"8 = 2³, so 3 times the doubling period = 3×5 = 15 years",
  "explanation_hi":"8 = 2³, इसलिए 3 × 5 = 15 वर्ष",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"A sum of Rs 12,000 deposited at compound interest becomes double at the end of 5 years. At the end of 15 years the sum will be:",
  "question_text_hi":"चक्रवृद्धि ब्याज पर जमा की गई 12,000 रुपये की राशि 5 वर्षों के अंत में दोगुनी हो जाती है। 15 वर्षों के अंत में राशि कितनी होगी?",
  "option_a":"Rs 1,08,000","option_a_hi":"₹1,08,000",
  "option_b":"Rs 1,20,000","option_b_hi":"₹1,20,000",
  "option_c":"Rs 84,000","option_c_hi":"₹84,000",
  "option_d":"Rs 96,000","option_d_hi":"₹96,000",
  "correct_answer":"d",
  "explanation":"In 15 years (= 3 × 5 years), sum doubles 3 times: 12000 × 2³ = 12000 × 8 = 96,000",
  "explanation_hi":"15 वर्ष में 3 बार दोगुना = 12000 × 8 = 96,000",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"A sum amounts to Rs 18,600 after 3 years and to Rs 27,900 after 6 years at compound interest compounded annually. Find the sum.",
  "question_text_hi":"एक निश्चित प्रतिशत वार्षिक दर पर, जब ब्याज वार्षिक रूप से संयोजित होता है, एक धनराशि 3 वर्ष बाद 18,600 रुपये हो जाती है और 6 वर्ष बाद 27,900 रुपये हो जाती है। धनराशि है:",
  "option_a":"11,800","option_a_hi":"11,800",
  "option_b":"12,400","option_b_hi":"12,400",
  "option_c":"14,400","option_c_hi":"14,400",
  "option_d":"14,600","option_d_hi":"14,600",
  "correct_answer":"b",
  "explanation":"27900/18600 = (1+r)³ = 1.5. P × 1.5² = P × (1+r)⁶... P = 18600/√(1.5³)... Actually P×(1+r)³=18600, P×(1+r)⁶=27900 → (1+r)³=27900/18600=1.5. P=18600/1.5=12400",
  "explanation_hi":"(1+r)³=1.5, P=18600/1.5=12400",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"What will be the compound interest on Rs. 22,000 at 10% p.a. for a certain period, compounded yearly, if it is Rs. 3,864?",
  "question_text_hi":"₹18,400 की एक धनराशि पर 10% वार्षिक दर से एक निश्चित समयावधि का चक्रवृद्धि ब्याज ₹3,864 है। दोगुनी धनराशि पर, समान दर पर दोगुनी समयावधि का साधारण ब्याज (₹ में) ज्ञात कीजिए।",
  "option_a":"7,360","option_a_hi":"₹7,360",
  "option_b":"11,820","option_b_hi":"₹11,820",
  "option_c":"14,720","option_c_hi":"₹14,720",
  "option_d":"10,785","option_d_hi":"₹10,785",
  "correct_answer":"c",
  "explanation":"18400×((1.1)^n-1)=3864 → (1.1)^n=1.21 → n=2. SI on double sum for double time = 18400×2×0.10×4=14720",
  "explanation_hi":"n=2, SI=18400×2×0.1×4=14720",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"Compound interest (compounding annually) on a sum for 2 years is Rs. 4180. If rate of interest is 20% per annum, then what is the sum?",
  "question_text_hi":"किसी धनराशि पर 2 वर्षों के लिए चक्रवृद्धि ब्याज (वार्षिक रूप से संयोजित) Rs. 4180 है। यदि वार्षिक ब्याज दर 20% है, तो धनराशि कितनी है?",
  "option_a":"Rs 8800","option_a_hi":"₹8800",
  "option_b":"Rs 9800","option_b_hi":"₹9800",
  "option_c":"Rs 9500","option_c_hi":"₹9500",
  "option_d":"Rs 8500","option_d_hi":"₹8500",
  "correct_answer":"c",
  "explanation":"P×((1.2)²-1)=4180 → P×0.44=4180 → P=9500",
  "explanation_hi":"P×0.44=4180 → P=9500",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"A sum amounts to Rs 6,120 in 2 years and Rs 7,340 in 3 years at compound interest. Find the sum (in Rs) (rounded off to 2 decimal places).",
  "question_text_hi":"चक्रवृद्धि ब्याज पर एक धनराशि 2 वर्ष में ₹6,120 और 3 वर्ष में ₹7,340 हो जाती है। वह धनराशि (₹ में) क्या है?",
  "option_a":"4,560.23","option_a_hi":"4,560.23",
  "option_b":"4,850.32","option_b_hi":"4,850.32",
  "option_c":"4,254.63","option_c_hi":"4,254.63",
  "option_d":"4,050.13","option_d_hi":"4,050.13",
  "correct_answer":"d",
  "explanation":"r = 7340/6120 - 1 = 1220/6120. P = 6120/(1+r)² = 6120×6120²/7340²... r=1220/6120=61/306. P=6120/(1+61/306)²=6120×(306/367)²≈4050.13",
  "explanation_hi":"दर = 7340/6120 - 1, मूलधन ≈ 4050.13",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"The difference between compound interest and simple interest on Rs 4500 for two years at the rate of 30% for the first year and 40% for the second year will be:",
  "question_text_hi":"4500 रुपये पर दो वर्ष के लिए पहले वर्ष के लिए 30% और दूसरे वर्ष के लिए 40% की दर से चक्रवृद्धि ब्याज होगा:",
  "option_a":"Rs 8190","option_a_hi":"₹8190",
  "option_b":"Rs 4690","option_b_hi":"₹4690",
  "option_c":"Rs 3690","option_c_hi":"₹3690",
  "option_d":"Rs 9000","option_d_hi":"₹9000",
  "correct_answer":"c",
  "explanation":"Amount = 4500 × 1.3 × 1.4 = 8190. CI = 8190 - 4500 = 3690",
  "explanation_hi":"4500×1.3×1.4=8190, CI=8190-4500=3690",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"What will be the amount due on Rs. 25,000 in 2 years when the rate of interest in successive years is 12% and 10% per annum respectively (interest compounding annually)?",
  "question_text_hi":"Rs. 25,000 पर 2 वर्षों में देय राशि क्या होगी जब क्रमिक वर्षों में ब्याज दर क्रमशः 12% और 10% प्रतिवर्ष है (ब्याज का संयोजन वार्षिक रूप से किया जाता है)?",
  "option_a":"Rs 30,800","option_a_hi":"₹30,800",
  "option_b":"Rs 33,800","option_b_hi":"₹33,800",
  "option_c":"Rs 28,000","option_c_hi":"₹28,000",
  "option_d":"Rs 27,800","option_d_hi":"₹27,800",
  "correct_answer":"a",
  "explanation":"Amount = 25000 × 1.12 × 1.10 = 25000 × 1.232 = 30,800",
  "explanation_hi":"25000 × 1.12 × 1.10 = 30,800",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"The difference between the compound interest and the simple interest on a principal of ₹54,000 at the same yearly rate for a period of 2 years is ₹1,215. Find the rate of interest.",
  "question_text_hi":"₹54,000 के मूलधन पर 2 वर्ष की अवधि के लिए समान वार्षिक ब्याज दर पर चक्रवृद्धि ब्याज और साधारण ब्याज के बीच का अंतर ₹1,215 है। ब्याज दर ज्ञात कीजिए।",
  "option_a":"12%","option_a_hi":"12%",
  "option_b":"15%","option_b_hi":"15%",
  "option_c":"18%","option_c_hi":"18%",
  "option_d":"10%","option_d_hi":"10%",
  "correct_answer":"b",
  "explanation":"CI-SI for 2 years = P×r² = 54000×r² = 1215 → r² = 1215/54000 = 0.0225 → r = 0.15 = 15%",
  "explanation_hi":"P×r²=1215 → r²=1215/54000=0.0225 → r=15%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"The difference between compound interest and simple interest on ₹80,000 at the same rate of interest per annum for 2 years is ₹98. What is the rate of interest per annum?",
  "question_text_hi":"2 वर्षों के लिए प्रति वर्ष समान ब्याज दर पर ₹80,000 पर चक्रवृद्धि ब्याज और साधारण ब्याज के बीच का अंतर ₹98 है। प्रति वर्ष ब्याज दर क्या है?",
  "option_a":"3.5%","option_a_hi":"3.5%",
  "option_b":"5.5%","option_b_hi":"5.5%",
  "option_c":"2.5%","option_c_hi":"2.5%",
  "option_d":"7.5%","option_d_hi":"7.5%",
  "correct_answer":"a",
  "explanation":"P×r²=98 → 80000×r²=98 → r²=98/80000=0.001225 → r=√0.001225=0.035=3.5%",
  "explanation_hi":"80000×r²=98 → r=3.5%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"A man borrowed a sum of money and agreed to pay off by paying Rs 4200 at the end of the first year and Rs 4410 at the end of the second year. If the rate of compound interest was 5% per annum, find the sum borrowed.",
  "question_text_hi":"एक आदमी ने कुछ धनराशि उधार ली और पहले वर्ष के अंत में 4200 रुपये और दूसरे वर्ष के अंत में 4410 रुपये का भुगतान करके भुगतान करने पर सहमत हुआ। यदि चक्रवृद्धि ब्याज की दर 5% प्रति वर्ष थी, तो उधार ली गई राशि ज्ञात कीजिए।",
  "option_a":"Rs 7500","option_a_hi":"₹7500",
  "option_b":"Rs 8000","option_b_hi":"₹8000",
  "option_c":"Rs 8500","option_c_hi":"₹8500",
  "option_d":"Rs 7000","option_d_hi":"₹7000",
  "correct_answer":"b",
  "explanation":"P = 4200/1.05 + 4410/1.05² = 4000 + 4000 = 8000",
  "explanation_hi":"P = 4200/1.05 + 4410/1.1025 = 4000 + 4000 = 8000",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"The compound interest on a certain sum at 16 2/3% p.a. for 3 years is Rs 6350. What will be the simple interest on the same sum at the same rate for 5 2/3 years?",
  "question_text_hi":"एक निश्चित राशि पर 16 2/3% प्रति वर्ष की दर से 3 वर्ष के लिए चक्रवृद्धि ब्याज 6350 है। उस राशि पर उसी दर से 5 2/3 वर्ष के लिए साधारण ब्याज क्या होगा?",
  "option_a":"10,200","option_a_hi":"10,200",
  "option_b":"7,620","option_b_hi":"7,620",
  "option_c":"11,400","option_c_hi":"11,400",
  "option_d":"9,600","option_d_hi":"9,600",
  "correct_answer":"a",
  "explanation":"r=1/6. P×((7/6)³-1)=6350 → P×127/216=6350 → P=10800. SI=10800×(1/6)×(17/3)=10200",
  "explanation_hi":"P=10800, SI=10800×(1/6)×(17/3)=10200",
},
]


def seed():
    db = SessionLocal()
    try:
        existing_texts = {
            r[0]
            for r in db.query(Question.question_text)
                         .filter(Question.subject_code == "quant")
                         .all()
        }

        new_qs = [q for q in QUESTIONS if q["question_text"] not in existing_texts]

        for qdata in new_qs:
            db.add(Question(**qdata))

        db.commit()
        print(f"✓ Inserted {len(new_qs)} new questions. "
              f"({len(QUESTIONS) - len(new_qs)} already existed, "
              f"{len(QUESTIONS)} total in seed data)")
    except Exception as e:
        db.rollback()
        print(f"✗ Error: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()
