"""
37 Compound Interest questions from CI Sheet-3 images.
Run: python seed_ci_sheet5.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))

from app.database.connection import SessionLocal
from app.models.question_model import Question

QUESTIONS = [

{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"If the rate of interest is 20% per annum compounded yearly and the interest on a certain sum is Rs 250 in the second year, then what will be the interest on the same sum in the 5th year?",
  "question_text_hi":"यदि ब्याज की दर 20% प्रति वर्ष वार्षिक रूप से संयोजित है और एक निश्चित राशि पर ब्याज दूसरे वर्ष 250 रुपये है, तो उसी राशि पर 5th वर्ष में ब्याज क्या होगा?",
  "option_a":"Rs 518","option_a_hi":"₹518",
  "option_b":"Rs 360","option_b_hi":"₹360",
  "option_c":"Rs 400","option_c_hi":"₹400",
  "option_d":"Rs 432","option_d_hi":"₹432",
  "correct_answer":"d",
  "explanation":"CI_5 = CI_2 × (1+r)^3 = 250 × (1.2)^3 = 250 × 1.728 = 432",
  "explanation_hi":"CI_5 = 250 × (1.2)³ = 432",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"13th year compound interest 1024. Find the C.I. of 10th year if rate of interest is 14 2/7%.",
  "question_text_hi":"13वें वर्ष का चक्रवृद्धि ब्याज 1024 हो, तो 10वें वर्ष का चक्रवृद्धि ब्याज ज्ञात करें। यदि ब्याज की दर 14 2/7% हो।",
  "option_a":"443","option_a_hi":"443",
  "option_b":"512","option_b_hi":"512",
  "option_c":"343","option_c_hi":"343",
  "option_d":"686","option_d_hi":"686",
  "correct_answer":"d",
  "explanation":"r=100/7%=1/7. CI_13/CI_10=(1+r)^3=(8/7)^3=512/343. CI_10=1024×343/512=686",
  "explanation_hi":"CI_10=1024×343/512=686",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"At the same rate of interest, in 2 years, the simple interest is ₹42 and compound interest is ₹51. What is the principal (in ₹)?",
  "question_text_hi":"यदि समान ब्याज दर पर, 2 वर्ष में, साधारण ब्याज ₹42 तथा चक्रवृद्धि ब्याज ₹51 है, तो मूलधन (₹ में) ज्ञात कीजिए।",
  "option_a":"44","option_a_hi":"44",
  "option_b":"49","option_b_hi":"49",
  "option_c":"42","option_c_hi":"42",
  "option_d":"53","option_d_hi":"53",
  "correct_answer":"b",
  "explanation":"CI−SI=Pr²=9. SI=2Pr=42→Pr=21. r=9/21=3/7... Wait: Pr²=9, Pr=21 → r=9/21=3/7. P=21×7/3=49",
  "explanation_hi":"Pr²=9, Pr=21 → r=3/7... P=49",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"On a certain sum, simple interest for 2 years is ₹9,600 whereas the compound interest compounded annually is ₹10,176. What is the rate of interest per annum?",
  "question_text_hi":"किसी राशि पर, 2 वर्ष का साधारण ब्याज ₹9,600 होता है, जबकि वार्षिक तौर पर संयोजित होने वाला चक्रवृद्धि ब्याज ₹10,176 होता है। वार्षिक ब्याज दर क्या होगी?",
  "option_a":"9%","option_a_hi":"9%",
  "option_b":"12%","option_b_hi":"12%",
  "option_c":"10%","option_c_hi":"10%",
  "option_d":"15%","option_d_hi":"15%",
  "correct_answer":"b",
  "explanation":"CI−SI=576. Pr²=576. Pr=4800. r=576/4800=0.12=12%",
  "explanation_hi":"r=576/4800=12%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"What is the rate of interest (in%) if simple interest earned on a certain sum for 5 years is Rs 45,000 and compound interest earned for 2 years is Rs 18,630?",
  "question_text_hi":"ब्याज दर (% में) क्या है, यदि एक निश्चित राशि पर 5 साल के लिए अर्जित साधारण ब्याज 45,000 रू और 2 साल के लिए अर्जित चक्रवृद्धि ब्याज 18,630 रू है?",
  "option_a":"5","option_a_hi":"5",
  "option_b":"7","option_b_hi":"7",
  "option_c":"8","option_c_hi":"8",
  "option_d":"6","option_d_hi":"6",
  "correct_answer":"b",
  "explanation":"Pr×5=45000→Pr=9000. CI=2Pr+Pr²=18000+9000r=18630→9000r=630→r=0.07=7%",
  "explanation_hi":"9000r=630→r=7%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"The compound interest and simple interest for two years on a certain sum at a certain rate are Rs.2257.5 and Rs.2100 respectively. Find the principal and rate percent.",
  "question_text_hi":"एक निश्चित राशि पर एक निश्चित राशि पर दो साल के लिए चक्रवृद्धि ब्याज और साधारण ब्याज रु.2257.5 एवं 2100 रु क्रमशः है। P और दर प्रतिशत ज्ञात करें।",
  "option_a":"6000, 7%","option_a_hi":"6000, 7%",
  "option_b":"7500, 8%","option_b_hi":"7500, 8%",
  "option_c":"14000, 10%","option_c_hi":"14000, 10%",
  "option_d":"7000, 15%","option_d_hi":"7000, 15%",
  "correct_answer":"d",
  "explanation":"Pr²=157.5. Pr=1050. r=157.5/1050=0.15=15%. P=1050/0.15=7000",
  "explanation_hi":"r=15%, P=7000",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"If the interest earned during the 2nd year on a certain sum is ₹3726, and the rate of interest is 15% per annum compounded annually, then the sum is:",
  "question_text_hi":"किसी निश्चित धनराशि पर दूसरे वर्ष के लिए अर्जित ब्याज ₹3726 है और ब्याज दर 15% वार्षिक है, जो वार्षिक रूप से चक्रवृद्धिनुत होती है। धनराशि ज्ञात कीजिए।",
  "option_a":"₹21600","option_a_hi":"₹21600",
  "option_b":"₹20885","option_b_hi":"₹20885",
  "option_c":"₹21185","option_c_hi":"₹21185",
  "option_d":"₹20835","option_d_hi":"₹20835",
  "correct_answer":"a",
  "explanation":"CI_2 = P×r×(1+r) = P×0.15×1.15 = 0.1725P = 3726 → P = 21600",
  "explanation_hi":"P×0.1725=3726 → P=21600",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"The compound interest on a certain principal at 12.5% per annum compounded annually is Rs.1215 in the third year. Find the principal.",
  "question_text_hi":"एक निश्चित मूलधन पर, चक्रवृद्धि ब्याज की 12.5% वार्षिक दर पर, तीसरे वर्ष में चक्रवृद्धि ब्याज 1215 रू है। तो मूलधन ज्ञात कीजिए।",
  "option_a":"Rs.7680","option_a_hi":"₹7680",
  "option_b":"Rs.8640","option_b_hi":"₹8640",
  "option_c":"Rs.6912","option_c_hi":"₹6912",
  "option_d":"Rs.9216","option_d_hi":"₹9216",
  "correct_answer":"a",
  "explanation":"CI_3 = P×0.125×(1.125)² = P×0.158203 = 1215 → P = 7680",
  "explanation_hi":"P×0.158203=1215 → P=7680",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"A sum of Rs 20000 is invested for three years at compound interest. Rate: 20% first year, 15% second year, 10% third year. Find the interest for the third year.",
  "question_text_hi":"चक्रवृद्धि ब्याज पर तीन वर्षों के लिए 20000 रू का निवेश किया जाता है। पहले वर्ष के लिए ब्याज की दर 20%, दूसरे वर्ष 15% और तीसरे वर्ष 10%। तीसरे वर्ष का ब्याज ज्ञात कीजिए।",
  "option_a":"Rs 2190","option_a_hi":"₹2190",
  "option_b":"Rs 2620","option_b_hi":"₹2620",
  "option_c":"Rs 2760","option_c_hi":"₹2760",
  "option_d":"Rs 2340","option_d_hi":"₹2340",
  "correct_answer":"c",
  "explanation":"After 2 years: 20000×1.2×1.15=27600. CI in 3rd year=27600×0.10=2760",
  "explanation_hi":"27600×0.10=2760",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"The compound interest on a certain sum for one year 146 days at 14.28% per annum is Rs.408. Find the principal.",
  "question_text_hi":"एक निश्चित धनराशि पर 14.28% वार्षिक चक्रवृद्धि ब्याज की दर से 1 साल, 146 दिन में प्राप्त ब्याज 408 रुपये है। तो मूलधन ज्ञात करे?",
  "option_a":"Rs.1920","option_a_hi":"₹1920",
  "option_b":"Rs.2040","option_b_hi":"₹2040",
  "option_c":"Rs.1960","option_c_hi":"₹1960",
  "option_d":"Rs.1880","option_d_hi":"₹1880",
  "correct_answer":"c",
  "explanation":"14.28%≈1/7. 1yr146days=7/5 yrs. P×(8/7)×(37/35)−P=P×51/245=408→P=1960",
  "explanation_hi":"P×51/245=408 → P=1960",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"The difference between C.I. and S.I. on a certain sum at 15% per annum for 2 years 219 days is Rs.2061. Find the principal.",
  "question_text_hi":"एक निश्चित धनराशि पर 2 वर्ष 219 दिन में 15% की वार्षिक चक्रवृद्धि ब्याज दर पर, चक्रवृद्धि ब्याज और साधारण ब्याज के बीच का अंतर 2061 रू है, तो मूलधन ज्ञात कीजिए?",
  "option_a":"Rs.40000","option_a_hi":"₹40000",
  "option_b":"Rs.48000","option_b_hi":"₹48000",
  "option_c":"Rs.36000","option_c_hi":"₹36000",
  "option_d":"Rs.32000","option_d_hi":"₹32000",
  "correct_answer":"a",
  "explanation":"2yr 219days=13/5 yrs at 15%. CI−SI=2061 → P=40000",
  "explanation_hi":"P=40000",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"The simple interest on a certain sum at the end of three years at 5% p.a. is 1200 rupees. The compound interest on the same sum for the same period at the same rate (interest compound yearly) is:",
  "question_text_hi":"तीन साल के अंत में एक निश्चित राशि पर साधारण ब्याज 5% p.a. की दर से 1200 रुपये है। समान दर पर समान अवधि के लिए समान राशि पर चक्रवृद्धि ब्याज (वार्षिक चक्रवृद्धि ब्याज) क्या होगा?",
  "option_a":"1273","option_a_hi":"1273",
  "option_b":"1261","option_b_hi":"1261",
  "option_c":"1272","option_c_hi":"1272",
  "option_d":"1260","option_d_hi":"1260",
  "correct_answer":"b",
  "explanation":"P=1200/(3×0.05)=8000. CI=8000×((1.05)^3−1)=8000×0.157625=1261",
  "explanation_hi":"P=8000. CI=1261",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"The compound interest on a certain sum of money at 8% per annum for 3 years is ₹4,058. Find the simple interest on the same sum for 4 years at 10% p.a.",
  "question_text_hi":"एक निश्चित धनराशि पर 3 वर्षों के लिए 8% प्रति वर्ष की दर से चक्रवृद्धि ब्याज ₹4,058 है। उसी राशि पर 4 वर्ष के लिए 10% प्रति वर्ष की दर से साधारण ब्याज ज्ञात कीजिए।",
  "option_a":"Rs 6520","option_a_hi":"₹6520",
  "option_b":"Rs 6025","option_b_hi":"₹6025",
  "option_c":"Rs 6250","option_c_hi":"₹6250",
  "option_d":"Rs 6052","option_d_hi":"₹6052",
  "correct_answer":"c",
  "explanation":"P×0.259712=4058→P=15625. SI=15625×0.10×4=6250",
  "explanation_hi":"P=15625. SI=6250",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"When difference between compound and simple interest for three years is ₹228 at 4% interest per annum, the principal is ₹______",
  "question_text_hi":"यदि 4% वार्षिक ब्याज दर से तीन वर्षों के चक्रवृद्धि ब्याज तथा साधारण ब्याज का अंतर ₹228 है, तो मूलधन (₹ में) ज्ञात कीजिए।",
  "option_a":"46875","option_a_hi":"46875",
  "option_b":"48075","option_b_hi":"48075",
  "option_c":"47295","option_c_hi":"47295",
  "option_d":"46300","option_d_hi":"46300",
  "correct_answer":"a",
  "explanation":"P×[3r²+r³]=P×[0.0048+0.000064]=P×0.004864=228→P=46875",
  "explanation_hi":"P×0.004864=228→P=46875",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"If the difference between C.I and S.I for three years is Rs.840. If rate of interest is 11⅑% then find principal.",
  "question_text_hi":"3 वर्षों में चक्रवृद्धि ब्याज और साधारण ब्याज का अंतर 840 रू है। यदि ब्याज की दर 11⅑% हो तो मूलधन ज्ञात करें?",
  "option_a":"Rs.21870","option_a_hi":"₹21870",
  "option_b":"Rs.20780","option_b_hi":"₹20780",
  "option_c":"Rs.18225","option_c_hi":"₹18225",
  "option_d":"Rs.24300","option_d_hi":"₹24300",
  "correct_answer":"a",
  "explanation":"r=1/9. P×28/729=840→P=840×729/28=21870",
  "explanation_hi":"P×28/729=840→P=21870",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"If the difference between C.I and S.I for one and half year is Rs.1500. If rate of interest is 25%, interest compounded half yearly, then find principal.",
  "question_text_hi":"1 वर्ष 6 माह में चक्रवृद्धि ब्याज और साधारण ब्याज का अंतर 1500 रू है। यदि ब्याज की दर 25% हो एवं यह छमाही संयोजित किया जाता है तो मूलधन ज्ञात करें?",
  "option_a":"Rs.30720","option_a_hi":"₹30720",
  "option_b":"Rs.20480","option_b_hi":"₹20480",
  "option_c":"Rs.28800","option_c_hi":"₹28800",
  "option_d":"Rs.36000","option_d_hi":"₹36000",
  "correct_answer":"a",
  "explanation":"P×(1.125)^3−P−P×0.375=P×0.04883=1500→P≈30720",
  "explanation_hi":"P≈30720",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"If the difference between the compound interest and the simple interest on a certain sum of money at 5% per annum for 3 years is Rs.183, what is the sum of money invested?",
  "question_text_hi":"यदि एक निश्चित धनराशि पर 5% वार्षिक की दर से 3 वर्षों के लिए वार्षिक रूप से चक्रवृद्धि हुए चक्रवृद्धि ब्याज और साधारण ब्याज के बीच का अंतर Rs.183 है, तो निवेश की गई धनराशि क्या होगी?",
  "option_a":"Rs.20,000","option_a_hi":"₹20,000",
  "option_b":"Rs.28,000","option_b_hi":"₹28,000",
  "option_c":"Rs.24,000","option_c_hi":"₹24,000",
  "option_d":"Rs.16,000","option_d_hi":"₹16,000",
  "correct_answer":"c",
  "explanation":"P×0.007625=183→P=24000",
  "explanation_hi":"P×0.007625=183→P=24000",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"On simple interest and the same sum on compound interest at a certain rate per annum. If ratio between the difference of CI and SI of 2 years and that of 3 years is 25:78, what is the rate of interest per annum?",
  "question_text_hi":"एक व्यक्ति ने एक निश्चित राशि साधारण ब्याज पर और उतनी ही राशि चक्रवृद्धि ब्याज पर एक निश्चित वार्षिक ब्याज दर पर उधार दी। यदि 2 वर्ष के चक्रवृद्धि ब्याज और साधारण ब्याज और 3 वर्ष के अंतर के बीच का अनुपात 25:78 है, तो प्रति वर्ष ब्याज की दर क्या है?",
  "option_a":"16%","option_a_hi":"16%",
  "option_b":"15%","option_b_hi":"15%",
  "option_c":"10%","option_c_hi":"10%",
  "option_d":"12%","option_d_hi":"12%",
  "correct_answer":"d",
  "explanation":"(CI−SI)_2/(CI−SI)_3 = 1/(3+r) = 25/78 → 3+r=78/25=3.12 → r=0.12=12%",
  "explanation_hi":"3+r=3.12→r=12%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"Difference between CI and SI on a certain sum at a certain rate for 3 years is Rs.2541 and for 2 years it is Rs.840. Find the rate of interest per annum.",
  "question_text_hi":"एक निश्चित राशि पर एक निश्चित दर से 3 वर्षों के लिए चक्रवृद्धि ब्याज और साधारण ब्याज के बीच का अंतर 2541 रुपये है और 2 वर्षों के लिए यह 840 रुपये है। प्रति वर्ष ब्याज दर ज्ञात कीजिए?",
  "option_a":"4%","option_a_hi":"4%",
  "option_b":"2.5%","option_b_hi":"2.5%",
  "option_c":"7.5%","option_c_hi":"7.5%",
  "option_d":"3.33%","option_d_hi":"3.33%",
  "correct_answer":"b",
  "explanation":"(CI−SI)_3/(CI−SI)_2=2541/840=3+r → r=0.025=2.5%",
  "explanation_hi":"2541/840=3+r→r=2.5%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"A sum of money is accumulating at CI at a certain rate. If SI instead of compound were reckoned, interest for first two years would be Rs.70 less and for first three years by Rs.213.5. Find the sum.",
  "question_text_hi":"एक निश्चित धनराशि किसी निश्चित दर पर चक्रवृद्धि ब्याज की दर पर धन जमा किया गया है। यदि चक्रवृद्धि के बजाय साधारण ब्याज की प्रतिपूर्ति की जाती है, तो पहले दो वर्षों के लिए ब्याज 70 रु और पहले तीन वर्षों के लिए ब्याज 213.5 रु से कम हो जाएगा। तो धनराशि ज्ञात करें?",
  "option_a":"21000 Rs.","option_a_hi":"₹21000",
  "option_b":"28000 Rs.","option_b_hi":"₹28000",
  "option_c":"24500 Rs.","option_c_hi":"₹24500",
  "option_d":"35000 Rs.","option_d_hi":"₹35000",
  "correct_answer":"b",
  "explanation":"Pr²=70. (3+r)=213.5/70=3.05→r=0.05. P=70/0.0025=28000",
  "explanation_hi":"r=5%, P=28000",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"The compound interest on a sum of money for 2 years is Rs.832 and the SI on the same sum for the same period is Rs.800. The difference between CI and SI for 3 years at the same rate will be:",
  "question_text_hi":"2 साल के लिए किसी राशि पर चक्रवृद्धि ब्याज 832 रू है और उसी अवधि के लिए समान राशि पर साधारण ब्याज 800 रु है। चक्रवृद्धि ब्याज और साधारण ब्याज के बीच 3 साल के लिए समान दर पर अंतर होगा:",
  "option_a":"Rs.92.36","option_a_hi":"₹92.36",
  "option_b":"Rs.75.64","option_b_hi":"₹75.64",
  "option_c":"Rs.98.56","option_c_hi":"₹98.56",
  "option_d":"Rs.106.56","option_d_hi":"₹106.56",
  "correct_answer":"c",
  "explanation":"Pr²=32, Pr=400→r=8%, P=5000. CI−SI(3yr)=5000×0.019712=98.56",
  "explanation_hi":"P=5000, r=8%. CI−SI=98.56",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"The ratio of CI earned over 2 years when compounding annually to SI for same principal at same rate for same duration is 25:24. Find the ratio of CI earned over 3 years to SI for 3 years.",
  "question_text_hi":"2 वर्ष की अवधि में अर्जित चक्रवृद्धि ब्याज जो वार्षिक संयोजित है और समान दर पर समान अवधि में अर्जित साधारण ब्याज का अनुपात 25:24 है। उसी मूलधन पर समान दर से 3 वर्ष में अर्जित चक्रवृद्धि ब्याज और साधारण ब्याज का अनुपात ज्ञात कीजिये?",
  "option_a":"625:576","option_a_hi":"625:576",
  "option_b":"79:72","option_b_hi":"79:72",
  "option_c":"301:288","option_c_hi":"301:288",
  "option_d":"469:432","option_d_hi":"469:432",
  "correct_answer":"d",
  "explanation":"25/24=(2r+r²)/2r→r=1/12. CI(3yr)/SI(3yr)=[(13/12)^3−1]/(1/4)=469/432",
  "explanation_hi":"r=1/12. अनुपात=469:432",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"The difference between the compound interest and the simple interest on a principal of ₹54,000 at the same yearly rate for a period of 2 years is ₹1,215. Find the rate of interest.",
  "question_text_hi":"₹54,000 के मूलधन पर 2 वर्ष की अवधि के लिए समान वार्षिक ब्याज दर पर चक्रवृद्धि ब्याज और साधारण ब्याज के बीच का अंतर ₹1,215 है। ब्याज दर ज्ञात कीजिये.",
  "option_a":"12%","option_a_hi":"12%",
  "option_b":"15%","option_b_hi":"15%",
  "option_c":"18%","option_c_hi":"18%",
  "option_d":"10%","option_d_hi":"10%",
  "correct_answer":"b",
  "explanation":"54000×r²=1215→r²=0.0225→r=0.15=15%",
  "explanation_hi":"r=15%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"The difference between the compound interest and the simple interest on ₹80,000 at the same rate of interest per annum for 2 years is ₹98. What is the rate of interest per annum?",
  "question_text_hi":"2 वर्षों के लिए प्रति वर्ष समान ब्याज दर पर ₹80,000 पर चक्रवृद्धि ब्याज और साधारण ब्याज के बीच का अंतर ₹98 है। प्रति वर्ष ब्याज दर क्या है?",
  "option_a":"3½%","option_a_hi":"3½%",
  "option_b":"5½%","option_b_hi":"5½%",
  "option_c":"2½%","option_c_hi":"2½%",
  "option_d":"7½%","option_d_hi":"7½%",
  "correct_answer":"a",
  "explanation":"80000×r²=98→r²=0.001225→r=0.035=3.5%=3½%",
  "explanation_hi":"r=3½%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"If the difference between CI and SI on a certain sum of money of Rs.25200 for 2 years is Rs.700. Find rate of interest?",
  "question_text_hi":"25200 रू के धन का 2 वर्ष का साधारण ब्याज और चक्रवृद्धि ब्याज का अंतर 700 रू है तो दर ज्ञात करें?",
  "option_a":"14 1/7%","option_a_hi":"14 1/7%",
  "option_b":"16 2/3%","option_b_hi":"16 2/3%",
  "option_c":"15%","option_c_hi":"15%",
  "option_d":"13%","option_d_hi":"13%",
  "correct_answer":"b",
  "explanation":"25200×r²=700→r²=1/36→r=1/6=16.67%=16 2/3%",
  "explanation_hi":"r=1/6=16 2/3%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"Amit borrowed a sum of 25000 rupees on simple interest. Bhola borrowed the same on compound interest (compounded yearly). At end of 2 years, Bhola paid 160 rupees more interest than Amit. Rate of interest per annum is:",
  "question_text_hi":"अमित ने साधारण ब्याज पर 25000 रुपये उधार लिए। भोला ने चक्रवृद्धि ब्याज पर समान राशि उधार ली। 2 साल के अंत में, भोला को अमित की तुलना में 160 रुपये अधिक ब्याज देना पड़ा। प्रति वर्ष ब्याज की दर है:",
  "option_a":"6.4%","option_a_hi":"6.4%",
  "option_b":"8%","option_b_hi":"8%",
  "option_c":"4%","option_c_hi":"4%",
  "option_d":"4.8%","option_d_hi":"4.8%",
  "correct_answer":"b",
  "explanation":"25000×r²=160→r²=0.0064→r=0.08=8%",
  "explanation_hi":"r=8%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"A borrowed ₹58,000 from B at 8% per annum simple interest for 2 years. He lent same to C at 10% per annum compound interest annually for 2 years. How much did he earn in the transaction at end of 2 years?",
  "question_text_hi":"A ने B से ₹58,000 की राशि 8% की वार्षिक साधारण ब्याज दर पर 2 वर्ष के लिए उधार ली। उसने C को समान राशि 10% की वार्षिक चक्रवृद्धि ब्याज दर पर, जिस पर ब्याज वार्षिक रूप से चक्रवृद्धि होता है, 2 वर्ष के लिए उधार दे दी। 2 वर्ष के बाद उसे इस लेन-देन में कितनी राशि (₹ में) लाभ के रूप में प्राप्त होगी?",
  "option_a":"3,000","option_a_hi":"3,000",
  "option_b":"2,800","option_b_hi":"2,800",
  "option_c":"2,900","option_c_hi":"2,900",
  "option_d":"2,750","option_d_hi":"2,750",
  "correct_answer":"c",
  "explanation":"Pays SI: 58000×0.08×2=9280. Receives CI: 58000×0.21=12180. Profit=2900",
  "explanation_hi":"12180−9280=2900",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"A money-lender borrows at 6% per annum and pays interest at end of year. He lends at 8% CI compounded half-yearly. In this way he gains Rs.1512 a year. The amount of money he borrows is:",
  "question_text_hi":"एक साहूकार 6% वार्षिक दर से धन उधार लेता है और वर्ष के अंत में ब्याज का भुगतान करता है। वह इसे 8% वार्षिक चक्रवृद्धि ब्याज पर उधार देता है जहाँ ब्याज छमाही रूप से चक्रवृद्धि किया जाता है। इस तरह उसे वार्षिक रूप से रु. 1512 का लाभ होता है। उसके द्वारा उधार ली गई राशि ज्ञात करें।",
  "option_a":"Rs. 60,000","option_a_hi":"₹60,000",
  "option_b":"Rs. 50,000","option_b_hi":"₹50,000",
  "option_c":"Rs. 55,000","option_c_hi":"₹55,000",
  "option_d":"Rs. 70,000","option_d_hi":"₹70,000",
  "correct_answer":"d",
  "explanation":"P×(0.0816−0.06)=P×0.0216=1512→P=70000",
  "explanation_hi":"P×0.0216=1512→P=70000",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"Akhilesh borrowed ₹50,000 at a certain rate on simple interest and lent the same to Rakesh on compound interest annually at same rate. At end of 2 years, Rakesh cleared and then Akhilesh also cleared. Akhilesh earned ₹180. What was the rate per annum?",
  "question_text_hi":"अखिलेश ने साधारण ब्याज की एक निश्चित दर पर ₹50,000 की धनराशि उधार ली, और उस राशि को समान, किन्तु वार्षिक चक्रवृद्धि आधार पर गणनीय, ब्याज दर पर राकेश को उधार दे दी। 2 वर्ष की समाप्ति पर, राकेश ने अपना उधार चुकाया और फिर अखिलेश ने अपना उधार चुका दिया। इस प्रक्रिया में, अखिलेश को ₹180 का लाभ हुआ। प्रभारित वार्षिक ब्याज की दर कितनी थी?",
  "option_a":"8%","option_a_hi":"8%",
  "option_b":"6%","option_b_hi":"6%",
  "option_c":"7.5%","option_c_hi":"7.5%",
  "option_d":"5%","option_d_hi":"5%",
  "correct_answer":"b",
  "explanation":"Gain=P×r²=50000×r²=180→r²=0.0036→r=0.06=6%",
  "explanation_hi":"50000×r²=180→r=6%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"Sudha invested her savings in schemes A and B in ratio 3:5 for 1½ years. Scheme A: 20% p.a. compounded 6-monthly. Scheme B: 10% p.a. compounded annually. Difference in interests = Rs.152.60. Money invested in scheme B is:",
  "question_text_hi":"सुधा ने अपनी बचत योजनाओं A और B में 3:5 के अनुपात में 1½ वर्षों के लिए निवेश की। योजना A 20% प्रति वर्ष की दर से 6-मासिक चक्रवृद्धि ब्याज की पेशकश करती है, जबकि योजना बी 10% प्रति वर्ष की दर से वार्षिक चक्रवृद्धि ब्याज प्रदान करती है। यदि A और B से प्राप्त ब्याज के बीच का अंतर 152.60 रुपये है, तो योजना B में निवेश की गई राशि है?",
  "option_a":"Rs 4000","option_a_hi":"₹4000",
  "option_b":"Rs 4500","option_b_hi":"₹4500",
  "option_c":"Rs 3000","option_c_hi":"₹3000",
  "option_d":"Rs 3500","option_d_hi":"₹3500",
  "correct_answer":"d",
  "explanation":"3k in A: 3k×(1.1)^3−3k=0.993k. 5k in B: 5k×1.155−5k=0.775k. Diff=0.218k=152.60→k=700. B=5×700=3500",
  "explanation_hi":"k=700. B=3500",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"Rs.8454 is invested in two parts at 12% per annum compounded annually for 13 and 15 years respectively. If amount received on both investments is equal, find the difference between both investments.",
  "question_text_hi":"8454 रू की धनराशि दो भागों में क्रमशः 13 वर्ष और 15 वर्ष के लिए 12% चक्रवृद्धि ब्याज की वार्षिक दर पर निवेशित करता है। यदि इन दोनों निवेशों से सामान मिश्रधन प्राप्त होता है, तो दोनो निवेशों के बीच अंतर ज्ञात कीजिए?",
  "option_a":"Rs.954","option_a_hi":"₹954",
  "option_b":"Rs.894","option_b_hi":"₹894",
  "option_c":"Rs.1014","option_c_hi":"₹1014",
  "option_d":"Rs.1272","option_d_hi":"₹1272",
  "correct_answer":"a",
  "explanation":"P1/P2=(1.12)^2=1.2544. P1+P2=8454→P2=3750,P1=4704. Diff=954",
  "explanation_hi":"P1=4704, P2=3750. अंतर=954",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"Ashok has ₹1612. He divided it among sons Raj and Varun asking them to invest at 8% CI annually. Raj and Varun got same amount after 15 and 16 years. How much did Ashok give to Raj?",
  "question_text_hi":"अशोक के पास ₹1612 हैं। उसने इसे अपने पुत्रों राज और वरुण के बीच बांट दिया तथा उन्हें इसे वार्षिक रूप से चक्रवृद्धि होने वाली 8% ब्याज दर पर निवेश करने को कहा। यह देखा गया कि राज और वरुण को क्रमशः 15 और 16 वर्ष बाद समान धनराशि प्राप्त हुई। अशोक ने राज को कितनी धनराशि (₹ में) दी थी?",
  "option_a":"687","option_a_hi":"687",
  "option_b":"837","option_b_hi":"837",
  "option_c":"875","option_c_hi":"875",
  "option_d":"775","option_d_hi":"775",
  "correct_answer":"b",
  "explanation":"Raj×(1.08)^15=Varun×(1.08)^16→Raj=Varun×1.08. Raj+Varun=1612→2.08Varun=1612→Varun=775,Raj=837",
  "explanation_hi":"Raj=837",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"A man wants to invest Rs.1,34,470 in bank accounts of his two sons (ages 12 and 16) so they get equal amount at age 21 at 20% per annum compounded annually. Find the share of younger brother.",
  "question_text_hi":"एक व्यक्ति अपने दो पुत्रों जिनकी आयु 12 वर्ष और 16 वर्ष है, के बैंक खातों में 1,34,470 रू की धनराशि इस प्रकार निवेशित करना चाहता है कि 20% चक्रवृद्धि ब्याज की वार्षिक दर पर, पुत्रों की 21 वर्ष की आयु होने पर उन्हें समान मिश्रधन प्राप्त हो। छोटे बेटे का भाग ज्ञात कीजिए?",
  "option_a":"Rs.43750","option_a_hi":"₹43750",
  "option_b":"Rs.90720","option_b_hi":"₹90720",
  "option_c":"Rs.97200","option_c_hi":"₹97200",
  "option_d":"Rs.42250","option_d_hi":"₹42250",
  "correct_answer":"a",
  "explanation":"Younger(12yr) invests for 9yr, older(16yr) for 5yr. P_young×(1.2)^9=P_old×(1.2)^5→P_young×(1.2)^4=P_old. 2.0736P_young+P_young=134470→P_young=43750",
  "explanation_hi":"P_younger=43750",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"A person deposits money at the start of each year. If rate of interest is 12.5% per annum compounded annually and compound interest of third year is Rs.13020, find what money is deposited each year.",
  "question_text_hi":"एक व्यक्ति प्रत्येक वर्ष की शुरुआत में एक निश्चित पैसा जमा करता है। चक्रवृद्धि ब्याज की दर सालाना 12.5% है, यदि तीसरे वर्ष का चक्रवृद्धि ब्याज 13020 रु है। तो कितना धन प्रति वर्ष जमा कराया गया है?",
  "option_a":"40960 Rs.","option_a_hi":"40960",
  "option_b":"25600 Rs.","option_b_hi":"25600",
  "option_c":"38400 Rs.","option_c_hi":"38400",
  "option_d":"30720 Rs.","option_d_hi":"30720",
  "correct_answer":"d",
  "explanation":"3rd year CI = P×[(1.125)²×0.125+(1.125)×0.125+0.125]=P×0.423828=13020→P=30720",
  "explanation_hi":"P×0.423828=13020→P=30720",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"medium","phase":"main",
  "question_text":"A man borrowed a sum of money and agreed to pay off by paying Rs 4200 at the end of the first year and Rs 4410 at the end of the second year. If rate of CI was 5% per annum, find the sum borrowed.",
  "question_text_hi":"एक आदमी ने कुछ धनराशि उधार ली और पहले वर्ष के अंत में 4200 रुपये और दूसरे वर्ष के अंत में 4410 रुपये का भुगतान करके भुगतान करने पर सहमत हुआ। यदि चक्रवृद्धि ब्याज की दर 5% प्रति वर्ष थी, तो उधार ली गई राशि ज्ञात कीजिए?",
  "option_a":"Rs 7500","option_a_hi":"₹7500",
  "option_b":"Rs 8000","option_b_hi":"₹8000",
  "option_c":"Rs 8500","option_c_hi":"₹8500",
  "option_d":"Rs 7000","option_d_hi":"₹7000",
  "correct_answer":"b",
  "explanation":"P=4200/1.05+4410/1.05²=4000+4000=8000",
  "explanation_hi":"P=4000+4000=8000",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"A person borrows money at 10% per annum compound interest for 3 years. At end of 2nd year he deposits Rs.8470 and at end of 3rd year clears all debt by paying Rs.13310. What was the money he borrowed?",
  "question_text_hi":"एक व्यक्ति 3 साल के लिए 10% प्रतिवर्ष चक्रवृद्धि पर कुछ पैसा उधार लता है। दूसरे वर्ष के अंत में उसने 8470 रुपये जमा किए और तीसरे वर्ष के अंत में उसने 13310 रुपये जमा किए और ऋण मुक्त हो गया। उसने कितना पैसा उधार लिया था?",
  "option_a":"Rs. 16000","option_a_hi":"₹16000",
  "option_b":"Rs. 17000","option_b_hi":"₹17000",
  "option_c":"Rs. 18000","option_c_hi":"₹18000",
  "option_d":"Rs. 16997.7","option_d_hi":"₹16997.7",
  "correct_answer":"b",
  "explanation":"After 2yr: P×1.21. Pay 8470. Remaining: P×1.21−8470. After 3yr: (P×1.21−8470)×1.1=13310→P×1.331=22627→P=17000",
  "explanation_hi":"P×1.331=22627→P=17000",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Compound Interest","difficulty":"hard","phase":"main",
  "question_text":"A person borrowed a sum of ₹30800 at 10% p.a. for 3 years, interest compounded annually. At end of two years, he paid ₹13268. At end of 3rd year, he paid ₹x to clear the debt. What is the value of x?",
  "question_text_hi":"एक व्यक्ति ने 10% वार्षिक चक्रवृद्धि ब्याज देर पर ₹30,800 की राशि 3 वर्ष के लिए उधार ली, जिसमें ब्याज वार्षिक रूप से चक्रवृद्धि होता है। दूसरे वर्ष के अंत में, उसने ₹13,268 की राशि का भुगतान किया। तीसरे वर्ष के अंत में, उसने ऋण चुकाने के लिए ₹x का भुगतान किया। x का मान ज्ञात करें।",
  "option_a":"26200","option_a_hi":"26200",
  "option_b":"26620","option_b_hi":"26620",
  "option_c":"26400","option_c_hi":"26400",
  "option_d":"26510","option_d_hi":"26510",
  "correct_answer":"c",
  "explanation":"After 2yr: 30800×1.21=37268. Pay 13268. Remaining: 24000. After 3yr: 24000×1.1=26400",
  "explanation_hi":"24000×1.1=26400",
},

]


def seed():
    db = SessionLocal()
    try:
        existing = {
            r[0]
            for r in db.query(Question.question_text)
                         .filter(Question.subject_code == "quant",
                                 Question.topic == "Compound Interest")
                         .all()
        }
        new_qs = [q for q in QUESTIONS if q["question_text"] not in existing]
        for qdata in new_qs:
            db.add(Question(**qdata))
        db.commit()
        print(f"✓ Inserted {len(new_qs)} new CI questions. "
              f"({len(QUESTIONS)-len(new_qs)} already existed, "
              f"{len(QUESTIONS)} total in this file)")
    except Exception as e:
        db.rollback()
        print(f"✗ Error: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()
