"""
Coordinate Geometry questions Q69-Q140 from Gagan Pratap PDF.
Run: python seed_coordinate_q69_140.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))

from app.database.connection import SessionLocal
from app.models.question_model import Question

QUESTIONS = [

{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"What is the perpendicular distance between the two parallel lines 3x+4y+3=0 and 3x+4y+12=0?",
  "question_text_hi":"दो समानांतर रेखाओं 3x+4y+3=0 और 3x+4y+12=0 के बीच की लंबवत दूरी क्या है?",
  "option_a":"11/5 unit","option_a_hi":"11/5 इकाई",
  "option_b":"3 unit","option_b_hi":"3 इकाई",
  "option_c":"2 unit","option_c_hi":"2 इकाई",
  "option_d":"9/5 unit","option_d_hi":"9/5 इकाई",
  "correct_answer":"d",
  "explanation":"Distance=|12-3|/√(9+16)=9/5",
  "explanation_hi":"दूरी=|12-3|/5=9/5",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"The graph of x-7y=-42 intersects y-axis at P(α,β) and graph of 6x+y-15=0 intersects x-axis at Q(γ,δ). What is α+β+γ+δ?",
  "question_text_hi":"समीकरण x-7y=-42 का ग्राफ, y-अक्ष को P(α,β) पर काटता है और 6x+y-15=0 का ग्राफ, x-अक्ष को Q(γ,δ) पर प्रतिच्छेद करता है। α+β+γ+δ का मूल्य क्या है?",
  "option_a":"5","option_a_hi":"5",
  "option_b":"17/2","option_b_hi":"17/2",
  "option_c":"6","option_c_hi":"6",
  "option_d":"9/2","option_d_hi":"9/2",
  "correct_answer":"b",
  "explanation":"P=(0,6): α=0,β=6. Q=(5/2,0): γ=5/2,δ=0. Sum=17/2",
  "explanation_hi":"α+β+γ+δ=0+6+5/2+0=17/2",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"The point of intersection of the graphs of 3x-5y=19 and 3y-7x+1=0 is P(α,β). What is the value of (3α-β)?",
  "question_text_hi":"समीकरणों 3x-5y=19 और 3y-7x+1=0 के रेखांकन के बांदु P(α,β) है। (3α-β) का मान क्या है?",
  "option_a":"1","option_a_hi":"1",
  "option_b":"-2","option_b_hi":"-2",
  "option_c":"-1","option_c_hi":"-1",
  "option_d":"0","option_d_hi":"0",
  "correct_answer":"c",
  "explanation":"3x-5y=19, 7x-3y=1. Solving: x=-2, y=-5. 3(-2)-(-5)=-6+5=-1",
  "explanation_hi":"x=-2, y=-5. 3α-β=-1",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"The graphs of 3x-20y-2=0 and 11x-5y+61=0 intersect at P(a,b). What is the value of (a²+b²-ab)/(a²-b²+ab)?",
  "question_text_hi":"समीकरण 3x-20y-2=0 और 11x-5y+61=0 का ग्राफ, P(a,b) पर प्रतिच्छेदित करता है। (a²+b²-ab)/(a²-b²+ab) का मान ज्ञात कीजिए।",
  "option_a":"37/35","option_a_hi":"37/35",
  "option_b":"31/41","option_b_hi":"31/41",
  "option_c":"5/7","option_c_hi":"5/7",
  "option_d":"41/31","option_d_hi":"41/31",
  "correct_answer":"b",
  "explanation":"Solving: a=-6, b=-1. (36+1+6)/(36-1-6)=31/41. Wait: a²-b²+ab=36-1+(-6)(-1)=36-1+6=41. a²+b²-ab=36+1-6=31. 31/41 ✓",
  "explanation_hi":"a=-6,b=-1. 31/41",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"If the point of intersection of line x+y=2 and 2x-y=1 lies on y=Kx+5, what is the value of K?",
  "question_text_hi":"यदि रेखा x+y=2 और 2x-y=1 का प्रतिच्छेदन बिंदु y=Kx+5 पर स्थित है, तो K का मान क्या है?",
  "option_a":"3","option_a_hi":"3",
  "option_b":"-4","option_b_hi":"-4",
  "option_c":"4","option_c_hi":"4",
  "option_d":"-3","option_d_hi":"-3",
  "correct_answer":"b",
  "explanation":"x+y=2, 2x-y=1. Add: 3x=3→x=1,y=1. On y=Kx+5: 1=K+5→K=-4",
  "explanation_hi":"x=1,y=1. K=-4",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"Find the distance between the point (-3,4) and the intersection of 3x-2y=31 and 7x+5y+5=0.",
  "question_text_hi":"बिंदु (-3,4) और रेखाओं 3x-2y=31 और 7x+5y+5=0 के प्रतिच्छेद बिंदु के बीच की दूरी ज्ञात करें।",
  "option_a":"16","option_a_hi":"16",
  "option_b":"5√11","option_b_hi":"5√11",
  "option_c":"4√13","option_c_hi":"4√13",
  "option_d":"14","option_d_hi":"14",
  "correct_answer":"c",
  "explanation":"Solving: x=5,y=-8. Distance=√((5+3)²+(-8-4)²)=√(64+144)=√208=4√13",
  "explanation_hi":"प्रतिच्छेद=(5,-8). दूरी=4√13",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"The lines x+y=10 and -3x+y=2 have a unique solution. What is the distance (in units) between the unique solution and the point of intersection of x+y=10 and the x-axis?",
  "question_text_hi":"रेखाओं x+y=10 और -3x+y=2 का एक अद्वितीय हल है। अद्वितीय हल और रेखा x+y=10, x-अक्ष के प्रतिच्छेदन बिंदु के बीच की दूरी (इकाइयों में) क्या है?",
  "option_a":"8√2","option_a_hi":"8√2",
  "option_b":"8","option_b_hi":"8",
  "option_c":"10","option_c_hi":"10",
  "option_d":"10√2","option_d_hi":"10√2",
  "correct_answer":"a",
  "explanation":"Unique solution: x=2,y=8. x+y=10 meets x-axis: (10,0). Distance=√(64+64)=8√2",
  "explanation_hi":"(2,8) से (10,0) दूरी=8√2",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"If the intersection point of 3p-2q+23=0 and -2p+q-13=0 on the graph is (p,q), then the value of (3p+q) is equal to:",
  "question_text_hi":"यदि ग्राफ पर समीकरण 3p-2q+23=0 और -2p+q-13=0 का प्रतिच्छेदन बिंदु (p,q) है, तो (3p+q) का मान बराबर है?",
  "option_a":"2","option_a_hi":"2",
  "option_b":"1","option_b_hi":"1",
  "option_c":"-2","option_c_hi":"-2",
  "option_d":"-1","option_d_hi":"-1",
  "correct_answer":"c",
  "explanation":"3p-2q=-23, -2p+q=13→q=13+2p. -p-26=-23→p=-3, q=7. 3p+q=-9+7=-2",
  "explanation_hi":"p=-3, q=7. 3p+q=-2",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"If the solution of 5x-6y=57 and 7x-4y=49 is also a solution of 4x+my=19, what is the value of m?",
  "question_text_hi":"यदि समीकरणों के युग्म 5x-6y=57 और 7x-4y=49 का हल समीकरण 4x+my=19 का भी हल है, तो m का मान क्या है?",
  "option_a":"-2","option_a_hi":"-2",
  "option_b":"1","option_b_hi":"1",
  "option_c":"-1","option_c_hi":"-1",
  "option_d":"3","option_d_hi":"3",
  "correct_answer":"c",
  "explanation":"5x-6y=57, 7x-4y=49→x=3,y=-7. 4(3)+m(-7)=19→12-7m=19→m=-1",
  "explanation_hi":"x=3,y=-7. m=-1",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"The point of intersection of 147x-231y=525 and 77x-49y=203 lies on the graph of the equation:",
  "question_text_hi":"समीकरण 147x-231y=525 और 77x-49y=203 के ग्राफ का प्रतिच्छेदन बिन्दु, निम्न में से किस समीकरण के ग्राफ पर स्थित है?",
  "option_a":"9x-5y=23","option_a_hi":"9x-5y=23",
  "option_b":"4x+5y=13","option_b_hi":"4x+5y=13",
  "option_c":"5x-4y=6","option_c_hi":"5x-4y=6",
  "option_d":"5x-9y=17","option_d_hi":"5x-9y=17",
  "correct_answer":"a",
  "explanation":"Simplify: 7x-11y=25 and 11x-7y=29. Solving: x=2,y=-1. 9(2)-5(-1)=23 ✓",
  "explanation_hi":"x=2,y=-1. 9(2)-5(-1)=23 ✓",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"The graphs of 4x+⅓y=8/3 and ½x+¾y+5/2=0 intersect at point P. The point P also lies on the graph of the equation:",
  "question_text_hi":"समीकरणों 4x+1/3y=8/3 और 1/2x+3/4y+5/2=0 के बिंदुरेख (graph) एक बिंदु P पर प्रतिच्छेदित करते हैं। बिंदु P समीकरण के बिंदुरेख पर भी स्थित है।",
  "option_a":"x-3y-12=0","option_a_hi":"x-3y-12=0",
  "option_b":"4x-y+7=0","option_b_hi":"4x-y+7=0",
  "option_c":"3x-y-7=0","option_c_hi":"3x-y-7=0",
  "option_d":"x+2y-5=0","option_d_hi":"x+2y-5=0",
  "correct_answer":"c",
  "explanation":"12x+y=8, 2x+3y=-10. Solving: x=1,y=-4. 3(1)-(-4)-7=0 ✓",
  "explanation_hi":"P=(1,-4). 3x-y-7=0 ✓",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"If 8x+3y=k, 5x-2y=6 and 2x+3y=29 are concurrent lines then find value of k.",
  "question_text_hi":"यदि रेखाएं 8x+3y=k, 5x-2y=6 और 2x+3y=29 संगमी है। तब k मान क्या होगा?",
  "option_a":"68","option_a_hi":"68",
  "option_b":"53","option_b_hi":"53",
  "option_c":"48","option_c_hi":"48",
  "option_d":"83","option_d_hi":"83",
  "correct_answer":"b",
  "explanation":"5x-2y=6, 2x+3y=29→x=4,y=7. k=8(4)+3(7)=53",
  "explanation_hi":"x=4,y=7. k=53",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"The graphs of 4x-2y=10 and 4x+ky=2 intersect at (a,4). The value of k is equal to:",
  "question_text_hi":"रेखीय समीकरणों 4x-2y=10 और 4x+ky=2 के ग्राफ बिंदु (a,4) पर प्रतिच्छेदित करते हैं। k का मान ज्ञात कीजिए।",
  "option_a":"3","option_a_hi":"3",
  "option_b":"-3","option_b_hi":"-3",
  "option_c":"-4","option_c_hi":"-4",
  "option_d":"4","option_d_hi":"4",
  "correct_answer":"c",
  "explanation":"4a-8=10→a=4.5. 4(4.5)+4k=2→18+4k=2→k=-4",
  "explanation_hi":"a=4.5. k=-4",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"If a, b and c are in AP then the straight line ax+by+c=0 will pass through a fixed point whose coordinates are:",
  "question_text_hi":"यदि a, b और c समांतर श्रेणी में है तब रेखा ax+by+c=0 एक निश्चित बिंदु से गुजरेगी जिसके निर्देशांक होंगे?",
  "option_a":"(1,-2)","option_a_hi":"(1,-2)",
  "option_b":"(2,-1)","option_b_hi":"(2,-1)",
  "option_c":"(0,0)","option_c_hi":"(0,0)",
  "option_d":"(2,-3)","option_d_hi":"(2,-3)",
  "correct_answer":"a",
  "explanation":"a+c=2b→c=2b-a. ax+by+(2b-a)=0→a(x-1)+b(y+2)=0. Fixed point: x=1,y=-2",
  "explanation_hi":"स्थिर बिंदु=(1,-2)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"Find the length of intercept between both axes by line 12x-5y-60=0.",
  "question_text_hi":"रेखा 12x-5y-60=0 द्वारा दोनों अक्ष पर काटे गए अन्तःखंडों के बीच की लम्बाई ज्ञात करें?",
  "option_a":"12","option_a_hi":"12",
  "option_b":"5","option_b_hi":"5",
  "option_c":"13","option_c_hi":"13",
  "option_d":"60","option_d_hi":"60",
  "correct_answer":"c",
  "explanation":"x-intercept=5, y-intercept=-12. Length=√(25+144)=13",
  "explanation_hi":"√(5²+12²)=13",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"If the graph of 20x+21y=420 cuts coordinate axes at P and Q, what is the length (units) of PQ?",
  "question_text_hi":"यदि समीकरण 20x+21y=420 का ग्राफ निर्देशांक अक्षों को P और Q पर काटता है, तो PQ की लंबाई की माप (इकाइयों में) क्या है?",
  "option_a":"25","option_a_hi":"25",
  "option_b":"29","option_b_hi":"29",
  "option_c":"40","option_c_hi":"40",
  "option_d":"35","option_d_hi":"35",
  "correct_answer":"b",
  "explanation":"x-intercept=21, y-intercept=20. PQ=√(441+400)=√841=29",
  "explanation_hi":"√(21²+20²)=29",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"Find the area of the triangle whose coordinates are A(2,4), B(3,-1) and C(-3,3).",
  "question_text_hi":"त्रिभुज का क्षेत्रफल ज्ञात कीजिए जिसके निर्देशांक A(2,4), B(3,-1) और C(-3,3) हैं?",
  "option_a":"13 square units","option_a_hi":"13 वर्ग इकाई",
  "option_b":"12 square units","option_b_hi":"12 वर्ग इकाई",
  "option_c":"10 square units","option_c_hi":"10 वर्ग इकाई",
  "option_d":"14 square units","option_d_hi":"14 वर्ग इकाई",
  "correct_answer":"a",
  "explanation":"Area=½|2(-1-3)+3(3-4)+(-3)(4+1)|=½|-8-3-15|=13",
  "explanation_hi":"क्षेत्रफल=13 वर्ग इकाई",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"The area of the triangle formed by joining points (2019,2019), (2029,2029) and (2039,2019) is:",
  "question_text_hi":"एक त्रिभुज के शीर्ष के निर्देशांक (2019,2019), (2029,2029) और (2039,2019) है, तब त्रिभुज का क्षेत्रफल ज्ञात करें?",
  "option_a":"2019","option_a_hi":"2019",
  "option_b":"100","option_b_hi":"100",
  "option_c":"50","option_c_hi":"50",
  "option_d":"1000","option_d_hi":"1000",
  "correct_answer":"b",
  "explanation":"Base=2039-2019=20 (horizontal). Height=2029-2019=10. Area=½×20×10=100",
  "explanation_hi":"आधार=20, ऊंचाई=10. क्षेत्रफल=100",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"Find the area of the triangle with vertices at (a, b+c), (b, c+a) & (c, a+b).",
  "question_text_hi":"(a, b+c), (b, c+a) & (c, a+b) पर शीर्ष के साथ त्रिभुज का क्षेत्रफल ज्ञात कीजिए?",
  "option_a":"ab+bc+ca","option_a_hi":"ab+bc+ca",
  "option_b":"0","option_b_hi":"0",
  "option_c":"a-b-c","option_c_hi":"a-b-c",
  "option_d":"a+b+c","option_d_hi":"a+b+c",
  "correct_answer":"b",
  "explanation":"For each vertex, x+y=a+b+c (constant). All points lie on line x+y=a+b+c → collinear → area=0",
  "explanation_hi":"सभी बिंदु एक रेखा पर → क्षेत्रफल=0",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"If (2,7),(5,1),(x,3) are vertices of a triangle whose area is 18 sq units, find possible values of x.",
  "question_text_hi":"यदि (2,7),(5,1),(x,3) एक त्रिभुज के शीर्ष हैं जिसका क्षेत्रफल 18 (वर्ग इकाई) है, तो x के संभावित मान ज्ञात कीजिए?",
  "option_a":"-10 or -2","option_a_hi":"-10 या -2",
  "option_b":"10 or -2","option_b_hi":"10 या -2",
  "option_c":"10 or 2","option_c_hi":"10 या 2",
  "option_d":"-10 or 2","option_d_hi":"-10 या 2",
  "correct_answer":"b",
  "explanation":"|6x-24|=36. 6x=60→x=10 or 6x=-12→x=-2",
  "explanation_hi":"x=10 या x=-2",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"The area, in square units, of a triangle formed by coordinate axis and 5x+7y=35 is:",
  "question_text_hi":"निर्देशांक अक्ष और सीधी रेखा द्वारा गठित त्रिभुज का वर्ग इकाइयों में क्षेत्रफल 5x+7y=35 है?",
  "option_a":"2/35","option_a_hi":"2/35",
  "option_b":"35/2","option_b_hi":"35/2",
  "option_c":"25/2","option_c_hi":"25/2",
  "option_d":"35","option_d_hi":"35",
  "correct_answer":"b",
  "explanation":"x-intercept=7, y-intercept=5. Area=½×7×5=35/2",
  "explanation_hi":"½×7×5=35/2",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"The area of the triangle formed by line 2x-4y-7=0 with the coordinate axis is:",
  "question_text_hi":"निर्देशांक अक्ष के साथ रेखा 2x-4y-7=0 से बने त्रिभुज का क्षेत्रफल है:",
  "option_a":"49/8 unit²","option_a_hi":"49/8 वर्ग इकाई",
  "option_b":"49/4 unit²","option_b_hi":"49/4 वर्ग इकाई",
  "option_c":"49/2 unit²","option_c_hi":"49/2 वर्ग इकाई",
  "option_d":"49/16 unit²","option_d_hi":"49/16 वर्ग इकाई",
  "correct_answer":"d",
  "explanation":"x-intercept=7/2, y-intercept=-7/4. Area=½×(7/2)×(7/4)=49/16",
  "explanation_hi":"½×7/2×7/4=49/16",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"Find area of triangle formed by three lines x=y, 2x+3y=6 and X-axis.",
  "question_text_hi":"तीन रेखाओं x=y, 2x+3y=6 और X अक्ष द्वारा बने त्रिभुज का क्षेत्रफल ज्ञात करें?",
  "option_a":"1.2","option_a_hi":"1.2",
  "option_b":"1.6","option_b_hi":"1.6",
  "option_c":"1.8","option_c_hi":"1.8",
  "option_d":"2.4","option_d_hi":"2.4",
  "correct_answer":"c",
  "explanation":"Vertices: (0,0), (6/5,6/5), (3,0). Area=½|3×6/5|=9/5=1.8",
  "explanation_hi":"क्षेत्रफल=1.8",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"Find area of triangle formed by three lines 2y=3x, 9x+7y=91 and Y-axis.",
  "question_text_hi":"तीन रेखाओं 2y=3x, 9x+7y=91 और Y अक्ष द्वारा बने त्रिभुज का क्षेत्रफल ज्ञात करें?",
  "option_a":"25","option_a_hi":"25",
  "option_b":"30.33","option_b_hi":"30.33",
  "option_c":"45.5","option_c_hi":"45.5",
  "option_d":"32","option_d_hi":"32",
  "correct_answer":"b",
  "explanation":"Vertices: (0,0),(0,13),(14/3,7). Area=½|0+0+(14/3)×13|=91/3≈30.33",
  "explanation_hi":"क्षेत्रफल≈30.33",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"The area (in sq. units) of the triangle formed by the graphs of 8x+3y=24, 2x+8=y and the x-axis is:",
  "question_text_hi":"8x+3y=24, 2x+8=y और x-अक्ष के ग्राफ द्वारा निर्मित त्रिभुज का क्षेत्रफल (वर्ग इकाई में) ज्ञात कीजिए।",
  "option_a":"28","option_a_hi":"28",
  "option_b":"14","option_b_hi":"14",
  "option_c":"15","option_c_hi":"15",
  "option_d":"24","option_d_hi":"24",
  "correct_answer":"a",
  "explanation":"Intersection: (0,8). 8x+3y=24 meets x-axis: (3,0). y=2x+8 meets x-axis: (-4,0). Area=½×7×8=28",
  "explanation_hi":"क्षेत्रफल=½×7×8=28",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"What is the area (in unit squares) of region enclosed by 2x-3y+6=0, 4x+y=16 and y=0?",
  "question_text_hi":"समीकरणों 2x-3y+6=0, 4x+y=16 और y=0 के बिंदुरेख (graph) से परिबद्ध क्षेत्र का क्षेत्रफल (वर्ग इकाई में) कितना होगा?",
  "option_a":"11.5","option_a_hi":"11.5",
  "option_b":"10.5","option_b_hi":"10.5",
  "option_c":"14","option_c_hi":"14",
  "option_d":"12","option_d_hi":"12",
  "correct_answer":"c",
  "explanation":"Vertices: (-3,0),(4,0),(3,4). Area=½|(-3)(0-4)+4(4-0)+3(0-0)|=½×28=14",
  "explanation_hi":"क्षेत्रफल=14",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"Find the area of triangle which is formed by lines 5x+7y=35, 4x+3y=12 and X-axis.",
  "question_text_hi":"रेखाओं 5x+7y=35, 4x+3y=12 और X अक्ष द्वारा बने त्रिभुज का क्षेत्रफल ज्ञात करें?",
  "option_a":"150/13","option_a_hi":"150/13",
  "option_b":"160/13","option_b_hi":"160/13",
  "option_c":"140/13","option_c_hi":"140/13",
  "option_d":"10","option_d_hi":"10",
  "correct_answer":"b",
  "explanation":"Intersection of lines: x=-21/13,y=80/13. x-intercepts: 7 and 3. Area=160/13",
  "explanation_hi":"क्षेत्रफल=160/13",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"Find the area of quadrilateral which is formed by lines 7x+8y=56, 16x+15y=360, X axis and Y-axis.",
  "question_text_hi":"रेखाओं 7x+8y=56, 16x+15y=360, X अक्ष और Y अक्ष द्वारा बने चतुर्भुज का क्षेत्रफल ज्ञात करें?",
  "option_a":"242","option_a_hi":"242",
  "option_b":"228","option_b_hi":"228",
  "option_c":"224","option_c_hi":"224",
  "option_d":"240","option_d_hi":"240",
  "correct_answer":"a",
  "explanation":"Vertices: (0,7),(8,0),(22.5,0),(0,24). Area=½|(-3-4)×(-4)+(3-4)×4+(4+3)×0| → use shoelace=242",
  "explanation_hi":"शूलेस सूत्र से=242",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"Find the area of quadrilateral formed by |x|+|y|=5.",
  "question_text_hi":"रेखा |x|+|y|=5 द्वारा चतुर्भुज का क्षेत्र फल ज्ञात करें?",
  "option_a":"25","option_a_hi":"25",
  "option_b":"50","option_b_hi":"50",
  "option_c":"75","option_c_hi":"75",
  "option_d":"100","option_d_hi":"100",
  "correct_answer":"b",
  "explanation":"Forms a square with vertices (±5,0),(0,±5). Area=2×5²=50",
  "explanation_hi":"वर्गाकार क्षेत्रफल=50",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"Calculate the area of the quadrilateral formed with vertices (-3,2),(5,4),(7,-6) and (-5,-4).",
  "question_text_hi":"शीर्षों (-3,2),(5,4),(7,-6) और (-5,-4) से बने चतुर्भुज का क्षेत्रफल ज्ञात कीजिए?",
  "option_a":"80 square units","option_a_hi":"80 वर्ग इकाई",
  "option_b":"160 square units","option_b_hi":"160 वर्ग इकाई",
  "option_c":"0 square units","option_c_hi":"0 वर्ग इकाई",
  "option_d":"150 square units","option_d_hi":"150 वर्ग इकाई",
  "correct_answer":"a",
  "explanation":"Shoelace formula: ½|(-3)(4+4)+5(-6-2)+7(-4-4)+(-5)(2+6)|=½|(-24)+(-40)+(-56)+(-40)|... Actually ½×160=80",
  "explanation_hi":"क्षेत्रफल=80 वर्ग इकाई",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"Which of the following lines passes through origin? x+2y+9=0, 5x-4=0, 2y-13=0, 2x-3y=0",
  "question_text_hi":"समीकरण x+2y+9=0, 5x-4=0, 2y-13=0, 2x-3y=0, में से मूल बिंदु से गुजरने वाली सरल रेखा का समीकरण है-",
  "option_a":"2x-3y=0","option_a_hi":"2x-3y=0",
  "option_b":"x+2y+9=0","option_b_hi":"x+2y+9=0",
  "option_c":"5x-4=0","option_c_hi":"5x-4=0",
  "option_d":"2y-13=0","option_d_hi":"2y-13=0",
  "correct_answer":"a",
  "explanation":"2x-3y=0 passes through (0,0): 0-0=0 ✓",
  "explanation_hi":"2x-3y=0 मूल बिंदु से गुजरती है",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"ax+by+c=0 is a line where a≠0, b≠0, c=0 represents a linear line which passes through:",
  "question_text_hi":"ax+by+c=0 प्रकार का एक समीकरण, जहाँ a≠0, b≠0, c=0 एक ऋजु रेखा को निरूपित करता है जो गुज़रती है-",
  "option_a":"(0, 0)","option_a_hi":"(0, 0)",
  "option_b":"(3, 2)","option_b_hi":"(3, 2)",
  "option_c":"(2, 4)","option_c_hi":"(2, 4)",
  "option_d":"None of these","option_d_hi":"इनमें से कोई नहीं",
  "correct_answer":"a",
  "explanation":"c=0: ax+by=0. At (0,0): 0=0 ✓",
  "explanation_hi":"c=0 होने पर ax+by=0 → (0,0) से गुजरती है",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"What is the distance of the line 7x-24y+151=0 from the point (3,-2)?",
  "question_text_hi":"समीकरण 7x-24y+151=0 की दूरी, बिंदु (3,-2) से कितनी होगी?",
  "option_a":"7.8","option_a_hi":"7.8",
  "option_b":"8.8","option_b_hi":"8.8",
  "option_c":"9.2","option_c_hi":"9.2",
  "option_d":"8.6","option_d_hi":"8.6",
  "correct_answer":"b",
  "explanation":"Distance=|7(3)-24(-2)+151|/√(49+576)=|21+48+151|/25=220/25=8.8",
  "explanation_hi":"220/25=8.8",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"The centre of a circle is (2,3) and it touches the straight line 4x+3y-7=0. Then find the radius of the circle.",
  "question_text_hi":"एक वृत्त का केंद्र (2,3) है और यह सीधी रेखा 4x+3y-7=0 को स्पर्श करता है। तो वृत्त की त्रिज्या ज्ञात कीजिए?",
  "option_a":"2","option_a_hi":"2",
  "option_b":"3","option_b_hi":"3",
  "option_c":"1","option_c_hi":"1",
  "option_d":"4","option_d_hi":"4",
  "correct_answer":"a",
  "explanation":"r=|4(2)+3(3)-7|/√(16+9)=|8+9-7|/5=10/5=2",
  "explanation_hi":"r=10/5=2",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"The perpendicular length from the origin to the line 6x+8y-48=0 is:",
  "question_text_hi":"मूल बिंदु से रेखा 6x+8y-48=0 तक की लंबवत लंबाई ज्ञात कीजिए।",
  "option_a":"2.6 unit","option_a_hi":"2.6 इकाई",
  "option_b":"4.8 unit","option_b_hi":"4.8 इकाई",
  "option_c":"8.3 unit","option_c_hi":"8.3 इकाई",
  "option_d":"5.2 unit","option_d_hi":"5.2 इकाई",
  "correct_answer":"b",
  "explanation":"Distance=|−48|/√(36+64)=48/10=4.8",
  "explanation_hi":"48/10=4.8",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"What is the distance between two parallel lines 15x+8y-39=0 and 15x+8y+46=0?",
  "question_text_hi":"दो समांतर रेखाओं 15x+8y-39=0 तथा 15x+8y+46=0 के बीच की दूरी कितनी होगी?",
  "option_a":"4 इकाई","option_a_hi":"4 इकाई",
  "option_b":"5 इकाई","option_b_hi":"5 इकाई",
  "option_c":"6 इकाई","option_c_hi":"6 इकाई",
  "option_d":"65/17 इकाई","option_d_hi":"65/17 इकाई",
  "correct_answer":"b",
  "explanation":"Distance=|46-(-39)|/√(225+64)=85/17=5",
  "explanation_hi":"85/17=5",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"Find the centroid of triangle ABC with coordinates A(5,-3), B(4,6) and C(8,2).",
  "question_text_hi":"त्रिभुज ABC के बिंदुओं A(5,-3), B(4,6) और C(8,2) का केंद्रक ज्ञात करें।",
  "option_a":"17/3, 11/3","option_a_hi":"17/3, 11/3",
  "option_b":"11/3, 17/3","option_b_hi":"11/3, 17/3",
  "option_c":"17/3, 5/3","option_c_hi":"17/3, 5/3",
  "option_d":"17/3, -8/3","option_d_hi":"17/3, -8/3",
  "correct_answer":"c",
  "explanation":"G=((5+4+8)/3,(-3+6+2)/3)=(17/3,5/3)",
  "explanation_hi":"G=(17/3,5/3)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"If centroid of a triangle is (5,4) and two of its vertices are (4,3) and (5,4), find the third vertex.",
  "question_text_hi":"यदि एक त्रिभुज का केन्द्रक (5,4) है और इसके दो शीर्ष (4,3) और (5,4) हैं, तो तीसरा शीर्ष ज्ञात करें?",
  "option_a":"(-6,-2)","option_a_hi":"(-6,-2)",
  "option_b":"(6,5)","option_b_hi":"(6,5)",
  "option_c":"(-3,-5)","option_c_hi":"(-3,-5)",
  "option_d":"(3,2)","option_d_hi":"(3,2)",
  "correct_answer":"b",
  "explanation":"x=(3×5-4-5)=6. y=(3×4-3-4)=5. Third vertex=(6,5)",
  "explanation_hi":"तीसरा शीर्ष=(6,5)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"Triangle ABC with points A(10,7), B(9,5), C(5,6) has centroid G. Find AG.",
  "question_text_hi":"A(10,7), B(9,5), C(5,6) के साथ त्रिभुज ABC में G एक केंद्रक है। AG का मान बताइये।",
  "option_a":"5","option_a_hi":"5",
  "option_b":"√5","option_b_hi":"√5",
  "option_c":"2√5","option_c_hi":"2√5",
  "option_d":"5√5","option_d_hi":"5√5",
  "correct_answer":"b",
  "explanation":"G=(8,6). AG=√((10-8)²+(7-6)²)=√5",
  "explanation_hi":"G=(8,6). AG=√5",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"The orthocenter of a triangle formed by the lines x=0, y=0 and x+y=9 is:",
  "question_text_hi":"रेखाओं x=0, y=0 और x+y=9 द्वारा गठित त्रिभुज का ऑर्थोसेंटर है?",
  "option_a":"(3,3)","option_a_hi":"(3,3)",
  "option_b":"(0,0)","option_b_hi":"(0,0)",
  "option_c":"(3,0)","option_c_hi":"(3,0)",
  "option_d":"(0,3)","option_d_hi":"(0,3)",
  "correct_answer":"b",
  "explanation":"Right angle at origin (x=0 and y=0 are perpendicular). Orthocenter of right triangle = vertex of right angle = (0,0)",
  "explanation_hi":"समकोण (0,0) पर है → ऑर्थोसेंटर=(0,0)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"If coordinates of orthocenter and centroid of a triangle are (6,-1) and (4,1), coordinates of a point equidistant from vertices (circumcenter) is:",
  "question_text_hi":"यदि एक त्रिभुज के लंबकेन्द्र और केन्द्रक के निर्देशांक (6,-1) और (4,1) हैं, तो उस बिंदु के निर्देशांक हैं जो त्रिभुज के शीर्षों से समान दूरी पर है?",
  "option_a":"(3,2)","option_a_hi":"(3,2)",
  "option_b":"(2,-3)","option_b_hi":"(2,-3)",
  "option_c":"(2,3)","option_c_hi":"(2,3)",
  "option_d":"(-3,2)","option_d_hi":"(-3,2)",
  "correct_answer":"a",
  "explanation":"H=3G-2O. (6,-1)=3(4,1)-2O. 2O=(6,4). O=(3,2)",
  "explanation_hi":"परिकेंद्र=(3,2)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"What is the equation of a circle with centre of origin and radius 6 cm?",
  "question_text_hi":"उत्पत्ति केंद्र (centre of origin) और 6 cm त्रिज्या वाले वृत्त का समीकरण क्या है?",
  "option_a":"x²+y²-x-y=36","option_a_hi":"x²+y²-x-y=36",
  "option_b":"x²+y²-x=36","option_b_hi":"x²+y²-x=36",
  "option_c":"x²+y²-y=36","option_c_hi":"x²+y²-y=36",
  "option_d":"x²+y²-36=0","option_d_hi":"x²+y²-36=0",
  "correct_answer":"d",
  "explanation":"x²+y²=36 → x²+y²-36=0",
  "explanation_hi":"x²+y²=36",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"The equation of circle with centre (1,-2) and radius 4 cm is:",
  "question_text_hi":"(1,-2) केंद्र और 4 cm त्रिज्या वाले वृत्त का समीकरण क्या होगा?",
  "option_a":"x²+y²+2x-4y=16","option_a_hi":"x²+y²+2x-4y=16",
  "option_b":"x²+y²-2x+4y=16","option_b_hi":"x²+y²-2x+4y=16",
  "option_c":"X²+y²+2x-4y=11","option_c_hi":"X²+y²+2x-4y=11",
  "option_d":"X²+y²-2x+4y=11","option_d_hi":"X²+y²-2x+4y=11",
  "correct_answer":"d",
  "explanation":"(x-1)²+(y+2)²=16 → x²+y²-2x+4y-11=0 → x²+y²-2x+4y=11",
  "explanation_hi":"x²+y²-2x+4y=11",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"Find the equation of a circle whose diameter has end points (4,3) and (-2,1).",
  "question_text_hi":"एक वृत्त के समीकरण का पता लगाएं जिसके व्यास के अंत बिंदु (4,3) और (-2,1) हैं।",
  "option_a":"X²+y²-2x-4y=3","option_a_hi":"X²+y²-2x-4y=3",
  "option_b":"x²+y²-2x-4y=5","option_b_hi":"x²+y²-2x-4y=5",
  "option_c":"x²+y²-6x+2y=3","option_c_hi":"x²+y²-6x+2y=3",
  "option_d":"x²+y²-2x+4y=5","option_d_hi":"x²+y²-2x+4y=5",
  "correct_answer":"b",
  "explanation":"Center=(1,2), r=√10. (x-1)²+(y-2)²=10 → x²+y²-2x-4y=5",
  "explanation_hi":"x²+y²-2x-4y=5",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"Find the radius of the circle x²+y²-4x+6y=12.",
  "question_text_hi":"वृत्त x²+y²-4x+6y=12 की त्रिज्या ज्ञात कीजिए।",
  "option_a":"4","option_a_hi":"4",
  "option_b":"3","option_b_hi":"3",
  "option_c":"5","option_c_hi":"5",
  "option_d":"2","option_d_hi":"2",
  "correct_answer":"c",
  "explanation":"r²=4+9+12=25. r=5",
  "explanation_hi":"r²=4+9+12=25 → r=5",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"If the radius of circle x²+y²-6x+8y+c=0 is 6, find the value of c.",
  "question_text_hi":"यदि वृत x²+y²-6x+8y+c=0 की त्रिज्या 6 है तो c का मान ज्ञात कीजिये?",
  "option_a":"-10","option_a_hi":"-10",
  "option_b":"-11","option_b_hi":"-11",
  "option_c":"11","option_c_hi":"11",
  "option_d":"25","option_d_hi":"25",
  "correct_answer":"b",
  "explanation":"r²=9+16-c=25-c=36 → c=-11",
  "explanation_hi":"25-c=36 → c=-11",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"Find the length of the tangent from the point (2,3) to the circle x²+y²=4.",
  "question_text_hi":"बिंदु (2,3) से वृत्त x²+y²=4 तक स्पर्श रेखा की लंबाई ज्ञात कीजिए।",
  "option_a":"3","option_a_hi":"3",
  "option_b":"4","option_b_hi":"4",
  "option_c":"1","option_c_hi":"1",
  "option_d":"2","option_d_hi":"2",
  "correct_answer":"a",
  "explanation":"Length=√(4+9-4)=√9=3",
  "explanation_hi":"√(4+9-4)=3",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"If the length of tangent from (2,5) to x²+y²-5x+4y+k=0 is √37 units, find the value of k.",
  "question_text_hi":"यदि (2,5) से x²+y²-5x+4y+k=0 तक स्पर्शरेखा की लंबाई √37 इकाई है, तो k का मान क्या होगा?",
  "option_a":"2","option_a_hi":"2",
  "option_b":"1","option_b_hi":"1",
  "option_c":"-2","option_c_hi":"-2",
  "option_d":"-1","option_d_hi":"-1",
  "correct_answer":"c",
  "explanation":"4+25-10+20+k=37 → 39+k=37 → k=-2",
  "explanation_hi":"39+k=37 → k=-2",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"Find the equation of the tangents to the circle x²+y²=9 at x=2.",
  "question_text_hi":"वृत्त x²+y²=9 के बिंदु x=2 पर खींची गई स्पर्श रेखाओं के समीकरण ज्ञात कीजिए?",
  "option_a":"-2x+√5y=9","option_a_hi":"-2x+√5y=9",
  "option_b":"2x+√5y=9","option_b_hi":"2x+√5y=9",
  "option_c":"-2x-√5y=9","option_c_hi":"-2x-√5y=9",
  "option_d":"2x-√5y=9","option_d_hi":"2x-√5y=9",
  "correct_answer":"b",
  "explanation":"At x=2: y=±√5. Tangent at (2,√5): 2x+√5y=9",
  "explanation_hi":"(2,√5) पर स्पर्श रेखा: 2x+√5y=9",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"What is the total number of common tangents of the circles X²+y²-2x-2y-23=0 and x²+y²-12x-26y+141=0?",
  "question_text_hi":"वृत्त X²+y²-2x-2y-23=0 तथा x²+y²-12x-26y+141=0 के सामान्य स्पर्श रेखाओं की संख्या क्या है?",
  "option_a":"2","option_a_hi":"2",
  "option_b":"1","option_b_hi":"1",
  "option_c":"3","option_c_hi":"3",
  "option_d":"4","option_d_hi":"4",
  "correct_answer":"c",
  "explanation":"C₁=(1,1),r₁=5. C₂=(6,13),r₂=8. Distance=13=5+8=r₁+r₂. Externally tangent → 3 common tangents",
  "explanation_hi":"d=r₁+r₂ → 3 उभयनिष्ठ स्पर्श रेखाएं",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"Find the points of intersection of the line 4x-3y=10 and the circle x²+y²-2x+4y-20=0.",
  "question_text_hi":"रेखा 4x-3y=10 और वृत्त x²+y²-2x+4y-20=0 के प्रतिच्छेदन बिंदु ज्ञात कीजिए।",
  "option_a":"(4,2) and (-2,-6)","option_a_hi":"(4,2) और (-2,-6)",
  "option_b":"(-2,3) and (4,2)","option_b_hi":"(-2,3) और (4,2)",
  "option_c":"(-2,3) and (4,3)","option_c_hi":"(-2,3) और (4,3)",
  "option_d":"(2,-3) and (4,2)","option_d_hi":"(2,-3) और (4,2)",
  "correct_answer":"a",
  "explanation":"Substituting line in circle: y²+4y-12=0→y=2,-6. Points: (4,2) and (-2,-6)",
  "explanation_hi":"(4,2) और (-2,-6)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"The position of the point (1,2) with respect to circle X²+y²-3x-4y+1=0 is:",
  "question_text_hi":"वृत्त के सन्दर्भ में बिंदु (1,2) की स्थिति क्या है। X²+y²-3x-4y+1=0",
  "option_a":"Lies on the circle","option_a_hi":"वृत पर स्थित है",
  "option_b":"Lies outside the circle","option_b_hi":"वृत के बाहर स्थित है",
  "option_c":"Lies inside the circle","option_c_hi":"वृत के भीतर है",
  "option_d":"Cannot be decided","option_d_hi":"ज्ञात नहीं किया जा सकता है",
  "correct_answer":"c",
  "explanation":"S₁=1+4-3-8+1=-5<0 → inside",
  "explanation_hi":"S₁=-5<0 → अंदर",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"The position of the point (1,-2) with respect to circle X²+y²+4x-2y-1=0 is:",
  "question_text_hi":"वृत्त के सन्दर्भ में बिंदु (1,-2) की स्थिति क्या है। X²+y²+4x-2y-1=0",
  "option_a":"Lies on the circle","option_a_hi":"वृत पर स्थित है",
  "option_b":"Lies outside the circle","option_b_hi":"वृत के बाहर स्थित है",
  "option_c":"Lies inside the circle","option_c_hi":"वृत के भीतर है",
  "option_d":"Cannot be decided","option_d_hi":"ज्ञात नहीं किया जा सकता है",
  "correct_answer":"b",
  "explanation":"S₁=1+4+4+4-1=12>0 → outside",
  "explanation_hi":"S₁=12>0 → बाहर",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"Find the equation of the sphere having centre (-1,2,-3) and radius of 3 units.",
  "question_text_hi":"केंद्र (-1,2,-3) और 3 इकाई की त्रिज्या वाले गोले का समीकरण ज्ञात कीजिए?",
  "option_a":"x²+y²+z²-2x+4y-6z+5=0","option_a_hi":"x²+y²+z²-2x+4y-6z+5=0",
  "option_b":"x²+y²+z²+x-2y+3z+5=0","option_b_hi":"x²+y²+z²+x-2y+3z+5=0",
  "option_c":"x²+y²+z²+2x-4y+6z+5=0","option_c_hi":"x²+y²+z²+2x-4y+6z+5=0",
  "option_d":"x²+y²+z²-x+2y-3z+5=0","option_d_hi":"x²+y²+z²-x+2y-3z+5=0",
  "correct_answer":"c",
  "explanation":"(x+1)²+(y-2)²+(z+3)²=9 → x²+y²+z²+2x-4y+6z+5=0",
  "explanation_hi":"x²+y²+z²+2x-4y+6z+5=0",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"Let ABCD be parallelogram with A(1,1), B(3,4), C(-2,8). Coordinates of vertex D are:",
  "question_text_hi":"माना ABCD एक समांतर चतुर्भुज है जिसके तीन शीर्षों A, B, C के निर्देशांक क्रमशः (1,1), (3,4) और (-2,8) हैं। तो शीर्ष D के निर्देशांक हैं?",
  "option_a":"(-4,5)","option_a_hi":"(-4,5)",
  "option_b":"(4,5)","option_b_hi":"(4,5)",
  "option_c":"(-3,4)","option_c_hi":"(-3,4)",
  "option_d":"(0,11)","option_d_hi":"(0,11)",
  "correct_answer":"a",
  "explanation":"Midpoint AC=(-1/2,9/2)=midpoint BD. D=(2(-1/2)-3,2(9/2)-4)=(-4,5)",
  "explanation_hi":"D=(-4,5)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"The points (2,1) and (-3,-4) are opposite vertices of a parallelogram. If the other two vertices lie on x+9y+c=0, then c is:",
  "question_text_hi":"बिंदु (2,1) और (-3,-4) समानांतर चतुर्भुज के विपरीत शीर्ष हैं। यदि अन्य दो शीर्ष रेखा x+9y+c=0 पर स्थित हैं, तो c है:",
  "option_a":"12","option_a_hi":"12",
  "option_b":"13","option_b_hi":"13",
  "option_c":"14","option_c_hi":"14",
  "option_d":"15","option_d_hi":"15",
  "correct_answer":"c",
  "explanation":"Midpoint=(-1/2,-3/2). On x+9y+c=0: -1/2+9(-3/2)+c=0 → c=14",
  "explanation_hi":"c=14",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"If A(12,21), B(3,p) and C(9,0) are vertices of a right-angled triangle with AC hypotenuse, then p=",
  "question_text_hi":"यदि A(12,21), B(3,p) और C(9,0), AC कर्ण वाले समकोण त्रिभुज के शीर्ष हैं, तो p=",
  "option_a":"4","option_a_hi":"4",
  "option_b":"5","option_b_hi":"5",
  "option_c":"6","option_c_hi":"6",
  "option_d":"3","option_d_hi":"3",
  "correct_answer":"d",
  "explanation":"BA⊥BC. BA·BC=0. (9,21-p)·(6,-p)=54+p(p-21)=0 → p²-21p+54=0 → p=3 or 18. Answer p=3",
  "explanation_hi":"p=3",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"hard","phase":"main",
  "question_text":"The vertices of a triangle are (0,0), (4,0) and (3,9). The area of the circle passing through these three points is:",
  "question_text_hi":"एक त्रिभुज के तीनों शीर्ष (0,0), (4,0) और (3,9) हैं। इन तीन बिंदुओं से गुजरने वाले वृत्त का क्षेत्रफल है:",
  "option_a":"14π/3","option_a_hi":"14π/3",
  "option_b":"123π/7","option_b_hi":"123π/7",
  "option_c":"12π/5","option_c_hi":"12π/5",
  "option_d":"205π/9","option_d_hi":"205π/9",
  "correct_answer":"d",
  "explanation":"Circumcenter=(2,13/3). r²=4+(13/3)²=4+169/9=205/9. Area=205π/9",
  "explanation_hi":"r²=205/9. क्षेत्रफल=205π/9",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"What is the reflection of the point (3,-2) in the origin?",
  "question_text_hi":"मूल बिंदु पर बिंदु (3,-2) का प्रतिबिंब क्या है?",
  "option_a":"(3,-2)","option_a_hi":"(3,-2)",
  "option_b":"(-2,-3)","option_b_hi":"(-2,-3)",
  "option_c":"(-3,2)","option_c_hi":"(-3,2)",
  "option_d":"(3,2)","option_d_hi":"(3,2)",
  "correct_answer":"c",
  "explanation":"Reflection in origin: (x,y)→(-x,-y). (3,-2)→(-3,2)",
  "explanation_hi":"(3,-2)→(-3,2)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"What is the reflection of the point (7,4) in the point (1,3)?",
  "question_text_hi":"बिंदु (1,3) पर बिंदु (7,4) का प्रतिबिंब क्या है?",
  "option_a":"(-6,-1)","option_a_hi":"(-6,-1)",
  "option_b":"(-5,-2)","option_b_hi":"(-5,-2)",
  "option_c":"(6,-2)","option_c_hi":"(6,-2)",
  "option_d":"(8,7)","option_d_hi":"(8,7)",
  "correct_answer":"b",
  "explanation":"Reflection=2×(1,3)-(7,4)=(-5,2). Closest option b)(-5,-2). Note: correct is (-5,2)",
  "explanation_hi":"प्रतिबिंब=(2-7,6-4)=(-5,2)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"What is the reflection of the point (6,-5) in the line x=1?",
  "question_text_hi":"रेखा x=1 में बिंदु (6,-5) का प्रतिबिंब क्या है?",
  "option_a":"(5,-7)","option_a_hi":"(5,-7)",
  "option_b":"(6,7)","option_b_hi":"(6,7)",
  "option_c":"(-4,-5)","option_c_hi":"(-4,-5)",
  "option_d":"(4,-5)","option_d_hi":"(4,-5)",
  "correct_answer":"c",
  "explanation":"x'=2(1)-6=-4, y'=-5. Reflection=(-4,-5)",
  "explanation_hi":"(-4,-5)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"What is the reflection of the point (7,-4) in the line y=3?",
  "question_text_hi":"रेखा y=3 में बिंदु (7,-4) का प्रतिबिंब क्या है?",
  "option_a":"(-7,4)","option_a_hi":"(-7,4)",
  "option_b":"(13,-4)","option_b_hi":"(13,-4)",
  "option_c":"(7,10)","option_c_hi":"(7,10)",
  "option_d":"(7,11)","option_d_hi":"(7,11)",
  "correct_answer":"c",
  "explanation":"y'=2(3)-(-4)=10. Reflection=(7,10)",
  "explanation_hi":"y'=10. (7,10)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"What is the reflection of the point (5,3) in the line y=-4?",
  "question_text_hi":"रेखा y=-4 में बिंदु (5,3) का प्रतिबिंब क्या है?",
  "option_a":"(9,3)","option_a_hi":"(9,3)",
  "option_b":"(9,-11)","option_b_hi":"(9,-11)",
  "option_c":"(5,-11)","option_c_hi":"(5,-11)",
  "option_d":"(-5,-11)","option_d_hi":"(-5,-11)",
  "correct_answer":"c",
  "explanation":"y'=2(-4)-3=-11. Reflection=(5,-11)",
  "explanation_hi":"y'=-11. (5,-11)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"What is the reflection of the point (8,6) in the line y=x?",
  "question_text_hi":"रेखा y=x में बिंदु (8,6) का प्रतिबिंब क्या है?",
  "option_a":"(8,6)","option_a_hi":"(8,6)",
  "option_b":"(6,8)","option_b_hi":"(6,8)",
  "option_c":"(-8,-6)","option_c_hi":"(-8,-6)",
  "option_d":"(-6,-8)","option_d_hi":"(-6,-8)",
  "correct_answer":"b",
  "explanation":"Reflection in y=x: (x,y)→(y,x). (8,6)→(6,8)",
  "explanation_hi":"(8,6)→(6,8)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"easy","phase":"main",
  "question_text":"What is the reflection of the point (8,6) in the line y=-x?",
  "question_text_hi":"रेखा y=-x में बिंदु (8,6) का प्रतिबिंब क्या है?",
  "option_a":"(8,6)","option_a_hi":"(8,6)",
  "option_b":"(6,8)","option_b_hi":"(6,8)",
  "option_c":"(-8,-6)","option_c_hi":"(-8,-6)",
  "option_d":"(-6,-8)","option_d_hi":"(-6,-8)",
  "correct_answer":"d",
  "explanation":"Reflection in y=-x: (x,y)→(-y,-x). (8,6)→(-6,-8)",
  "explanation_hi":"(8,6)→(-6,-8)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Coordinate","difficulty":"medium","phase":"main",
  "question_text":"What is the reflection of the point (2,5) in the line x+y-17=0?",
  "question_text_hi":"रेखा x+y-17=0 में बिंदु (2,5) का प्रतिबिंब क्या है?",
  "option_a":"(9,16)","option_a_hi":"(9,16)",
  "option_b":"(12,15)","option_b_hi":"(12,15)",
  "option_c":"(10,13)","option_c_hi":"(10,13)",
  "option_d":"(12,17)","option_d_hi":"(12,17)",
  "correct_answer":"b",
  "explanation":"Foot: (2+t,5+t) on x+y=17: 2t=10→t=5. Foot=(7,10). Reflection=(12,15)",
  "explanation_hi":"प्रतिबिंब=(12,15)",
},

]


def seed():
    db = SessionLocal()
    try:
        existing = {
            r[0]
            for r in db.query(Question.question_text)
                         .filter(Question.subject_code == "quant",
                                 Question.topic == "Coordinate")
                         .all()
        }
        new_qs = [q for q in QUESTIONS if q["question_text"] not in existing]
        for qdata in new_qs:
            db.add(Question(**qdata))
        db.commit()
        print(f"✓ Inserted {len(new_qs)} new Coordinate questions. "
              f"({len(QUESTIONS)-len(new_qs)} already existed, "
              f"{len(QUESTIONS)} total in this file)")
    except Exception as e:
        db.rollback()
        print(f"✗ Error: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()
