import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app.database.connection import SessionLocal
from app.models.question_model import Question

QUESTIONS = [
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "Length of a train is 330 meters and it is moving at the speed of 72 km/h. In how much time will it take to cross a platform of length 710 meters? (ICAR Technician 2022)",
        "option_a": "64 seconds",
        "option_b": "52 seconds",
        "option_c": "56 seconds",
        "option_d": "72 seconds",
        "correct_answer": "B",
        "explanation": "Speed = 72 × 5/18 = 20 m/s. Total distance = 330 + 710 = 1040 m. Time = 1040/20 = 52 sec.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "A train is running at a speed of 99 km/h. If the train is 565 m long, then what will be the time (in seconds) taken by it to cross a 975 m long tunnel?",
        "option_a": "52",
        "option_b": "56",
        "option_c": "40",
        "option_d": "42",
        "correct_answer": "B",
        "explanation": "Speed = 99 × 5/18 = 27.5 m/s. Total = 565 + 975 = 1540 m. Time = 1540/27.5 = 56 sec.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "The platform of a station 400 m long starts exactly where the last span of a bridge 1.2 km long ends. How long will a train 200 m long travelling at 72 km/h take to cover the distance between the starting point of the span of the bridge and the far end of the platform?",
        "option_a": "1.6 min",
        "option_b": "1.5 min",
        "option_c": "1.8 min",
        "option_d": "2 min",
        "correct_answer": "B",
        "explanation": "Total distance = 1200 + 400 + 200 = 1800 m. Speed = 72 × 5/18 = 20 m/s. Time = 1800/20 = 90 sec = 1.5 min.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "A train of length 350 m crosses a bridge of length 250 m in 20 seconds. What is the speed of the train (in km/h)?",
        "option_a": "95",
        "option_b": "72",
        "option_c": "108",
        "option_d": "88",
        "correct_answer": "C",
        "explanation": "Total distance = 350 + 250 = 600 m. Speed = 600/20 = 30 m/s = 30 × 18/5 = 108 km/h.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "A train of length 348 m is running at 36 km/h. In 50 seconds, it will cross a bridge. What is the length (in m) of the bridge? (IB ACIO 2023)",
        "option_a": "152",
        "option_b": "146",
        "option_c": "176",
        "option_d": "105",
        "correct_answer": "A",
        "explanation": "Speed = 36 × 5/18 = 10 m/s. Total distance = 10 × 50 = 500 m. Bridge = 500 - 348 = 152 m.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "The speed of a train is 42 km/h. It crosses an electric pole in 27 seconds and a platform in 51 seconds. What is the length (in m) of the platform?",
        "option_a": "280",
        "option_b": "315",
        "option_c": "245",
        "option_d": "260",
        "correct_answer": "A",
        "explanation": "Speed = 42 × 5/18 = 35/3 m/s. Train length = (35/3) × 27 = 315 m. Total = (35/3) × 51 = 595 m. Platform = 595 - 315 = 280 m.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "A 315 m long train is moving at a speed of 24 km/h. It will cross a man coming from the opposite direction at a speed of 3 km/h in how many seconds?",
        "option_a": "36",
        "option_b": "38",
        "option_c": "42",
        "option_d": "40",
        "correct_answer": "C",
        "explanation": "Relative speed = 24 + 3 = 27 km/h = 7.5 m/s. Time = 315/7.5 = 42 sec.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "A train is running at 72 km/h. It crosses a 180 m long platform in 60 seconds. How many seconds will it take to cross an electric pole?",
        "option_a": "48",
        "option_b": "51",
        "option_c": "54",
        "option_d": "57",
        "correct_answer": "B",
        "explanation": "Speed = 72 × 5/18 = 20 m/s. Total distance = 20 × 60 = 1200 m. Train length = 1200 - 180 = 1020 m. Pole time = 1020/20 = 51 sec.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "If a 1952 m long train crosses a pole in 122 seconds, then find the time (in seconds) taken by the train to cross a 160 m long platform. (RRB RPF SI 2024)",
        "option_a": "128",
        "option_b": "132",
        "option_c": "135",
        "option_d": "140",
        "correct_answer": "B",
        "explanation": "Speed = 1952/122 = 16 m/s. Time for platform = (1952 + 160)/16 = 2112/16 = 132 sec.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "A train is running at 40⅔ km/h. It crosses an electric pole in 24 seconds. How long (in seconds) will it take to cross a 450 m long bridge?",
        "option_a": "56",
        "option_b": "52",
        "option_c": "60",
        "option_d": "64",
        "correct_answer": "D",
        "explanation": "Speed = (122/3) × (5/18) = 305/27 m/s. Train = (305/27) × 24 = 2440/9 m. Bridge time = (2440/9 + 450)/(305/27) = 6490/9 × 27/305 = 64 sec.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "A train crosses a pole in 12 sec, and a bridge of length 170 m in 36 sec. Then the speed of the train is:",
        "option_a": "30.75 km/h",
        "option_b": "10.8 km/h",
        "option_c": "25.5 km/h",
        "option_d": "32.45 km/h",
        "correct_answer": "C",
        "explanation": "Train length = 12v. (12v + 170)/v = 36 → 170/v = 24 → v = 85/12 m/s = 25.5 km/h.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "A train crosses two platforms having lengths 293 m and 425 m in 35 seconds and 47 seconds respectively. Find the length of the train.",
        "option_a": "92 m",
        "option_b": "78 m",
        "option_c": "99 m",
        "option_d": "88 m",
        "correct_answer": "A",
        "explanation": "Let train = L, speed = v. (L+425)-(L+293) = (47-35)v → 132 = 12v → v = 11 m/s. L = 35×11 - 293 = 92 m.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "A 629 m long train crosses a man walking at a speed of 10.4 km/h in the opposite direction in 12 seconds. What is the speed (in km/h) of the train?",
        "option_a": "183.1",
        "option_b": "178.3",
        "option_c": "176.6",
        "option_d": "177.4",
        "correct_answer": "B",
        "explanation": "Relative speed = 629/12 m/s × 18/5 = 188.7 km/h. Train speed = 188.7 - 10.4 = 178.3 km/h.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "A 315 m long train is moving at a speed of 24 km/h. In how many seconds will it cross a man walking at 3 km/h coming from the opposite direction?",
        "option_a": "36",
        "option_b": "38",
        "option_c": "42",
        "option_d": "40",
        "correct_answer": "C",
        "explanation": "Relative speed = 24 + 3 = 27 km/h = 7.5 m/s. Time = 315/7.5 = 42 sec.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "A 252 m long train is running at a speed of 125 km/h. What is the time (in seconds) in which it will pass a man who starts from the engine running at 17 km/h in the same direction as the train?",
        "option_a": "7.6",
        "option_b": "6.4",
        "option_c": "8.4",
        "option_d": "3.4",
        "correct_answer": "C",
        "explanation": "Relative speed = (125-17) km/h = 108 km/h = 30 m/s. Time = 252/30 = 8.4 sec.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "A 234 m long train passes a person running at 9 km/h in the opposite direction in 6 seconds. In how much time (in seconds) will it pass another person moving at 23.4 km/h in the same direction? (SSC CPO 2024)",
        "option_a": "6.8",
        "option_b": "7.8",
        "option_c": "7.2",
        "option_d": "8.2",
        "correct_answer": "B",
        "explanation": "Train speed = 234/6 - 2.5 = 36.5 m/s. Relative speed with person2 = 36.5 - 6.5 = 30 m/s. Time = 234/30 = 7.8 sec.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "A 240 m long train overtakes a man walking at 6 km/h in the same direction in 9 seconds. How much time (in seconds) will it take to pass a 372 m long tunnel with the same speed?",
        "option_a": "21.6",
        "option_b": "18",
        "option_c": "24",
        "option_d": "20.4",
        "correct_answer": "A",
        "explanation": "Relative speed = 240/9 = 80/3 m/s. Train speed = 80/3 + 5/3 = 85/3 m/s. Tunnel time = (240+372)/(85/3) = 612×3/85 = 21.6 sec.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "A train, 500 m long, passes a railway platform 400 m long in one minute with uniform speed. What is the time (in seconds) taken by the train to pass a man riding a motorbike travelling opposite to the direction of the train at 18 km/h?",
        "option_a": "30",
        "option_b": "48",
        "option_c": "54",
        "option_d": "25",
        "correct_answer": "D",
        "explanation": "Train speed = (500+400)/60 = 15 m/s. Motorbike: 18 km/h = 5 m/s opposite. Relative = 15+5 = 20 m/s. Time = 500/20 = 25 sec.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "The speed of a train is 78 km/h. It crosses a tunnel in 45 s and overtakes a person walking at 6 km/h in the same direction in 15 s. The length (in m) of the tunnel is:",
        "option_a": "675",
        "option_b": "650",
        "option_c": "975",
        "option_d": "780",
        "correct_answer": "A",
        "explanation": "Train length = (78-6)×5/18 × 15 = 20×15 = 300 m. Tunnel = 78×5/18×45 - 300 = 975 - 300 = 675 m.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "Trains A and B of lengths 329 m and 296 m respectively are running in opposite directions on parallel tracks at 85 km/h and 65 km/h respectively. In what time (in seconds) will they cross each other?",
        "option_a": "15",
        "option_b": "15.5",
        "option_c": "14",
        "option_d": "16.5",
        "correct_answer": "A",
        "explanation": "Total length = 329+296 = 625 m. Relative speed = (85+65)×5/18 = 125/3 m/s. Time = 625/(125/3) = 15 sec.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Train Sheet",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "A 320 m long train completely crosses a 240 m long train coming from the opposite direction in y seconds. The first train travels at 44 km/h and the second at 56.8 km/h. What is the value of y? (SSC CPO 2024)",
        "option_a": "21",
        "option_b": "18",
        "option_c": "20",
        "option_d": "22",
        "correct_answer": "C",
        "explanation": "Total length = 320+240 = 560 m. Relative speed = (44+56.8)×5/18 = 100.8×5/18 = 28 m/s. y = 560/28 = 20 sec.",
    },
]


def seed():
    db = SessionLocal()
    try:
        added = 0
        for q in QUESTIONS:
            exists = db.query(Question).filter(
                Question.question_text == q["question_text"]
            ).first()
            if not exists:
                db.add(Question(**q))
                added += 1
        db.commit()
        print(f"Seeded {added} new Train Sheet questions (skipped {len(QUESTIONS) - added} duplicates).")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
