"""
Boat and Stream questions extracted from Gagan Pratap Boat and Stream PDF (54 questions).
Run: python seed_boat_stream.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))

from app.database.connection import SessionLocal
from app.models.question_model import Question

QUESTIONS = [

{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"easy","phase":"main",
  "question_text":"The effective speed of a boat is 15.2 km/h against the stream and 20.8 km/h along the stream. Find the speed of the stream.",
  "question_text_hi":"एक नाव की प्रभावी चाल धारा के विरुद्ध दिशा में 15.2 km/h है और धारा की दिशा में 20.8 km/h है। धारा की चाल ज्ञात कीजिए।",
  "option_a":"18 km/h","option_a_hi":"18 km/h",
  "option_b":"1.8 km/h","option_b_hi":"1.8 km/h",
  "option_c":"2.8 km/h","option_c_hi":"2.8 km/h",
  "option_d":"3 km/h","option_d_hi":"3 km/h",
  "correct_answer":"c",
  "explanation":"Speed of stream = (downstream − upstream)/2 = (20.8 − 15.2)/2 = 2.8 km/h",
  "explanation_hi":"धारा की चाल = (20.8−15.2)/2 = 2.8 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"easy","phase":"main",
  "question_text":"A boat covers a certain distance downstream at 33 km/hr and upstream at 14 km/hr. Find the speed of boat in still water and speed of current.",
  "question_text_hi":"एक नाव एक निश्चित दूरी धारा के अनुकूल 33 किमी/घंटे की चाल से तय करती है। लेकिन धारा के प्रतिकूल 14 किमी/घंटे की चाल से तय करती है। शांत जल में नाव की चाल और धारा की चाल ज्ञात कीजिए।",
  "option_a":"9.5 km/hr and 23.5 km/hr","option_a_hi":"9.5 km/hr और 23.5 km/hr",
  "option_b":"23.5 km/hr and 9.5 km/hr","option_b_hi":"23.5 km/hr और 9.5 km/hr",
  "option_c":"28.5 km/hr and 4.5 km/hr","option_c_hi":"28.5 km/hr और 4.5 km/hr",
  "option_d":"4.5 km/hr and 28.5 km/hr","option_d_hi":"4.5 km/hr और 28.5 km/hr",
  "correct_answer":"b",
  "explanation":"Still water = (33+14)/2 = 23.5 km/hr; Current = (33−14)/2 = 9.5 km/hr",
  "explanation_hi":"शांत जल = 23.5 km/hr; धारा = 9.5 km/hr",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"Rahul covers 734 km in a boat in 30 hours against the stream and takes 12 hours with the stream. Find the speed of the stream.",
  "question_text_hi":"राहुल एक नाव में धारा के विपरीत 734 किमी की दूरी 30 घंटे में तय करता है और उसे धारा के साथ 12 घंटे लगते हैं तो धारा की गति ज्ञात कीजिए।",
  "option_a":"18.35 km/h","option_a_hi":"18.35 km/h",
  "option_b":"11.88 km/h","option_b_hi":"11.88 km/h",
  "option_c":"19.07 km/h","option_c_hi":"19.07 km/h",
  "option_d":"28.44 km/h","option_d_hi":"28.44 km/h",
  "correct_answer":"a",
  "explanation":"Upstream = 734/30 ≈ 24.47 km/h, Downstream = 734/12 ≈ 61.17 km/h, Stream = (61.17−24.47)/2 ≈ 18.35 km/h",
  "explanation_hi":"धारा = (61.17−24.47)/2 ≈ 18.35 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"A man rows 25.8 km upstream in 8.6 hours and a distance of 20 km downstream in 4 hours. The speed of the man in still water is:",
  "question_text_hi":"एक आदमी धारा के विपरीत 25.8 किमी की दूरी 8.6 घंटे में तय करता है और धारा के अनुकूल 20 किमी की दूरी 4 घंटे में तय करता है। शांत पानी में आदमी की गति क्या है?",
  "option_a":"2 km/h","option_a_hi":"2 km/h",
  "option_b":"4 km/h","option_b_hi":"4 km/h",
  "option_c":"6 km/h","option_c_hi":"6 km/h",
  "option_d":"5 km/h","option_d_hi":"5 km/h",
  "correct_answer":"b",
  "explanation":"Upstream = 25.8/8.6 = 3 km/h, Downstream = 20/4 = 5 km/h, Still = (3+5)/2 = 4 km/h",
  "explanation_hi":"3 और 5 का औसत = 4 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"A person rows a boat 11 km in 5 hours downstream and returns upstream in 7 hours. What is the speed of the stream in km/h?",
  "question_text_hi":"एक व्यक्ति धारा की अनुकूल दिशा में 5 घंटे में 11 किमी. नाव चलाता है और धारा की प्रतिकूल दिशा में 7 घंटे में लौटता है। किमी/घं. में धारा की चाल क्या है?",
  "option_a":"11/35 km/h","option_a_hi":"11/35 km/h",
  "option_b":"11/27 km/h","option_b_hi":"11/27 km/h",
  "option_c":"11/38 km/h","option_c_hi":"11/38 km/h",
  "option_d":"11/28 km/h","option_d_hi":"11/28 km/h",
  "correct_answer":"a",
  "explanation":"Downstream = 11/5, Upstream = 11/7. Stream = (11/5 − 11/7)/2 = 11(2/35)/2 = 11/35 km/h",
  "explanation_hi":"धारा = (11/5 − 11/7)/2 = 11/35 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"A man wishes to cover 1 km distance in river water. In still water he takes 12 minutes to cover it, but in the flowing river he takes 13 minutes. The speed of the flowing water is:",
  "question_text_hi":"एक पुरुष नदी के पानी में 1 km की दूरी तय करना चाहता है। शांत जल में इस दूरी को तय करने में उसे 12 मिनट लेकिन बहती नदी में 13 मिनट लगते हैं। नदी के बहते पानी की चाल ज्ञात करें।",
  "option_a":"25 km/h","option_a_hi":"25 km/h",
  "option_b":"5/13 km/h","option_b_hi":"5/13 km/h",
  "option_c":"22 km/h","option_c_hi":"22 km/h",
  "option_d":"7/12 km/h","option_d_hi":"7/12 km/h",
  "correct_answer":"b",
  "explanation":"Still speed = 5 km/h. Upstream = 60/13 km/h. Current = 5 − 60/13 = 5/13 km/h",
  "explanation_hi":"धारा = 5 − 60/13 = 5/13 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A man's speed in still water is 4 km/h more than the speed of the current. If the man takes a total of 10 hours to cover 45 km downstream and 35 km upstream, then the speed of the man in still water is:",
  "question_text_hi":"शांत जल में एक व्यक्ति की चाल, धारा की चाल से 4 km/h अधिक है। यदि वह व्यक्ति धारा की अनुकूल दिशा में 45 km और धारा की प्रतिकूल दिशा में 35 km की दूरी तय करने में कुल 10 घंटे लेता है, तो शांत जल में व्यक्ति की चाल कितनी है?",
  "option_a":"20 km/h","option_a_hi":"20 km/h",
  "option_b":"18 km/h","option_b_hi":"18 km/h",
  "option_c":"15 km/h","option_c_hi":"15 km/h",
  "option_d":"22 km/h","option_d_hi":"22 km/h",
  "correct_answer":"a",
  "explanation":"v = c+4. 45/(2c+4)+35/4=10. 45/(2c+4)=1.25 → 2c+4=36 → c=16, v=20",
  "explanation_hi":"c=16, v=20 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"easy","phase":"main",
  "question_text":"The speed of a boat in still water is 15 km/h and the speed of the current is 9 km/h. The distance travelled by the boat downstream in 25 minutes is:",
  "question_text_hi":"शांत जल में एक नाव की चाल 15 km/h है और धारा की चाल 9 km/h है। नाव द्वारा धारा के अनुकूल 25 मिनट में तय की गई दूरी कितनी है?",
  "option_a":"8 km","option_a_hi":"8 km",
  "option_b":"10 km","option_b_hi":"10 km",
  "option_c":"12 km","option_c_hi":"12 km",
  "option_d":"9 km","option_d_hi":"9 km",
  "correct_answer":"b",
  "explanation":"Downstream speed = 15+9 = 24 km/h. Distance = 24 × 25/60 = 10 km",
  "explanation_hi":"24 × 25/60 = 10 km",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"A person rows 3¾ km upstream in 1½ hours and 13 km downstream in 2 hours. How many hours will it take to row 90 km in still water?",
  "question_text_hi":"एक व्यक्ति नाव द्वारा धारा के प्रवाह की विपरीत दिशा में 3¾ km की दूरी 1½ घंटे में तय करता है और धारा के प्रवाह की दिशा में 13 km की दूरी 2 घंटे में तय करता है। उस व्यक्ति को स्थिर जल में 90 km की दूरी तय करने में कितना समय लगेगा?",
  "option_a":"15","option_a_hi":"15",
  "option_b":"20","option_b_hi":"20",
  "option_c":"18","option_c_hi":"18",
  "option_d":"24","option_d_hi":"24",
  "correct_answer":"b",
  "explanation":"Upstream = 3.75/1.5 = 2.5 km/h. Downstream = 13/2 = 6.5 km/h. Still = (2.5+6.5)/2 = 4.5 km/h. Time = 90/4.5 = 20 hrs",
  "explanation_hi":"शांत जल चाल=4.5, समय=90/4.5=20 घंटे",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"easy","phase":"main",
  "question_text":"A boat at 10 km/h in still water. If the speed of the stream is 7 km/h, what is the time taken to row 85 km downstream?",
  "question_text_hi":"एक व्यक्ति स्थिर जल में 10 km/h की चाल से नाव चला सकता है। यदि धारा की चाल 7 km/h हो, तो धाराप्रवाह की दिशा में 85 km तक नाव चलाने में कितना समय लगता है?",
  "option_a":"5 hours","option_a_hi":"5 घंटे",
  "option_b":"4 hours","option_b_hi":"4 घंटे",
  "option_c":"6 hours","option_c_hi":"6 घंटे",
  "option_d":"3 hours","option_d_hi":"3 घंटे",
  "correct_answer":"a",
  "explanation":"Downstream = 10+7 = 17 km/h. Time = 85/17 = 5 hours",
  "explanation_hi":"85/17 = 5 घंटे",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"A boat can travel at 15.5 km/h in still water. If speed of stream is 4.5 km/h, how much time to go 76 km downstream and 104.5 km upstream?",
  "question_text_hi":"एक नाव शांत जल में 15.5 km/h की चाल से यात्रा कर सकती है। यदि धारा की चाल 4.5 km/h है, तो धारा की दिशा में 76 km और धारा की विपरीत दिशा में 104.5 km जाने में कितना समय लगेगा?",
  "option_a":"15 hours 20 minutes","option_a_hi":"15 घंटे 20 मिनट",
  "option_b":"13 hours 18 minutes","option_b_hi":"13 घंटे 18 मिनट",
  "option_c":"12 hours 30 minutes","option_c_hi":"12 घंटे 30 मिनट",
  "option_d":"18 hours 13 minutes","option_d_hi":"18 घंटे 13 मिनट",
  "correct_answer":"b",
  "explanation":"Downstream = 20 km/h. Upstream = 11 km/h. Time = 76/20 + 104.5/11 = 3.8 + 9.5 = 13.3 hrs = 13 hr 18 min",
  "explanation_hi":"76/20 + 104.5/11 = 13 घंटे 18 मिनट",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"A boat can travel 16.9 km downstream in 52 min. If the speed of the current is 3 km/h, how much time (in hours) will the boat take to travel 84 km upstream?",
  "question_text_hi":"एक नाव 52 min में धारा के अनुकूल 16.9 km की यात्रा कर सकती है। यदि धारा की गति 3 km/h है, तो नाव को धारा के प्रतिकूल 84 km की दूरी तय करने में कितना समय (घंटों में) लगेगा?",
  "option_a":"6","option_a_hi":"6",
  "option_b":"13.5","option_b_hi":"13.5",
  "option_c":"6.22","option_c_hi":"6.22",
  "option_d":"7.5","option_d_hi":"7.5",
  "correct_answer":"c",
  "explanation":"Downstream = 16.9/(52/60) = 19.5 km/h. Still = 19.5−3 = 16.5. Upstream = 13.5. Time = 84/13.5 ≈ 6.22 hrs",
  "explanation_hi":"अनुप्रवाह = 13.5 km/h. समय = 84/13.5 ≈ 6.22",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"Two boats A and B start moving towards each other from two places 272 km apart. Speed of A in still water is 32 km/h and B is 36 km/h. If A moves downstream and B upstream, in how much time will they meet?",
  "question_text_hi":"दो नाव A और B एक दूसरे की ओर 272 km की दूरी पर स्थित दो स्थानों से चलना आरंभ होती हैं। शांत जल में नाव A और B की चाल क्रमशः 32 km/h और 36 km/h है। यदि A धारा के दिशा में चलती है और B धारा के विपरीत दिशा में चलती है, तो वे एक-दूसरे से कितने समय में मिलेगी?",
  "option_a":"4 hours","option_a_hi":"4 घंटे",
  "option_b":"3 hours","option_b_hi":"3 घंटे",
  "option_c":"5 hours","option_c_hi":"5 घंटे",
  "option_d":"6 hours","option_d_hi":"6 घंटे",
  "correct_answer":"a",
  "explanation":"Relative speed = (32+stream) + (36−stream) = 68 km/h. Time = 272/68 = 4 hours",
  "explanation_hi":"सापेक्ष चाल = 68 km/h. समय = 272/68 = 4 घंटे",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"The ratio of speed of a boat to that of current is 35:8. The boat goes along with the current in 5 hours 10 minutes. What will be the time taken by the boat to come back?",
  "question_text_hi":"एक नाव की गति और धारा की गति का अनुपात 35:8 है। नाव धारा के अनुकूल 5 घंटे 10 मिनट में जाती है। नाव को वापस आने में कितना समय लगेगा?",
  "option_a":"5 hours 15 minutes 58 seconds","option_a_hi":"5 घंटे 15 मिनट 58 सेकंड",
  "option_b":"6 hours 45 minutes 10 seconds","option_b_hi":"6 घंटे 45 मिनट 10 सेकंड",
  "option_c":"8 hours 13 minutes 48 seconds","option_c_hi":"8 घंटे 13 मिनट 48 सेकंड",
  "option_d":"9 hours 30 minutes 49 seconds","option_d_hi":"9 घंटे 30 मिनट 49 सेकंड",
  "correct_answer":"c",
  "explanation":"Still=35k, current=8k. Downstream=43k, Upstream=27k. Distance=43k×31/6. Upstream time=43×31/(6×27)=1333/162≈8.228 hrs≈8h13m48s",
  "explanation_hi":"वापस समय = 43×31/(6×27) ≈ 8h 13m 48s",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"Speed of boat in still water is 25 km/hr and stream is 7 km/hr. A boat goes from A to B and back in 6 hours 40 minutes. Find the time to cover twice the distance AB downstream.",
  "question_text_hi":"स्थिर पानी में नाव की गति 25 किमी/घंटा है। और धारा की गति 7 किमी / घंटा है। यदि एक नाव द्वारा जगह A से B तक जाने में और B से A तक लौटने में उसे कुल 6 घंटे 40 मिनट लगते हैं। नाव द्वारा धारा के अनुकूल प्रवाह में AB के दुगुनी दूरी तय करने के लिए नाव द्वारा लिया गया समय ज्ञात कीजिए।",
  "option_a":"3 hours 36 minutes","option_a_hi":"3 घंटे 36 मिनट",
  "option_b":"4 hours 16 minutes","option_b_hi":"4 घंटे 16 मिनट",
  "option_c":"5 hours 12 minutes","option_c_hi":"5 घंटे 12 मिनट",
  "option_d":"4 hours 48 minutes","option_d_hi":"4 घंटे 48 मिनट",
  "correct_answer":"d",
  "explanation":"d/32+d/18=20/3 → d×50/576=20/3 → d=76.8. 2d=153.6. Time=153.6/32=4.8 hrs=4h48m",
  "explanation_hi":"d=76.8, 2d/32=4.8 hrs=4h48m",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"A boat covers 375 metres upstream in 30 min and returns to starting point in 18 min. Find the ratio of speed of boat in still water to speed of stream.",
  "question_text_hi":"एक नाव धारा के विपरीत दिशा में 375 मीटर की एक दूरी को 30 मिनट में तय करती है और 18 मिनट में वापस प्रारंभिक बिंदु पर आ जाती है। शांत जल में नाव की चाल और धारा की चाल का अनुपात ज्ञात करें।",
  "option_a":"5:6","option_a_hi":"5:6",
  "option_b":"7:13","option_b_hi":"7:13",
  "option_c":"13:7","option_c_hi":"13:7",
  "option_d":"4:1","option_d_hi":"4:1",
  "correct_answer":"d",
  "explanation":"Upstream=12.5 m/min, Downstream=20.83 m/min. Still=16.67, Stream=4.17. Ratio≈4:1",
  "explanation_hi":"शांत:धारा ≈ 4:1",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"A boat running upstream takes 8 hours 48 mins to cover a certain distance, while it takes 4 hours downstream. The speed of current is how much percentage less than speed of boat in still water?",
  "question_text_hi":"धारा के प्रतिकूल चलने वाली एक नाव को एक निश्चित दूरी तय करने में 8 घंटे 48 मिनट लगते हैं, जबकि समान दूरी को धारा के अनुकूल तय करने में 4 घंटे लगते हैं। धारा की गति स्थिर पानी में नाव की गति से कितना प्रतिशत कम है?",
  "option_a":"62.5%","option_a_hi":"62.5%",
  "option_b":"60%","option_b_hi":"60%",
  "option_c":"66.66%","option_c_hi":"66.66%",
  "option_d":"58.33%","option_d_hi":"58.33%",
  "correct_answer":"a",
  "explanation":"Speed ratio v_u:v_d = 4:(44/5) = 5:11. Still=8 units, Stream=3 units. % = (8−3)/8 × 100 = 62.5%",
  "explanation_hi":"धारा/शांत × 100 = 3/8 × 100 = 37.5%. % कम = 62.5%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"A boat takes one-fourth time in moving downstream than upstream. The speed of boat in still water is how much percentage more than speed of current?",
  "question_text_hi":"एक नाव को कुछ दूरी धारा के प्रतिकूल जाने की तुलना में अनुकूल जाने में एक चौथाई समय लगता है। स्थिर पानी में नाव की चाल धारा की चाल से कितना प्रतिशत ज्यादा है?",
  "option_a":"40%","option_a_hi":"40%",
  "option_b":"66.66%","option_b_hi":"66.66%",
  "option_c":"60%","option_c_hi":"60%",
  "option_d":"75%","option_d_hi":"75%",
  "correct_answer":"b",
  "explanation":"v_u=v_d/4 → v−c=(v+c)/4 → 3v=5c → v/c=5/3. % more=(5−3)/3×100=66.66%",
  "explanation_hi":"v/c=5/3. % अधिक=66.66%",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"The speed of a boat in still water is 5⅓ km/h. It is found that the boat takes thrice as much time to row up than to row down the same distance. Find the speed of the river stream.",
  "question_text_hi":"शांत जल में एक नाव की चाल 5⅓ km/h है। यह पाया गया है कि नाव को धारा की विपरीत दिशा में एक निश्चित दूरी तय करने में लगने वाला समय, धारा की दिशा में वही दूरी तय करने में लगने वाले समय का तीन गुना है। नदी की धारा की चाल ज्ञात कीजिए।",
  "option_a":"23/27 m/sec","option_a_hi":"23/27 m/sec",
  "option_b":"22/27 m/sec","option_b_hi":"22/27 m/sec",
  "option_c":"20/27 m/sec","option_c_hi":"20/27 m/sec",
  "option_d":"19/27 m/sec","option_d_hi":"19/27 m/sec",
  "correct_answer":"c",
  "explanation":"v=16/3. v−c=(v+c)/3 → 2v=4c → c=v/2=8/3 km/h. In m/s: 8/3×1000/3600=20/27",
  "explanation_hi":"c=8/3 km/h = 20/27 m/s",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"A boat starting from P goes downstream to Q in 3 hours and returns from Q to P in 4 hours. If speed of water is 3 km/h, find the speed of boat in still water.",
  "question_text_hi":"एक नाव बिंदु P से धारा की दिशा में चलना शुरू करती है और बिंदु Q तक 3 घंटे में पहुंचती है और बिंदु Q से बिंदु P पर 4 घंटे में वापस आती है। यदि जल की चाल 3 km/h है, तो शांत जल में नाव की चाल (km/h में) ज्ञात कीजिए।",
  "option_a":"12","option_a_hi":"12",
  "option_b":"20","option_b_hi":"20",
  "option_c":"21","option_c_hi":"21",
  "option_d":"32","option_d_hi":"32",
  "correct_answer":"c",
  "explanation":"3(v+3) = 4(v−3) → 3v+9 = 4v−12 → v = 21 km/h",
  "explanation_hi":"3(v+3)=4(v-3) → v=21 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A boat takes 60% more time to cover a certain distance upstream than downstream. If speed of current is 9 km/hr, in how much time will it cover 504 km downstream?",
  "question_text_hi":"किसी नाव के द्वारा एक निश्चित दूरी धारा के प्रतिकूल तय करने में लगा समय, धारा के अनुकूल लगने वाले समय से 60% अधिक है! यदि धारा की चाल 9 किमी./घंटे है! तो यह धारा के अनुकूल 504 किमी. की दूरी कितने समय में तय करेगी?",
  "option_a":"10 hr","option_a_hi":"10 घंटे",
  "option_b":"10.5 hr","option_b_hi":"10.5 घंटे",
  "option_c":"12 hr","option_c_hi":"12 घंटे",
  "option_d":"12.5 hr","option_d_hi":"12.5 घंटे",
  "correct_answer":"b",
  "explanation":"v_d=1.6v_u. v_d−v_u=18 → 0.6v_u=18 → v_u=30, v_d=48. Time=504/48=10.5 hr",
  "explanation_hi":"v_d=48 km/h. 504/48=10.5 घंटे",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"The time taken by a boat downstream is two-thirds of time upstream. If 2 times still water speed is 10 km/h more than 7 times stream speed, find the stream speed.",
  "question_text_hi":"एक नाव द्वारा धारा के अनुकूल एक निश्चित दूरी तक जाने में लिया गया समय, नाव द्वारा समान दूरी को धारा के प्रतिकूल जाने में लिए गए समय का दो-तिहाई है। यदि शांत जल में नाव की गति का 2 गुना धारा की गति के 7 गुना से 10 किमी/घंटा अधिक है, तो धारा की गति (किमी/घंटा में) क्या है?",
  "option_a":"3⅓ km/h","option_a_hi":"3⅓ km/h",
  "option_b":"2½ km/h","option_b_hi":"2½ km/h",
  "option_c":"4 km/h","option_c_hi":"4 km/h",
  "option_d":"2 km/h","option_d_hi":"2 km/h",
  "correct_answer":"a",
  "explanation":"v+c=3(v−c)/2 → 2v+2c=3v−3c → v=5c. 2v−7c=10 → 10c−7c=10 → c=10/3=3⅓",
  "explanation_hi":"c=10/3=3⅓ km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A boat can cover 56 km downstream in 3.5 hours. Ratio of boat in still water to stream speed is 3:1. How much time (in hours) will the boat take to cover 41.6 km upstream?",
  "question_text_hi":"एक नाव धारा की दिशा में 56 किमी की दूरी 3.5 घंटे में तय कर सकती है। स्थिर जल में नाव की चाल और धारा की चाल का अनुपात 3:1 है। नाव धारा की विपरीत दिशा में 41.6 किमी की दूरी तय करने में कितना समय (घंटों में) लेगी?",
  "option_a":"9.1","option_a_hi":"9.1",
  "option_b":"10.5","option_b_hi":"10.5",
  "option_c":"10.4","option_c_hi":"10.4",
  "option_d":"5.2","option_d_hi":"5.2",
  "correct_answer":"d",
  "explanation":"Downstream=56/3.5=16=v+c. v=3c → 4c=16 → c=4, v=12. Upstream=8. Time=41.6/8=5.2",
  "explanation_hi":"c=4, v=12, अनुप्रवाह=8. 41.6/8=5.2",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A man rows at 10 km/h in still water. If the river is flowing at 4.5 km/h, it takes 2 hours to go to a point and come back. At what distance (in km) is the place? (rounded to two decimal places)",
  "question_text_hi":"एक आदमी शांत जल में 10 km/h की चाल से नाव चला सकता है। यदि नदी 4.5 km/h की चाल से बह रही है, तो उसे एक स्थान तक जाने और आरंभिक बिंदु तक वापस आने में 2 घंटे का समय लगता है। वह स्थान कितनी दूरी (km में) पर स्थित है?",
  "option_a":"6.25","option_a_hi":"6.25",
  "option_b":"5.50","option_b_hi":"5.50",
  "option_c":"7.98","option_c_hi":"7.98",
  "option_d":"8.98","option_d_hi":"8.98",
  "correct_answer":"c",
  "explanation":"d/(10+4.5) + d/(10−4.5) = 2 → d/14.5 + d/5.5 = 2 → 20d/79.75 = 2 → d ≈ 7.98 km",
  "explanation_hi":"d ≈ 7.98 km",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A boat's speed in still water is 22 km/h and the river flows at 8 km/h. The time taken to cover upstream is 4 hours more than downstream. Find the distance.",
  "question_text_hi":"शांत जल में एक नाव की चाल 22 km/h है जबकि धारा की चाल 8 km/h है। यदि नाव द्वारा धारा की विपरीत दिशा एक निश्चित दूरी को तय करने में लिया गया समय, धारा की दिशा में उतनी ही दूरी तय करने में लगने वाले समय से 4 घंटे अधिक है, तो वह दूरी ज्ञात कीजिए।",
  "option_a":"105 km","option_a_hi":"105 km",
  "option_b":"110 km","option_b_hi":"110 km",
  "option_c":"115 km","option_c_hi":"115 km",
  "option_d":"125 km","option_d_hi":"125 km",
  "correct_answer":"a",
  "explanation":"d/14 − d/30 = 4 → d×16/420 = 4 → d = 105 km",
  "explanation_hi":"d×16/420=4 → d=105 km",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"The speed of a boat in still water is 15 km/h. If it can travel 42 km downstream and 28 km upstream in the same time, what is the speed of the stream?",
  "question_text_hi":"शांत जल में एक नाव की गति 15 किमी/घंटा है। यदि वह समान समय में 42 किमी धारा के अनुकूल और 28 किमी धारा के प्रतिकूल यात्रा कर सकती है, तो धारा की गति क्या है?",
  "option_a":"2.5 km/h","option_a_hi":"2.5 km/h",
  "option_b":"3 km/h","option_b_hi":"3 km/h",
  "option_c":"4.5 km/h","option_c_hi":"4.5 km/h",
  "option_d":"6 km/h","option_d_hi":"6 km/h",
  "correct_answer":"b",
  "explanation":"42/(15+c) = 28/(15−c) → 42(15−c)=28(15+c) → 70c=210 → c=3 km/h",
  "explanation_hi":"70c=210 → c=3 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"The time taken by a boat to travel 13 km downstream is the same as 7 km upstream. Stream speed 3 km/h. How much time to travel 44.8 km in still water?",
  "question_text_hi":"एक नाव द्वारा 13 किमी की बहाव की दिशा की ओर लिया गया समय, उसके द्वारा बहाव के विपरीत 7 किमी की यात्रा के लिए गए समय के बराबर है। यदि धारा की गति 3 किमी/घंटा है। स्थिर पानी में 44.8 किमी की दूरी तय करने में कितना समय लगेगा?",
  "option_a":"4 12/25 hours","option_a_hi":"4 12/25 घंटे",
  "option_b":"5 3/5 hours","option_b_hi":"5 3/5 घंटे",
  "option_c":"5 2/5 hours","option_c_hi":"5 2/5 घंटे",
  "option_d":"4 13/25 hours","option_d_hi":"4 13/25 घंटे",
  "correct_answer":"a",
  "explanation":"13/(v+3)=7/(v−3) → 13v−39=7v+21 → 6v=60 → v=10. Time=44.8/10=4.48=4 12/25",
  "explanation_hi":"v=10. 44.8/10=4 12/25",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"A man rows to a place at 72 km and back in 36 hours. He can row 12 km with the stream in the same time as 4 km against. The speed (km/h) of the stream is:",
  "question_text_hi":"एक आदमी 72 किमी की दूरी तक नाव चलाकर 36 घंटे में वापस आता है। उसने पाया कि वह धारा के साथ 12 किमी की दूरी तय करने में उतना ही समय लगा सकता है जितना धारा के विपरीत 4 किमी की दूरी तय कर सकता है। धारा की गति (किमी/घंटा में) क्या है?",
  "option_a":"3.75","option_a_hi":"3.75",
  "option_b":"2.45","option_b_hi":"2.45",
  "option_c":"2.67","option_c_hi":"2.67",
  "option_d":"2.33","option_d_hi":"2.33",
  "correct_answer":"c",
  "explanation":"v_d=3v_u. 72/3v_u+72/v_u=36 → 24/v_u+72/v_u=36 → v_u=8/3. v_d=8. Stream=(8−8/3)/2=8/3≈2.67",
  "explanation_hi":"धारा = 8/3 ≈ 2.67 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A man rows 48 km and back in 48 hours. He can row 4 km with the stream in the same time as 3 km against. The speed of the stream (km/h) is:",
  "question_text_hi":"एक आदमी 48 km नाव चलाता है और 48 घंटे में वापस आता है। वह धारा के अनुकूल 4 km की दूरी उतने की समय में तय कर सकता है जितने समय में धारा के विपरीत 3 km की दूरी तय करता है। धारा की चाल (km/h में) ज्ञात करें।",
  "option_a":"5/21","option_a_hi":"5/21",
  "option_b":"7/21","option_b_hi":"7/21",
  "option_c":"7/24","option_c_hi":"7/24",
  "option_d":"3/29","option_d_hi":"3/29",
  "correct_answer":"c",
  "explanation":"v_d=4k, v_u=3k. 48/4k+48/3k=48 → 28/k=48 → k=7/12. Stream=k/2=7/24",
  "explanation_hi":"k=7/12, धारा=7/24 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"The speed of a boat downstream is 150% more than upstream. Time for 80 km downstream and 50 km upstream is 8.2 hours. What is the downstream speed (km/h)?",
  "question_text_hi":"धारा की दिशा में, किसी नाव की चाल धारा की विपरीत दिशा की इसकी चाल से 150% अधिक है। यदि धारा की दिशा में 80 km और धारा की विपरीत दिशा में 50 km की दूरी तय करने में लगा समय 8.2 घंटे है, तो धारा की दिशा में नाव की चाल (किमी. में) ज्ञात करें।",
  "option_a":"16","option_a_hi":"16",
  "option_b":"30","option_b_hi":"30",
  "option_c":"24","option_c_hi":"24",
  "option_d":"25","option_d_hi":"25",
  "correct_answer":"d",
  "explanation":"v_d=2.5v_u. 80/2.5v_u+50/v_u=8.2 → 82/v_u=8.2 → v_u=10. v_d=25",
  "explanation_hi":"v_u=10, v_d=25 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A boat takes total 10 hr to cover 102 km downstream and 63 km upstream. Time for 34 km downstream equals time for 24 km still water. Speed of boat upstream vs speed of current, how much greater?",
  "question_text_hi":"एक नाव धारा के अनुकूल 102 किमी. और धारा के प्रतिकूल 63 किमी. की दूरी तय करने में कुल 10 घंटे का समय लेती है। धारा के अनुकूल 34 किमी. की दूरी तय करने में लगा समय स्थिर जल में 24 किमी. की दूरी तय करने में लगे समय के बराबर है। धारा के प्रतिकूल नाव की चाल, धारा की चाल से कितना अधिक है?",
  "option_a":"4 km/hr","option_a_hi":"4 km/hr",
  "option_b":"3 km/hr","option_b_hi":"3 km/hr",
  "option_c":"4.5 km/hr","option_c_hi":"4.5 km/hr",
  "option_d":"5 km/hr","option_d_hi":"5 km/hr",
  "correct_answer":"b",
  "explanation":"34/(v+c)=24/v → 34v=24v+24c → 10v=24c → v=12c/5. Solving: c=7.5, v=18. Upstream speed−current=v−c−c=v−2c=3",
  "explanation_hi":"c=7.5, v=18. v−2c=3 km/hr",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"The speed of a boat downstream is 2.5 times the speed upstream. If the time for 30 km downstream and same distance upstream is 7 hours, what is the downstream speed (km/h)?",
  "question_text_hi":"धारा की दिशा में किसी नाव की चाल, धारा की विपरीत दिशा में जाने की चाल से 2.5 गुना है। यदि नाव द्वारा धारा की दिशा में 30 km और धारा की विपरीत दिशा में समान दूरी तय करने में 7 घंटे लगते हैं, तो धारा की दिशा में नाव की चाल (km/h) ज्ञात करें।",
  "option_a":"12.5","option_a_hi":"12.5",
  "option_b":"9","option_b_hi":"9",
  "option_c":"15","option_c_hi":"15",
  "option_d":"7.5","option_d_hi":"7.5",
  "correct_answer":"c",
  "explanation":"v_d=2.5v_u. 30/2.5v_u+30/v_u=7 → 42/v_u=7 → v_u=6. v_d=15",
  "explanation_hi":"v_u=6, v_d=15 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"A boat goes 112 km downstream and comes back to the starting point in 11.5 hours. If the speed of the current is 9 km/hr, find the speed of the boat in still water.",
  "question_text_hi":"एक नाव धारा की दिशा में 112 कि.मी. दूरी तय करती है तथा आरंभिक बिंदु पर 11.5 घंटे में वापस आ जाती है। यदि धारा की चाल 9 कि.मी./घंटा है, तो शांत जल में नाव की चाल ज्ञात करें?",
  "option_a":"17 km/h","option_a_hi":"17 km/h",
  "option_b":"19 km/h","option_b_hi":"19 km/h",
  "option_c":"29 km/h","option_c_hi":"29 km/h",
  "option_d":"23 km/h","option_d_hi":"23 km/h",
  "correct_answer":"d",
  "explanation":"112/(v+9)+112/(v−9)=11.5. Try v=23: 112/32+112/14=3.5+8=11.5 ✓",
  "explanation_hi":"v=23: 112/32+112/14=11.5 ✓",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"The speed of a stream is 6 km/h. A boat can go 56 km downstream and 39 km upstream in 7 hours. What is the speed (km/h) of the boat in still water?",
  "question_text_hi":"एक धारा की चाल 6 km/h है। एक नाव धारा के अनुकूल 56 km और धारा के प्रतिकूल 39 km की दूरी 7 घंटे में तय कर सकती है। स्थिर जल में नाव की चाल (km/h में) ज्ञात कीजिए।",
  "option_a":"22","option_a_hi":"22",
  "option_b":"15","option_b_hi":"15",
  "option_c":"7","option_c_hi":"7",
  "option_d":"13","option_d_hi":"13",
  "correct_answer":"b",
  "explanation":"v=15: downstream=21, upstream=9. 56/21+39/9=2.67+4.33=7 ✓",
  "explanation_hi":"v=15: 56/21+39/9=7 ✓",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"In a stream running at 3 km/h, a motorboat goes 12 km upstream and back to starting point in 60 min. Find the speed of the motorboat in still water.",
  "question_text_hi":"3 किमी/घंटा की गति से बहती धारा में। एक मोटरबोट धारा के प्रतिकूल 12 किमी जाती है और 60 मिनट में प्रारंभिक बिंदु पर वापस आती है। शांत जल में मोटरबोट की गति ज्ञात कीजिये?",
  "option_a":"2(2+√17)","option_a_hi":"2(2+√17)",
  "option_b":"2(4+√15)","option_b_hi":"2(4+√15)",
  "option_c":"3(4+√17)","option_c_hi":"3(4+√17)",
  "option_d":"3(2+√17)","option_d_hi":"3(2+√17)",
  "correct_answer":"c",
  "explanation":"12/(v−3)+12/(v+3)=1 → 24v=v²−9 → v²−24v−9=0 → v=(24+6√17)/2=12+3√17=3(4+√17)",
  "explanation_hi":"v=12+3√17=3(4+√17)",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"The speed of a motorboat in still water is 20 km/h. It travels 150 km downstream and returns. If the round trip takes 16 hours, what is the speed (km/h) of the river flow?",
  "question_text_hi":"स्थिर जल में, किसी मोटरबोट की चाल 20 km/h है। यह धारा की दिशा में 150 km की दूरी तय करती है और फिर शुरुआती बिन्दु पर वापस आती है। यदि राउंड ट्रिप में 16 घंटे का समय लगता है, तो नदी के प्रवाह की चाल (km/h में) ज्ञात करें।",
  "option_a":"6","option_a_hi":"6",
  "option_b":"4","option_b_hi":"4",
  "option_c":"8","option_c_hi":"8",
  "option_d":"5","option_d_hi":"5",
  "correct_answer":"d",
  "explanation":"150/(20+c)+150/(20−c)=16 → 6000/(400−c²)=16 → c²=25 → c=5",
  "explanation_hi":"c²=25 → c=5 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"A motorboat's speed is 16 km/h in still water. It takes 72 minutes more to go 36 km upstream than downstream. The speed (km/h) of the stream is:",
  "question_text_hi":"शांत जल में एक मोटरबोट की गति 16 किमी/घंटा है। धारा के प्रतिकूल 36 किमी जाने में धारा के अनुकूल समान स्थान पर लौटने की तुलना में 72 मिनट अधिक लगते हैं। धारा की गति (किमी/घंटा में) है:",
  "option_a":"8","option_a_hi":"8",
  "option_b":"10","option_b_hi":"10",
  "option_c":"4","option_c_hi":"4",
  "option_d":"5","option_d_hi":"5",
  "correct_answer":"c",
  "explanation":"36/(16−c)−36/(16+c)=1.2 → 72c/(256−c²)=1.2 → c²+60c−256=0 → c=4",
  "explanation_hi":"c²+60c−256=0 → c=4 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A motorboat covers 28 km upstream and 40 km downstream in 11 hours. At the same speed it can travel 30 km downstream and 16 km upstream in 7 hours. The speed of the stream is:",
  "question_text_hi":"एक मोटरबोट कुछ गति से यात्रा करते हुए 11 घंटे में धारा के प्रतिकूल 28 किमी और धारा के अनुकूल 40 किमी की दूरी तय कर सकती है। समान गति से यह 7 घंटे में धारा के अनुकूल 30 किमी और धारा के प्रतिकूल 16 किमी की यात्रा कर सकती है, तो धारा की गति क्या है?",
  "option_a":"2 km/h","option_a_hi":"2 km/h",
  "option_b":"4 km/h","option_b_hi":"4 km/h",
  "option_c":"3 km/h","option_c_hi":"3 km/h",
  "option_d":"1 km/h","option_d_hi":"1 km/h",
  "correct_answer":"c",
  "explanation":"Let a=1/u, b=1/d. 28a+40b=11, 16a+30b=7. Solve: b=1/10 (d=10), a=1/4 (u=4). Stream=(10−4)/2=3",
  "explanation_hi":"d=10, u=4. धारा=(10−4)/2=3 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A man covers 39 km upstream and 116 km downstream in 7 hrs. He also covers 65 km upstream and 87 km downstream in 8 hrs. Find the speed of boat in still water.",
  "question_text_hi":"एक व्यक्ति को 39 किमी की दूरी धारा के विपरीत दिशा में और 116 किमी धारा की दिशा में तय करने में कुल समय 7 घंटे लगता है। और उसे 65 किमी की दूरी धारा के विपरीत दिशा में और 87 किमी धारा की दिशा में तय करने में कुल समय 8 घंटे लगता है। स्थिर पानी में नाव की गति का पता लगाएं।",
  "option_a":"21 km/hr","option_a_hi":"21 km/hr",
  "option_b":"27 km/hr","option_b_hi":"27 km/hr",
  "option_c":"18 km/hr","option_c_hi":"18 km/hr",
  "option_d":"29 km/hr","option_d_hi":"29 km/hr",
  "correct_answer":"a",
  "explanation":"39a+116b=7, 65a+87b=8. Solving: b=1/29 (d=29), a=1/13 (u=13). Still=(13+29)/2=21",
  "explanation_hi":"u=13, d=29. शांत=(13+29)/2=21 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A boat can go 40 km downstream and 25 km upstream in 7.5 hours. It can also go 48 km downstream and 36 km upstream in 10 hours. What is the speed (km/h) of the boat in still water?",
  "question_text_hi":"एक नाव 7 घंटे 30 मिनट में 40 किमी. धारा की दिशा में और 25 किमी. धारा की विपरीत दिशा में जा सकती है। यह 10 घंटे में 48 किमी. धारा की दिशा में और 36 किमी. धारा की विपरीत दिशा में जा सकती है। शांत जल में नाव की चाल (किमी/घं. में) कितनी होगी?",
  "option_a":"6","option_a_hi":"6",
  "option_b":"12","option_b_hi":"12",
  "option_c":"9","option_c_hi":"9",
  "option_d":"15","option_d_hi":"15",
  "correct_answer":"c",
  "explanation":"40a+25b=7.5, 48a+36b=10. Solving: b=1/6 (u=6), a=1/12 (d=12). Still=(6+12)/2=9",
  "explanation_hi":"u=6, d=12. शांत=9 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A boat can go 30 km downstream and 24 km upstream in 2h27m. Also it can go 10 km downstream and 4 km upstream in 37 min. What is the upstream speed (km/hr)?",
  "question_text_hi":"एक नाव 30 किमी धारा की दिशा में और 24 किमी धारा के विपरीत 2 घंटे 27 मिनट में जा सकती है। साथ ही, यह 37 मिनट में 10 किमी धारा की दिशा में और 4 किमी धारा के विपरीत जा सकता है। नाव के बहाव की दिशा में गति (किमी / घंटा में) क्या है?",
  "option_a":"20","option_a_hi":"20",
  "option_b":"24","option_b_hi":"24",
  "option_c":"22","option_c_hi":"22",
  "option_d":"18","option_d_hi":"18",
  "correct_answer":"a",
  "explanation":"30/d+24/u=49/20; 10/d+4/u=37/60. Subtract 3× of second from first: 12/u=12/20→u=20",
  "explanation_hi":"u=20 km/hr",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A boat can go 3 km upstream and 5 km downstream in 55 min. It can also go 4 km upstream and 9 km downstream in 1h25m. In how much time will it go 43.2 km downstream?",
  "question_text_hi":"एक नाव 55 मिनट में धारा–प्रवाह के विपरीत दिशा में 3 km और धारा–प्रवाह की दिशा में 5 km की दूरी तय कर सकती है। यह 1 घंटा और 25 मिनट में 4 km upstream और 9 km downstream भी तय कर सकती है। धारा–प्रवाह की दिशा में यह 43.2 km की दूरी तय करने में कितना समय (घंटों में) लेगी?",
  "option_a":"4.8","option_a_hi":"4.8",
  "option_b":"5.4","option_b_hi":"5.4",
  "option_c":"3.6","option_c_hi":"3.6",
  "option_d":"4.4","option_d_hi":"4.4",
  "correct_answer":"c",
  "explanation":"3a+5b=11/12, 4a+9b=17/12. Solving: b=1/12 (d=12). Time=43.2/12=3.6 hrs",
  "explanation_hi":"d=12, समय=43.2/12=3.6 घंटे",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A motorboat can go 8.4 km downstream and 4.8 km upstream in 1 hour. It can go 17.5 km downstream and 9 km upstream in 2 hours. How much time (hours) to go 31.2 km in still water?",
  "question_text_hi":"एक मोटरबोट 1 घंटे में धारा के अनुकूल 8.4 किमी और धारा के प्रतिकूल 4.8 किमी जा सकती है। यह 2 घंटे में 17.5 किमी डाउनस्ट्रीम और 9 किमी अपस्ट्रीम जा सकती है। शांत जल में 31.2 किमी की दूरी तय करने में कितना समय (घंटों में) लगेगा?",
  "option_a":"2.4","option_a_hi":"2.4",
  "option_b":"1.3","option_b_hi":"1.3",
  "option_c":"3.9","option_c_hi":"3.9",
  "option_d":"1.2","option_d_hi":"1.2",
  "correct_answer":"a",
  "explanation":"8.4/d+4.8/u=1; 17.5/d+9/u=2. Solving: d=14, u=12. Still=13. Time=31.2/13=2.4",
  "explanation_hi":"d=14, u=12, शांत=13. 31.2/13=2.4",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A boat covers 24 km upstream and 36 km downstream in 10 hours, and 36 km upstream and 24 km downstream in 12 hours. The speed of the current is:",
  "question_text_hi":"एक नाव धारा के प्रतिकूल 24 km की दूरी और धारा के अनुकूल 36 km की दूरी 10 घंटे में तय करती है और धारा के प्रतिकूल 36 km की दूरी और धारा के अनुकूल 24 km की दूरी 12 घंटे में तय करती है। धारा की चाल ज्ञात करें।",
  "option_a":"26/9 km/h","option_a_hi":"26/9 km/h",
  "option_b":"33/13 km/h","option_b_hi":"33/13 km/h",
  "option_c":"25/8 km/h","option_c_hi":"25/8 km/h",
  "option_d":"24/7 km/h","option_d_hi":"24/7 km/h",
  "correct_answer":"c",
  "explanation":"24a+36b=10, 36a+24b=12. Solving: b=1/10 (d=10), a=4/15 (u=3.75). Stream=(10−3.75)/2=3.125=25/8",
  "explanation_hi":"u=3.75, d=10. धारा=(10−3.75)/2=25/8",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A boat can go 3.6 km upstream and 5.4 km downstream in 54 minutes. While it can go 5.4 km upstream and 3.6 km downstream in 58.5 minutes. The time (in minutes) taken by the boat in going 10 km downstream is:",
  "question_text_hi":"एक नाव 3.6 किमी धारा प्रवाह की प्रतिकूल दिशा में और 5.4 किमी धारा प्रवाह की दिशा में 54 मिनट में जा सकती है। जबकि यह 5.4 किमी upstream और 3.6 किमी downstream 58.5 मिनट में जा सकती है। नाव से 10 किमी downstream में लगने वाला समय है:",
  "option_a":"48","option_a_hi":"48",
  "option_b":"50","option_b_hi":"50",
  "option_c":"45","option_c_hi":"45",
  "option_d":"54","option_d_hi":"54",
  "correct_answer":"b",
  "explanation":"3.6a+5.4b=0.9; 5.4a+3.6b=0.975. Solving: b=1/12 (d=12). Time=10/12 hr=50 min",
  "explanation_hi":"d=12. 10/12 hr=50 मिनट",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"On a river, Q is the midpoint between P and R. A boat can go from P to Q and back in 12 hours, and from P to R in 16 hours 40 min. How long would it take to go from R to P?",
  "question_text_hi":"किसी नदी में नदी के एक ही किनारे पर दो बिन्दुओं P और R के बीच मध्य बिंदु Q है। कोई नाव P से Q तक जाकर वापस कुल 12 घंटे में आ सकती है और P से R तक 16 घंटे 40 मिनट में आ सकती है। बताइए उसे R से P तक जाने में कितना समय लगेगा?",
  "option_a":"3 3/7 h","option_a_hi":"3 3/7 घंटे",
  "option_b":"5 h","option_b_hi":"5 घंटे",
  "option_c":"6 2/3 h","option_c_hi":"6 2/3 घंटे",
  "option_d":"7 1/3 h","option_d_hi":"7 1/3 घंटे",
  "correct_answer":"d",
  "explanation":"PQ/d=25/3 (from P to R=50/3). PQ/u=12−25/3=11/3. R to P: 2PQ/u=22/3=7⅓ hours",
  "explanation_hi":"PQ/u=11/3, R से P=22/3=7⅓ घंटे",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"X and Y are two points in a river. Points P and Q divide XY into three equal parts. The river flows along XY. Time from X to Q and Y to Q are in ratio 4:5. The ratio of the speed of the boat downstream to river current is:",
  "question_text_hi":"X और Y, किसी नदी पर दो बिंदु हैं। बिंदु P और Q सीधी रेखा XY को तीन बराबर भागों में विभाजित करते हैं। नदी, XY के समानांतर बहती है और किसी नाव द्वारा X से Q तक और Q की यात्रा में लगने वाले समय का अनुपात 4:5 है। धारा की दिशा में नाव की चाल और नदी की धारा की चाल का अनुपात ज्ञात करें।",
  "option_a":"3:10","option_a_hi":"3:10",
  "option_b":"3:4","option_b_hi":"3:4",
  "option_c":"10:3","option_c_hi":"10:3",
  "option_d":"4:3","option_d_hi":"4:3",
  "correct_answer":"c",
  "explanation":"2d/(v+c) : d/(v−c) = 4:5 → 2(v−c)/(v+c)=4/5 → 10v−10c=4v+4c → 6v=14c → v=7c/3. (v+c)/c=10c/3c=10/3. Ratio=10:3",
  "explanation_hi":"v=7c/3. (v+c)/c=10/3. अनुपात=10:3",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A boat takes 20 hours for travelling downstream from A to B and comes back to midpoint C between A and B. Stream speed 5 km/h, still water speed 10 km/h. Find distance AB (km).",
  "question_text_hi":"एक नाव को बिंदु A से बिंदु B तक धारा के अनुकूल यात्रा करने में 20 घंटे लगते हैं और A और B के बीच मध्य बिंदु C पर वापस आती है। धारा की गति 5 किमी/घंटा है और शांत पानी में नाव की गति 10 किमी/घंटा है। A और B के बीच की दूरी (किमी में) ज्ञात करें?",
  "option_a":"100","option_a_hi":"100",
  "option_b":"120","option_b_hi":"120",
  "option_c":"150","option_c_hi":"150",
  "option_d":"75","option_d_hi":"75",
  "correct_answer":"b",
  "explanation":"d/15 + (d/2)/5 = 20 → d/15 + d/10 = 20 → d(2+3)/30 = 20 → d=120",
  "explanation_hi":"d/15+d/10=20 → d=120 km",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A man travels by motor boat down a river to his office and back. If he doubles the speed of his motor boat (river speed unchanged), travel time reduces by 75%. The ratio of original motor boat speed to river speed is:",
  "question_text_hi":"एक आदमी एक मोटर बोट से एक नदी की धारा के अनुकूल अपने कार्यालय जाता है और वापस लौटता है। यदि नदी की गति अपरिवर्तित रहे, और वह अपने मोटर बोट की गति को दोगुना कर देता है, तो उसके यात्रा का समय 75% कम हो जाता है। मोटर बोट की मूल गति और नदी की गति का अनुपात है?",
  "option_a":"√6:√2","option_a_hi":"√6:√2",
  "option_b":"√7:2","option_b_hi":"√7:2",
  "option_c":"2√5:3","option_c_hi":"2√5:3",
  "option_d":"3:2","option_d_hi":"3:2",
  "correct_answer":"b",
  "explanation":"T₁=0.25T → 4vd/(4v²−c²)=0.25×2vd/(v²−c²) → 4(v²−c²)=4v²−c² ... 4v²=7c² → v/c=√7/2",
  "explanation_hi":"4v²=7c² → v:c=√7:2",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A boat covers a round trip between A and B in T hours. If speed doubles, it takes 80T/161 hours. Find ratio of still water speed to stream speed.",
  "question_text_hi":"कोई नाव, किसी नदी में दो बिन्दुओं A और B के बीच राउंड-ट्रिप यात्रा वाली दूरी को T घंटे में तय करती है। यदि स्थिर जल में इसकी चाल 2 गुनी हो जाती है, तो इसे उसी दूरी को तय करने में 80T/161 घंटे लगेंगे। स्थिर जल में इसकी चाल का, नदी की चाल से अनुपात ज्ञात करें।",
  "option_a":"11:1","option_a_hi":"11:1",
  "option_b":"161:40","option_b_hi":"161:40",
  "option_c":"1:11","option_c_hi":"1:11",
  "option_d":"2:1","option_d_hi":"2:1",
  "correct_answer":"a",
  "explanation":"T₁/T=80/161. 4(v²−c²)/(4v²−c²)=80/161 → 644v²−644c²=640v²−160c² → 4v²=484c² → v/c=11. Ratio 11:1",
  "explanation_hi":"v²/c²=121 → v:c=11:1",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A man swims from A to B and back in 4½ hours. A block of wood goes from A to B with stream in 6 hours. Ratio of man's still water speed to stream speed is:",
  "question_text_hi":"एक आदमी A से B तक तैरता है और 4½ घंटे में वापस आ जाता है। लकड़ी का एक कुंदा जब A से B तक धारा के साथ जाता है तो 6 घंटे लगते हैं। धारा की गति का आदमी की गति से अनुपात क्या है?",
  "option_a":"2:1","option_a_hi":"2:1",
  "option_b":"4:3","option_b_hi":"4:3",
  "option_c":"3:1","option_c_hi":"3:1",
  "option_d":"4:1","option_d_hi":"4:1",
  "correct_answer":"c",
  "explanation":"Set d=6. c=1 (wood goes d in 6 hrs so c=d/6=1). 2v×6/(v²−1)=4.5 → 3v²−8v−3=0 → v=3. v:c=3:1",
  "explanation_hi":"v=3, c=1. v:c=3:1",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"A swimmer swims from P against the current for 6 min and then swims back along the current for 6 min, reaching Q. If PQ = 120 m, the speed of the current (km/h) is:",
  "question_text_hi":"एक तैराक एक बिंदु P से धारा के विपरीत 6 मिनट तक तैरता है और फिर अगले 6 मिनट के लिए धारा के साथ तैरता है और एक बिंदु Q पर पहुंचता है। यदि P और Q के बीच की दूरी 120 m है, तो धारा की चाल (km/h में) ........... है।",
  "option_a":"0.4","option_a_hi":"0.4",
  "option_b":"0.2","option_b_hi":"0.2",
  "option_c":"1","option_c_hi":"1",
  "option_d":"0.6","option_d_hi":"0.6",
  "correct_answer":"d",
  "explanation":"Net displacement = (v+c)×6 − (v−c)×6 = 12c = 120 m. c = 10 m/min = 0.6 km/h",
  "explanation_hi":"12c=120 → c=10 m/min = 0.6 km/h",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"hard","phase":"main",
  "question_text":"A ship is 77 km from shore. A leak admits 2¼ ton water every 5½ min. Outlet throws 12 tons/hr. Rescue ship moves at 6 km/h. Find the speed of the sinking ship so that rescue can save passengers (69 ton to sink).",
  "question_text_hi":"एक समुद्री जहाज किनारे से 77 किमी. दूर है। उसमें एक छेद हो जाता है जिसमें से प्रत्येक 5½ मिनट में 2¼ टन पानी निकलता है। एक निकासी नल भी है जो प्रति घण्टे 12 टन पानी बाहर फेंकता है। ज्ञात करों कि इसे किस चाल से चलना चाहिए कि जब यह डूबने वाली हो तो इसे 6 किमी /घण्टे की रफ्तार से आने वाला बचाव जहाज आकर बचा ले और जहा डुबने के लिए 69 टन पानी पर्याप्त है?",
  "option_a":"6 km/hr","option_a_hi":"6 km/hr",
  "option_b":"8 km/hr","option_b_hi":"8 km/hr",
  "option_c":"10 km/hr","option_c_hi":"10 km/hr",
  "option_d":"12 km/hr","option_d_hi":"12 km/hr",
  "correct_answer":"b",
  "explanation":"Net intake = 2.25/(5.5/60)−12 ≈ 12.55 tons/hr. Time to sink = 69/12.55 ≈ 5.5 hrs. Rescue covers 6×5.5=33 km. Ship must cover 77−33=44 km in 5.5 hrs → 44/5.5=8 km/hr",
  "explanation_hi":"जहाज को 5.5 घंटे में 44 km तय करना = 8 km/hr",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Boat & Stream","difficulty":"medium","phase":"main",
  "question_text":"A man rows downstream in 9 hours and upstream in 18 hours. How many hours will it take to row three-fifths of the same distance in still water?",
  "question_text_hi":"एक आदमी एक नाव को प्रवाह की दिशा में चलाते हुए एक निश्चित दूरी 9 घंटे में तय करता है, जबकि प्रवाह की विपरीत दिशा में नाव चलाते हुए सामान दूरी तय करने में उसे 18 घंटे का समय लगता है। शांत जल में समान दूरी के तीन बटे पाँच भाग तक नाव चलाने में उसे कितने घंटे लगेंगे?",
  "option_a":"9.5","option_a_hi":"9.5",
  "option_b":"7.2","option_b_hi":"7.2",
  "option_c":"10","option_c_hi":"10",
  "option_d":"12","option_d_hi":"12",
  "correct_answer":"b",
  "explanation":"v+c=d/9, v−c=d/18. v=d/12. Time for 3d/5 = (3d/5)/(d/12) = 36/5 = 7.2 hrs",
  "explanation_hi":"v=d/12. समय=3d/5÷d/12=7.2 घंटे",
},

]


def seed():
    db = SessionLocal()
    try:
        existing = {
            r[0]
            for r in db.query(Question.question_text)
                         .filter(Question.subject_code == "quant",
                                 Question.topic == "Boat & Stream")
                         .all()
        }
        new_qs = [q for q in QUESTIONS if q["question_text"] not in existing]
        for qdata in new_qs:
            db.add(Question(**qdata))
        db.commit()
        print(f"✓ Inserted {len(new_qs)} new Boat & Stream questions. "
              f"({len(QUESTIONS)-len(new_qs)} already existed, "
              f"{len(QUESTIONS)} total in seed data)")
    except Exception as e:
        db.rollback()
        print(f"✗ Error: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()
