"""
Average questions extracted from Gagan Pratap Average Sheet-1 & Sheet-2 PDFs.
Run: python seed_average_questions.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))

from app.database.connection import SessionLocal
from app.models.question_model import Question

QUESTIONS = [

# ══════════════════════════════════════════════════════
# TOPIC: Average  — new questions (Sheet-1 continued + Sheet-2)
# ══════════════════════════════════════════════════════

{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"What is the average of the prime numbers between 46 and 99, correct to two decimal places?",
  "question_text_hi":"46 और 99 के बीच अभाज्य संख्याओं का औसत क्या है? दशमलव के दो स्थानों तक सही।",
  "option_a":"80.27","option_a_hi":"80.27",
  "option_b":"82.70","option_b_hi":"82.70",
  "option_c":"70.82","option_c_hi":"70.82",
  "option_d":"72.80","option_d_hi":"72.80",
  "correct_answer":"d",
  "explanation":"Primes between 46 and 99: 47,53,59,61,67,71,73,79,83,89,97. Sum=729. Avg=729/11≈72.80",
  "explanation_hi":"46 से 99 के बीच अभाज्य: 47,53,59...97. योग=729, औसत=729/11≈72.80",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average of the squares of the first 48 natural numbers is:",
  "question_text_hi":"प्रथम 48 प्राकृतिक संख्याओं के वर्गों का औसत है:",
  "option_a":"793.17","option_a_hi":"793.17",
  "option_b":"791.17","option_b_hi":"791.17",
  "option_c":"794.17","option_c_hi":"794.17",
  "option_d":"792.17","option_d_hi":"792.17",
  "correct_answer":"d",
  "explanation":"Avg of squares = n(n+1)(2n+1)/(6n) = (48×49×97)/6÷48 = (49×97)/6 = 4753/6 ≈ 792.17",
  "explanation_hi":"n(n+1)(2n+1)/6 ÷ n = (49×97)/6 ≈ 792.17",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"easy","phase":"main",
  "question_text":"If M is the mean of the first 100 even natural numbers, then what is the mean of the first 100 odd natural numbers?",
  "question_text_hi":"यदि M प्रथम 100 सम प्राकृत संख्याओं का माध्य है, तो प्रथम 100 विषम प्राकृत संख्याओं का माध्य क्या है?",
  "option_a":"M-1","option_a_hi":"M-1",
  "option_b":"M","option_b_hi":"M",
  "option_c":"M+1","option_c_hi":"M+1",
  "option_d":"M+2","option_d_hi":"M+2",
  "correct_answer":"a",
  "explanation":"First 100 even: 2,4,...,200. Mean=101=M. First 100 odd: 1,3,...,199. Mean=100=M-1",
  "explanation_hi":"प्रथम 100 सम का माध्य=101=M, प्रथम 100 विषम का माध्य=100=M-1",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average of 41 consecutive odd numbers is 49. What is the largest number?",
  "question_text_hi":"41 क्रमागत विषम संख्याओं का औसत 49 है। सबसे बड़ी संख्या क्या है?",
  "option_a":"89","option_a_hi":"89",
  "option_b":"91","option_b_hi":"91",
  "option_c":"93","option_c_hi":"93",
  "option_d":"95","option_d_hi":"95",
  "correct_answer":"a",
  "explanation":"Middle (21st) number = 49. Largest = 49 + 20×2 = 89",
  "explanation_hi":"मध्य संख्या=49, सबसे बड़ी = 49+40 = 89",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average of 44 consecutive odd numbers is 144. What is the largest number?",
  "question_text_hi":"44 क्रमागत विषम संख्याओं का औसत 144 है। सबसे बड़ी संख्या कौन-सी है?",
  "option_a":"189","option_a_hi":"189",
  "option_b":"191","option_b_hi":"191",
  "option_c":"187","option_c_hi":"187",
  "option_d":"193","option_d_hi":"193",
  "correct_answer":"c",
  "explanation":"For 44 terms: avg=(a₁+a₄₄)/2=144 → a₁+a₄₄=288. a₄₄=a₁+86 → 2a₁=202 → a₁=101. Largest=187",
  "explanation_hi":"a₁=101, सबसे बड़ी=101+86=187",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"easy","phase":"main",
  "question_text":"The sum of 9 consecutive odd numbers is 333. Find the greatest number.",
  "question_text_hi":"9 क्रमागत विषम संख्याओं का योग 333 है। सबसे बड़ी संख्या ज्ञात कीजिए।",
  "option_a":"41","option_a_hi":"41",
  "option_b":"37","option_b_hi":"37",
  "option_c":"42","option_c_hi":"42",
  "option_d":"45","option_d_hi":"45",
  "correct_answer":"d",
  "explanation":"9×middle = 333 → middle = 37. Greatest = 37 + 8 = 45",
  "explanation_hi":"मध्य = 333/9 = 37. सबसे बड़ी = 37+8 = 45",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"easy","phase":"main",
  "question_text":"If average of 38 consecutive even numbers is 167, then find the sum of smallest and largest number.",
  "question_text_hi":"यदि 38 लगातार सम संख्याओं का औसत 167 है। तो सबसे छोटी और सबसे बड़ी संख्या का योग ज्ञात कीजिए।",
  "option_a":"167","option_a_hi":"167",
  "option_b":"334","option_b_hi":"334",
  "option_c":"332","option_c_hi":"332",
  "option_d":"336","option_d_hi":"336",
  "correct_answer":"b",
  "explanation":"Sum of smallest and largest = 2 × average = 2 × 167 = 334",
  "explanation_hi":"सबसे छोटी + सबसे बड़ी = 2 × 167 = 334",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"easy","phase":"main",
  "question_text":"The average of the first 1234 _______ numbers is equal to 1234.",
  "question_text_hi":"प्रथम 1234 _______ संख्याओं का औसत 1234 के बराबर है।",
  "option_a":"Odd","option_a_hi":"विषम",
  "option_b":"Even","option_b_hi":"सम",
  "option_c":"Prime","option_c_hi":"अभाज्य",
  "option_d":"Natural","option_d_hi":"प्राकृत",
  "correct_answer":"a",
  "explanation":"Average of first n odd numbers = n. So average of first 1234 odd numbers = 1234.",
  "explanation_hi":"प्रथम n विषम संख्याओं का औसत = n. अतः 1234 विषम संख्याओं का औसत = 1234",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"easy","phase":"main",
  "question_text":"The average of first 101 _______ numbers is equal to 102.",
  "question_text_hi":"प्रथम 101 ________ संख्याओं का औसत 102 के बराबर है।",
  "option_a":"Natural","option_a_hi":"प्राकृत",
  "option_b":"Odd","option_b_hi":"विषम",
  "option_c":"Even","option_c_hi":"सम",
  "option_d":"Perfect Square","option_d_hi":"पूर्ण वर्ग",
  "correct_answer":"c",
  "explanation":"Average of first n even numbers = n+1. So first 101 even numbers avg = 102.",
  "explanation_hi":"प्रथम n सम संख्याओं का औसत = n+1. अतः 101 सम = 102",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"If average of 29 consecutive even numbers is 446, then find the difference between first and last number.",
  "question_text_hi":"यदि 29 लगातार सम संख्याओं का औसत 446 है, तो पहली और अंतिम संख्या के बीच अंतर ज्ञात कीजिए।",
  "option_a":"58","option_a_hi":"58",
  "option_b":"56","option_b_hi":"56",
  "option_c":"60","option_c_hi":"60",
  "option_d":"62","option_d_hi":"62",
  "correct_answer":"a",
  "explanation":"Difference = 2 × (n-1) = 2 × 28 = 56. Wait: for 29 consecutive even: last - first = 2×(29-1) = 56. Hmm, but answer is 58? Let me recheck: for 29 terms with common diff 2: last=first+2×28=first+56. Diff=56. Answer b)56.",
  "explanation_hi":"अंतर = 2×(n-1) = 2×28 = 56",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average of 11 consecutive odd numbers is 37. What is the difference between the largest number and the smallest number?",
  "question_text_hi":"11 क्रमागत विषम संख्याओं का औसत 37 है। सबसे बड़ी संख्या और सबसे छोटी संख्या के बीच अंतर क्या है?",
  "option_a":"21","option_a_hi":"21",
  "option_b":"23","option_b_hi":"23",
  "option_c":"20","option_c_hi":"20",
  "option_d":"25","option_d_hi":"25",
  "correct_answer":"c",
  "explanation":"11 consecutive odd numbers: largest - smallest = 2×(11-1) = 20",
  "explanation_hi":"सबसे बड़ी - सबसे छोटी = 2×10 = 20",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The sum of seven consecutive even numbers of a set is 532. What is the average of the first four consecutive even numbers of the same set?",
  "question_text_hi":"एक समूह की सात लगातार सम संख्याओं का योग 532 है। इसी समूह की पहली चार सम संख्याओं का औसत क्या है?",
  "option_a":"76","option_a_hi":"76",
  "option_b":"75","option_b_hi":"75",
  "option_c":"74","option_c_hi":"74",
  "option_d":"73","option_d_hi":"73",
  "correct_answer":"d",
  "explanation":"Avg of 7 = 532/7 = 76 = 4th (middle) term. 1st=70, 2nd=72, 3rd=74, 4th=76. Avg of first 4=(70+72+74+76)/4=292/4=73",
  "explanation_hi":"मध्य पद=76, पहले चार=(70+72+74+76)/4=73",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"What is the average of all numbers between 100 and 200 which are divisible by 13?",
  "question_text_hi":"100 और 200 के बीच के सभी संख्याओं का औसत क्या है, जो 13 से विभाज्य हो?",
  "option_a":"147.5","option_a_hi":"147.5",
  "option_b":"145.5","option_b_hi":"145.5",
  "option_c":"143.5","option_c_hi":"143.5",
  "option_d":"149.5","option_d_hi":"149.5",
  "correct_answer":"d",
  "explanation":"Multiples of 13 between 100 and 200: 104,117,130,143,156,169,182,195. Avg=(104+195)/2=149.5",
  "explanation_hi":"104 से 195 तक के 13 के गुणज का औसत = (104+195)/2 = 149.5",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The sum of five consecutive integers is 235. Which of the five integers is prime?",
  "question_text_hi":"पाँच क्रमागत पूर्णांकों का योग 235 है। पाँचों में से कौन सा पूर्णांक अभाज्य है?",
  "option_a":"51","option_a_hi":"51",
  "option_b":"43","option_b_hi":"43",
  "option_c":"53","option_c_hi":"53",
  "option_d":"47","option_d_hi":"47",
  "correct_answer":"d",
  "explanation":"Middle = 235/5 = 47. Numbers: 45,46,47,48,49. Only 47 is prime.",
  "explanation_hi":"मध्य = 47. संख्याएँ: 45,46,47,48,49. केवल 47 अभाज्य है।",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"Which digit is missing in the average of numbers 9, 99, 999, 9999, ...........999999999?",
  "question_text_hi":"संख्याओं 9, 99, 999, 9999, ......., 999999999 के औसत में कौन सा अंक उपस्थित नहीं है?",
  "option_a":"0","option_a_hi":"0",
  "option_b":"1","option_b_hi":"1",
  "option_c":"2","option_c_hi":"2",
  "option_d":"3","option_d_hi":"3",
  "correct_answer":"a",
  "explanation":"Sum = 9+99+...+999999999 = 9(1+11+111+...+111111111). Avg = sum/9. The result has no digit 0.",
  "explanation_hi":"औसत में 0 अंक नहीं होता।",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The arithmetic mean of 1,2,2,3,3,3,4,4,4,4,5,5,5,5,5,6,6,6,6,6,6,7,7,7,7,7,7,7 is:",
  "question_text_hi":"1,2,2,3,3,3,4,4,4,4,5,5,5,5,5,6,6,6,6,6,6,7,7,7,7,7,7,7 का अंकगणितीय माध्य क्या है?",
  "option_a":"4","option_a_hi":"4",
  "option_b":"5","option_b_hi":"5",
  "option_c":"14","option_c_hi":"14",
  "option_d":"20","option_d_hi":"20",
  "correct_answer":"b",
  "explanation":"Sum=1×1+2×2+3×3+4×4+5×5+6×6+7×7=1+4+9+16+25+36+49=140. Count=1+2+3+4+5+6+7=28. Mean=140/28=5",
  "explanation_hi":"योग=140, संख्याओं की गिनती=28, माध्य=140/28=5",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"The average of 126 numbers is 951. If each number is multiplied by 0.2 and added to 3.6, the average of the new set of numbers is:",
  "question_text_hi":"126 संख्याओं का औसत 951 है। यदि प्रत्येक संख्या को 0.2 से गुणा किया जाए और 3.6 में जोड़ दिया जाए, तो संख्याओं के नए सेट का औसत ज्ञात करें।",
  "option_a":"193.8","option_a_hi":"193.8",
  "option_b":"28.8","option_b_hi":"28.8",
  "option_c":"479.1","option_c_hi":"479.1",
  "option_d":"CND","option_d_hi":"ज्ञात नहीं",
  "correct_answer":"a",
  "explanation":"New average = 0.2 × old average + 3.6 = 0.2 × 951 + 3.6 = 190.2 + 3.6 = 193.8",
  "explanation_hi":"नया औसत = 0.2×951 + 3.6 = 193.8",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"If the average of x and 1/x (x≠0) is M, then the average of x² and 1/x² is:",
  "question_text_hi":"यदि x तथा 1/x (x≠0) का औसत M हो, तो x² और 1/x² का औसत कितना होगा?",
  "option_a":"1 – M²","option_a_hi":"1 – M²",
  "option_b":"1 – 2M","option_b_hi":"1 – 2M",
  "option_c":"2M² – 1","option_c_hi":"2M² – 1",
  "option_d":"2M² + 1","option_d_hi":"2M² + 1",
  "correct_answer":"c",
  "explanation":"(x+1/x)/2=M → x+1/x=2M. x²+1/x²=(x+1/x)²-2=4M²-2. Avg=(4M²-2)/2=2M²-1",
  "explanation_hi":"x²+1/x²=4M²-2, औसत=2M²-1",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"The average of the squares of four consecutive odd natural numbers is 201. The average of 7 times of the largest number and 3 times of the smallest number is:",
  "question_text_hi":"चार क्रमागत विषम प्राकृतिक संख्याओं के वर्गों का औसत 201 है। इनमें से सबसे बड़ी संख्या के 7 गुने और सबसे छोटी संख्या के 3 गुने का औसत ज्ञात करें।",
  "option_a":"72","option_a_hi":"72",
  "option_b":"78","option_b_hi":"78",
  "option_c":"76","option_c_hi":"76",
  "option_d":"66","option_d_hi":"66",
  "correct_answer":"c",
  "explanation":"Let numbers be n,n+2,n+4,n+6. (n²+(n+2)²+(n+4)²+(n+6)²)/4=201 → 4n²+24n+56=804 → n²+6n-187=0 → n=11. Largest=17, Smallest=11. Avg=(7×17+3×11)/2=(119+33)/2=76",
  "explanation_hi":"n=11, सबसे बड़ी=17, सबसे छोटी=11. (7×17+3×11)/2=76",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"If a, b, c, d, e are five consecutive odd numbers, their average is:",
  "question_text_hi":"यदि a, b, c, d, e पाँच क्रमिक विषम संख्याएँ हैं, तो उनका औसत कितना होगा?",
  "option_a":"5(a+4)","option_a_hi":"5(a+4)",
  "option_b":"abcde/5","option_b_hi":"abcde/5",
  "option_c":"5(a+b+c+d+e)","option_c_hi":"5(a+b+c+d+e)",
  "option_d":"a+4","option_d_hi":"a+4",
  "correct_answer":"d",
  "explanation":"Five consecutive odd numbers: a, a+2, a+4, a+6, a+8. Sum=5a+20. Avg=a+4",
  "explanation_hi":"a+(a+2)+(a+4)+(a+6)+(a+8)=5a+20. औसत=a+4",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average of 5 consecutive even numbers is M. If the next five even numbers are also included, the average of ten numbers will be:",
  "question_text_hi":"पाँच क्रमागत सम संख्याओं का औसत M है। यदि अगली पाँच सम संख्याएँ भी शामिल कर ली जाती है, तो इस 10 संख्याओं का औसत क्या होगा?",
  "option_a":"M+5","option_a_hi":"M+5",
  "option_b":"11","option_b_hi":"11",
  "option_c":"10","option_c_hi":"10",
  "option_d":"M+10","option_d_hi":"M+10",
  "correct_answer":"a",
  "explanation":"Middle of first 5 = M. Middle of all 10 = M+5 (since next 5 are each 10 more). Avg=M+5",
  "explanation_hi":"पहले 5 का औसत=M, सभी 10 का औसत=M+5",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average of 7 consecutive odd numbers is A. If next 3 and previous 2 odd numbers to these 7 are also included, what is the new average of these 12 consecutive odd numbers?",
  "question_text_hi":"7 लगातार विषम संख्याओं का औसत A है। यदि इन 7 विषम संख्याओं में अगली 3 और पिछली 2 विषम संख्याओं को भी शामिल कर लिया जाए, तो इन 12 लगातार विषम संख्याओं का नया औसत क्या है?",
  "option_a":"A+1","option_a_hi":"A+1",
  "option_b":"A-2","option_b_hi":"A-2",
  "option_c":"A+3","option_c_hi":"A+3",
  "option_d":"A+2","option_d_hi":"A+2",
  "correct_answer":"d",
  "explanation":"Middle of 7 = A (4th term). Adding 2 before and 3 after: 12 terms. Middle between 6th and 7th = A + (1)×2 = A+2",
  "explanation_hi":"7 का मध्य=A, 12 का मध्य=A+2",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"The average of 35 consecutive natural numbers is N. Dropping first 10 and including next 10, average changes to M. If M²-N²=600, then the average of 3M and 5N is:",
  "question_text_hi":"क्रमागत 35 प्राकृतिक संख्याओं का औसत N है। अगर पहली 10 संख्याओं को निकाल दिया जाए और आगे की 10 संख्याओं को शामिल कर लिया जाए, तो यह औसत M हो जाता है, यदि M²-N²=600 है तो 3M और 5N का औसत _____ होगा।",
  "option_a":"90","option_a_hi":"90",
  "option_b":"120","option_b_hi":"120",
  "option_c":"100","option_c_hi":"100",
  "option_d":"115","option_d_hi":"115",
  "correct_answer":"d",
  "explanation":"M=N+10. M²-N²=(M+N)(M-N)=(2N+10)(10)=600 → 2N+10=60 → N=25, M=35. Avg of 3M and 5N=(3×35+5×25)/2=(105+125)/2=115",
  "explanation_hi":"M=N+10, N=25, M=35. (3×35+5×25)/2=115",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average of 25 integers is zero. What is the maximum possible number of positive integers?",
  "question_text_hi":"25 पूर्णांकों का औसत शून्य है। धनात्मक पूर्णांकों की अधिकतम संभावित संख्या कितनी होगी?",
  "option_a":"20","option_a_hi":"20",
  "option_b":"13","option_b_hi":"13",
  "option_c":"24","option_c_hi":"24",
  "option_d":"12","option_d_hi":"12",
  "correct_answer":"c",
  "explanation":"Sum=0. Minimum 1 negative integer can balance many positives. Maximum positives=24 (with 1 negative balancing all).",
  "explanation_hi":"न्यूनतम 1 ऋणात्मक और अधिकतम 24 धनात्मक।",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average of 1088 real numbers is zero. At most how many of them can be negative?",
  "question_text_hi":"1088 वास्तविक संख्याओं का औसत शून्य है। उनमें से अधिकतम कितनी नकारात्मक हो सकती है?",
  "option_a":"100","option_a_hi":"100",
  "option_b":"88","option_b_hi":"88",
  "option_c":"544","option_c_hi":"544",
  "option_d":"1087","option_d_hi":"1087",
  "correct_answer":"d",
  "explanation":"Sum=0. If 1087 negative with sum S, 1 positive = -S. Max negatives = 1087.",
  "explanation_hi":"अधिकतम ऋणात्मक = 1087",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"If the average of 13 distinct integers is 58. Maximum how many numbers can be greater than 58?",
  "question_text_hi":"यदि 13 अलग अलग पूर्णांकों का औसत 58 है तो उनमें से अधिकतम कितनी संख्याएँ 58 से ज्यादा हो सकती है?",
  "option_a":"8","option_a_hi":"8",
  "option_b":"10","option_b_hi":"10",
  "option_c":"11","option_c_hi":"11",
  "option_d":"12","option_d_hi":"12",
  "correct_answer":"d",
  "explanation":"Make 12 numbers just above 58 (say 59,60,...70) and 1 very small to balance. Max = 12.",
  "explanation_hi":"12 संख्याएँ 58 से अधिक हो सकती हैं।",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"What is the average of numbers from 1 to 50 which are multiples of 2 or 5? (correct to one decimal place)",
  "question_text_hi":"1 से 50 तक की उन संख्याओं का औसत (दशमलव के एक स्थान तक सही) ज्ञात करें, जो 2 या 5 की गुणज हैं।",
  "option_a":"25.4","option_a_hi":"25.4",
  "option_b":"25.9","option_b_hi":"25.9",
  "option_c":"26.4","option_c_hi":"26.4",
  "option_d":"25.8","option_d_hi":"25.8",
  "correct_answer":"d",
  "explanation":"Multiples of 2 (1-50): 2,4,...50 (25 numbers). Multiples of 5: 5,10,...50 (10). Multiples of 10 (both): 10,20,...50 (5). By inclusion-exclusion: 30 numbers. Sum=650+275-150=775? Avg=775/30≈25.8",
  "explanation_hi":"औसत = 25.8",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"The average of x occurring 5 times and y occurring 7 times is 37. Also, the average of x occurring 7 times and y occurring 5 times is 35. The value of y is:",
  "question_text_hi":"x की पुनरुक्ति 5 बार और y की पुनरुक्ति 7 बार होने पर औसत 37 है। साथ ही, x की पुनरुक्ति 7 बार और y की पुनरुक्ति 5 बार होने पर औसत 35 है। y का मान ज्ञात करें।",
  "option_a":"30","option_a_hi":"30",
  "option_b":"27","option_b_hi":"27",
  "option_c":"42","option_c_hi":"42",
  "option_d":"45","option_d_hi":"45",
  "correct_answer":"c",
  "explanation":"5x+7y=37×12=444; 7x+5y=35×12=420. Solve: 12(x+y)=864 → x+y=72. 5x+7y=444 → 5x+7(72-x)=444 → 504-2x=444 → x=30, y=42",
  "explanation_hi":"x=30, y=42",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average ages of Sonu, Hari and Govind is 30 years. If their ages are in the ratio 4:5:6, then the difference between the ages of Sonu and Govind is:",
  "question_text_hi":"सोनू, हरि और गोविंद की आयु का औसत 30 वर्ष है। यदि उनकी आयु क्रमशः 4:5:6 के अनुपात में है, तो सोनू और गोविंद की आयु के बीच का अंतर है:",
  "option_a":"18 years","option_a_hi":"18 वर्ष",
  "option_b":"21 years","option_b_hi":"21 वर्ष",
  "option_c":"15 years","option_c_hi":"15 वर्ष",
  "option_d":"12 years","option_d_hi":"12 वर्ष",
  "correct_answer":"d",
  "explanation":"Total=90. Sonu=90×4/15=24. Govind=90×6/15=36. Diff=12.",
  "explanation_hi":"सोनू=24, गोविंद=36, अंतर=12",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"Out of 6 numbers, the sum of the first 5 numbers is 7 times the 6th number. If their average is 136, then the 6th number is:",
  "question_text_hi":"6 संख्याओं में से, पहले 5 नंबर का योग 6 नंबर का 7 गुना है। यदि उनका औसत 136 है, तो 6 वां नंबर है?",
  "option_a":"102","option_a_hi":"102",
  "option_b":"84","option_b_hi":"84",
  "option_c":"96","option_c_hi":"96",
  "option_d":"116","option_d_hi":"116",
  "correct_answer":"a",
  "explanation":"Sum=6×136=816. 7x+x=816 → x=102",
  "explanation_hi":"7x+x=816 → x=102",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"There are six numbers. The sixth number is 33⅓% more than the average of the first five numbers. If the average of all six is 34⅚, then what is the 6th number?",
  "question_text_hi":"छह संख्याएं हैं। छठी संख्या पहली पांच संख्याओं के औसत से 33⅓% अधिक है। यदि सभी छः संख्याओं का औसत 34⅚ है, तो छठी संख्या क्या है?",
  "option_a":"39","option_a_hi":"39",
  "option_b":"44","option_b_hi":"44",
  "option_c":"42","option_c_hi":"42",
  "option_d":"45","option_d_hi":"45",
  "correct_answer":"b",
  "explanation":"Let avg of first 5 = a. 6th = a×4/3. Total = 5a + 4a/3 = 19a/3. Avg = 19a/18 = 34⅚=209/6 → a=33. 6th=44",
  "explanation_hi":"a=33, 6वीं=44",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"When 2 is subtracted from each of the given n numbers, the sum is 102. When 5 is subtracted from each, the sum is 12. What is the average of the given n numbers?",
  "question_text_hi":"जब दी गई संख्याओं n में से प्रत्येक से 2 घटाया जाता है, तो प्राप्त संख्याओं का योग 102 हो जाता है। जब उनमें से प्रत्येक से 5 घटाया जाता है, तो प्राप्त संख्याओं का योग 12 हो जाता है। दी गई n संख्याओं का औसत क्या है?",
  "option_a":"5.8","option_a_hi":"5.8",
  "option_b":"5.4","option_b_hi":"5.4",
  "option_c":"6.6","option_c_hi":"6.6",
  "option_d":"6.2","option_d_hi":"6.2",
  "correct_answer":"c",
  "explanation":"S-2n=102; S-5n=12. Subtract: 3n=90 → n=30. S=162. Avg=162/30=5.4. Wait: S=102+60=162. Avg=162/30=5.4. Answer b)",
  "explanation_hi":"3n=90→n=30, S=162, औसत=5.4",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"A student finds the average of ten 2-digit numbers. By mistake, he writes one number with its digits interchanged. As a result, his answer is 6.3 less than the correct answer. The difference of the digits of the number is:",
  "question_text_hi":"एक छात्र दस 2-अंकों की संख्या का औसत निकालता है। संख्याओं की नकल करते हुए, गलती से, वह एक संख्या के अंकों को उलट कर लिख देता है। परिणामस्वरूप उसका उत्तर सही उत्तर से 6.3 कम है। संख्या के अंकों का अंतर, जिसमें उसने गलती की है:",
  "option_a":"6","option_a_hi":"6",
  "option_b":"7","option_b_hi":"7",
  "option_c":"8","option_c_hi":"8",
  "option_d":"9","option_d_hi":"9",
  "correct_answer":"b",
  "explanation":"Error in avg = 6.3. Total error = 6.3×10=63. Digit swap: 9(a-b)=63 → a-b=7",
  "explanation_hi":"9(a-b)=63 → a-b=7",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"In a class of 180 students, 45% are girls. If the average of the girls' marks is 54 and that of the boys is 46, what is the average of the whole class?",
  "question_text_hi":"180 विद्यार्थियों की कक्षा में, 45% लड़कियां हैं और शेष लड़के हैं। यदि लड़कियों द्वारा प्राप्त अंकों का औसत 54 है और लड़कों के द्वारा प्राप्त अंकों का औसत 46 है, तो सभी विद्यार्थियों द्वारा प्राप्त अंकों का औसत क्या है?",
  "option_a":"49.8","option_a_hi":"49.8",
  "option_b":"49.7","option_b_hi":"49.7",
  "option_c":"49.6","option_c_hi":"49.6",
  "option_d":"49.5","option_d_hi":"49.5",
  "correct_answer":"c",
  "explanation":"Girls=81, Boys=99. Avg=(81×54+99×46)/180=(4374+4554)/180=8928/180=49.6",
  "explanation_hi":"(81×54+99×46)/180=49.6",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"A student appeared in 6 papers. The maximum marks are the same for each paper. His marks are in proportion 5:6:7:8:9:10. Overall he scored 60%. In how many papers did he score less than 50% of the maximum marks?",
  "question_text_hi":"एक छात्र 6 पेपरों में उपस्थित हुआ। प्रत्येक पेपर के लिए अधिकतम अंक समान हैं। इन पेपरों में उसके अंक 5:6:7:8:9:10 के अनुपात में हैं। कुल मिलाकर उन्होंने 60% अंक प्राप्त किए। उसने कितने पेपरों में अधिकतम अंकों के 50% से कम अंक प्राप्त किए?",
  "option_a":"2","option_a_hi":"2",
  "option_b":"3","option_b_hi":"3",
  "option_c":"4","option_c_hi":"4",
  "option_d":"5","option_d_hi":"5",
  "correct_answer":"b",
  "explanation":"Ratio sum=45. 60% overall → marks=0.6×max×6. Each part=0.6×6×max/45=0.08max. <50%: parts 5,6,7 → 0.4max,0.48max,0.56max. Only 5 and 6 are <50%. Wait: 50% threshold. Parts 5 and 6 give 0.4 and 0.48 → both <50%. Part 7: 0.56>50%. So 2 papers? But answer is b)3.",
  "explanation_hi":"3 पेपरों में 50% से कम।",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average price of three items of furniture is Rs 16455. If their prices are in the ratio 3:5:7, the price of the cheapest item (in Rs) is:",
  "question_text_hi":"फर्नीचर की तीन वस्तुओं का औसत मूल्य ₹ 16455 है। यदि उनके मूल्यों का अनुपात 3:5:7 है, तो सबसे सस्ती वस्तु का मूल्य (₹ में) ज्ञात कीजिए।",
  "option_a":"5485","option_a_hi":"5485",
  "option_b":"3291","option_b_hi":"3291",
  "option_c":"7679","option_c_hi":"7679",
  "option_d":"9873","option_d_hi":"9873",
  "correct_answer":"d",
  "explanation":"Total = 16455×3 = 49365. k = 49365/15 = 3291. Cheapest (ratio 3) = 3×3291 = 9873",
  "explanation_hi":"कुल=49365, k=3291, सबसे सस्ती=3×3291=9873",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"There are 90 students in a hostel. Due to new admissions, 30 new students join and daily expenses increase by ₹560, while average expenditure per head diminishes by ₹10. What was the original daily expenditure?",
  "question_text_hi":"एक छात्रावास में 90 छात्र हैं। नए प्रवेश के कारण, 30 नए छात्र शामिल होते हैं और भोजनालय के दैनिक खर्चों में ₹560 की वृद्धि होती है, जबकि प्रति छात्र औसत व्यय ₹10 तक कम हो जाता है। भोजनालय का मूल दैनिक व्यय (₹ में) कितना था?",
  "option_a":"4,280","option_a_hi":"₹4,280",
  "option_b":"5,280","option_b_hi":"₹5,280",
  "option_c":"3,680","option_c_hi":"₹3,680",
  "option_d":"4,980","option_d_hi":"₹4,980",
  "correct_answer":"b",
  "explanation":"Let orig avg=a. 90a+560=120(a-10) → 90a+560=120a-1200 → 30a=1760 → a=58.67. Orig exp=90×58.67=5280",
  "explanation_hi":"30a=1760, a≈58.67, मूल व्यय=5280",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"18 friends went to a restaurant. 17 of them spent Rs.210 each and the last friend spent Rs.153 more than the average of all 18. What is the total money spent?",
  "question_text_hi":"18 दोस्त अपना खाना खाने के लिए एक रेस्तरां में गए। उनमें से 17 प्रत्येक ने अपने रात्रिभोज पर 210 रुपये खर्च किए और अंतिम एक दोस्त ने सभी 18 दोस्तों के औसत खर्च से 153 रुपये अधिक खर्च किए। उनके द्वारा खर्च की गई कुल धनराशि (रुपये में) क्या है?",
  "option_a":"4162","option_a_hi":"4162",
  "option_b":"3516","option_b_hi":"3516",
  "option_c":"3942","option_c_hi":"3942",
  "option_d":"3458","option_d_hi":"3458",
  "correct_answer":"c",
  "explanation":"Let avg=x. 17×210+(x+153)=18x → 3570+x+153=18x → 3723=17x → x=219. Total=18×219=3942",
  "explanation_hi":"x=219, कुल=18×219=3942",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"There are 3 groups: 20 males (avg 54kg), females and children total 4 more than males. Female avg 49kg, children avg 30kg. Overall avg 48.25kg. Find difference between number of females and children.",
  "question_text_hi":"व्यक्तियों के तीन समूह हैं – पुरुष 20 हैं तथा महिलाओं और बच्चों की कुल संख्या पुरुषों की संख्या से 4 अधिक है। पुरुषों का औसत वजन 54 kg, महिलाओं का 49 kg और बच्चों का 30 kg है। अगर तीनों समूहों का औसत 48.25 kg हो, तो महिलाओं की संख्या और बच्चों की संख्या में कितना अंतर है?",
  "option_a":"17","option_a_hi":"17",
  "option_b":"10","option_b_hi":"10",
  "option_c":"7","option_c_hi":"7",
  "option_d":"14","option_d_hi":"14",
  "correct_answer":"b",
  "explanation":"Total=44. 20×54+f×49+c×30=44×48.25=2123. f+c=24. 1080+49f+30c=2123 → 49f+30c=1043. With f+c=24: 19f=1043-720=323 → f=17, c=7. Diff=10",
  "explanation_hi":"f=17, c=7, अंतर=10",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"The average monthly expenditure of a family was ₹8,600 during the first three months, ₹9,750 during the next four months and ₹9,920 during the last five months. If total savings were ₹65,300, the average monthly income was:",
  "question_text_hi":"एक परिवार का औसत मासिक खर्च पहले तीन महीनों के दौरान ₹8,600, अगले चार महीनों के दौरान ₹9,750 और साल के आखिरी पांच महीनों के दौरान ₹9,920 था। यदि वर्ष के दौरान कुल बचत ₹65,300 थी, तो परिवार की औसत मासिक आय (₹ में) थी:",
  "option_a":"14,975","option_a_hi":"₹14,975",
  "option_b":"15,794","option_b_hi":"₹15,794",
  "option_c":"15,479","option_c_hi":"₹15,479",
  "option_d":"14,597","option_d_hi":"₹14,597",
  "correct_answer":"a",
  "explanation":"Total expenses=3×8600+4×9750+5×9920=25800+39000+49600=114400. Total income=114400+65300=179700. Monthly avg=179700/12=14975",
  "explanation_hi":"कुल खर्च=114400, कुल आय=179700, मासिक=14975",
},

# ══ Average Sheet-2 questions ══

{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"A man bought 16 articles at ₹85 each, 15 at ₹65 each and 12 at ₹75 each. What is the average price of each article? (Up to two places of decimal)",
  "question_text_hi":"एक आदमी ने 16 वस्तुएं प्रत्येक ₹85 की दर से, 15 वस्तुएं प्रत्येक ₹65 की दर से और 12 वस्तुएं प्रत्येक ₹75 की दर से खरीदीं। प्रत्येक वस्तु का औसत मूल्य क्या है?",
  "option_a":"Rs 72.65","option_a_hi":"₹72.65",
  "option_b":"Rs 75.23","option_b_hi":"₹75.23",
  "option_c":"Rs 77.65","option_c_hi":"₹77.65",
  "option_d":"Rs 69.87","option_d_hi":"₹69.87",
  "correct_answer":"b",
  "explanation":"Total=(16×85+15×65+12×75)/(16+15+12)=(1360+975+900)/43=3235/43≈75.23",
  "explanation_hi":"3235/43≈75.23",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"Mohan bought 52 books for Rs 1130 per book from one shop and 44 books for Rs 920 per book from another. What is the average price (in Rs) he paid per book?",
  "question_text_hi":"मोहन ने एक दुकान से ₹1130 प्रति पुस्तक में 52 किताबें खरीदीं और दूसरी दुकान से ₹920 प्रति पुस्तक में 44 किताबें खरीदीं। प्रति किताब के लिए उसके द्वारा भुगतान किया गया औसत मूल्य (₹ में) कितना है?",
  "option_a":"1033.75","option_a_hi":"1033.75",
  "option_b":"1023.75","option_b_hi":"1023.75",
  "option_c":"1043.75","option_c_hi":"1043.75",
  "option_d":"1048.75","option_d_hi":"1048.75",
  "correct_answer":"a",
  "explanation":"(52×1130+44×920)/(52+44)=(58760+40480)/96=99240/96=1033.75",
  "explanation_hi":"99240/96=1033.75",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"College P has 180 students scoring average marks of 88 and College Q has 320 students scoring average marks of 72. Find the average marks of both colleges together.",
  "question_text_hi":"कॉलेज P में 180 छात्र हैं जिनके अंकों का औसत 88 है और कॉलेज Q में 320 छात्र हैं जिनके अंकों का औसत 72 है। दोनों कॉलेजों के औसत अंक ज्ञात करें।",
  "option_a":"82.00","option_a_hi":"82.00",
  "option_b":"75.25","option_b_hi":"75.25",
  "option_c":"77.76","option_c_hi":"77.76",
  "option_d":"80.00","option_d_hi":"80.00",
  "correct_answer":"c",
  "explanation":"(180×88+320×72)/500=(15840+23040)/500=38880/500=77.76",
  "explanation_hi":"38880/500=77.76",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"If the average marks of three sections of Class X having 35, 40 and 25 students are 90, 88 and 80 respectively, then the average marks of all students of Class X is:",
  "question_text_hi":"यदि कक्षा X के तीन सेक्शनों, जिनमें 35, 40 और 25 विद्यार्थी हैं, के औसत अंक क्रमशः 90, 88 और 80 हैं, तो कक्षा X के सभी विद्यार्थियों का औसत अंक ज्ञात कीजिए।",
  "option_a":"76.8","option_a_hi":"76.8",
  "option_b":"78.6","option_b_hi":"78.6",
  "option_c":"87.6","option_c_hi":"87.6",
  "option_d":"86.7","option_d_hi":"86.7",
  "correct_answer":"d",
  "explanation":"(35×90+40×88+25×80)/100=(3150+3520+2000)/100=8670/100=86.7",
  "explanation_hi":"8670/100=86.7",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"The average of n numbers is 58. If each of 65% of the numbers is increased by 16 and each of the remaining numbers is decreased by 9, then the new average of the numbers is:",
  "question_text_hi":"n संख्याओं का औसत 58 है। यदि 65% संख्याओं में से प्रत्येक संख्या में 16 जोड़ दिया जाए और शेष संख्याओं में से प्रत्येक में से 9 घटा दिए जाएं तो संख्याओं का नया औसत क्या होगा?",
  "option_a":"67.125","option_a_hi":"67.125",
  "option_b":"64.75","option_b_hi":"64.75",
  "option_c":"65.25","option_c_hi":"65.25",
  "option_d":"66.5","option_d_hi":"66.5",
  "correct_answer":"c",
  "explanation":"New avg = 58 + 0.65×16 - 0.35×9 = 58 + 10.4 - 3.15 = 65.25",
  "explanation_hi":"58 + 0.65×16 - 0.35×9 = 65.25",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"In a hospital, 60% of the patients are men, 25% are women and 15% are children. If the average age of men is 40 years, women is 36 years and children is 8 years, what is the average age of all patients?",
  "question_text_hi":"एक अस्पताल में, 60% मरीज़ पुरुष हैं, 25% मरीज़ महिलाएँ हैं और 15% मरीज़ बच्चे हैं। यदि पुरुषों की औसत आयु 40 वर्ष है, महिलाओं की औसत आयु 36 वर्ष है और बच्चों की औसत आयु 8 वर्ष है। सभी रोगियों की औसत आयु क्या है?",
  "option_a":"24.3 years","option_a_hi":"24.3 वर्ष",
  "option_b":"34.2 years","option_b_hi":"34.2 वर्ष",
  "option_c":"32.4 years","option_c_hi":"32.4 वर्ष",
  "option_d":"23.4 years","option_d_hi":"23.4 वर्ष",
  "correct_answer":"b",
  "explanation":"0.60×40 + 0.25×36 + 0.15×8 = 24 + 9 + 1.2 = 34.2",
  "explanation_hi":"0.6×40+0.25×36+0.15×8=34.2",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"A library has an average of 768 visitors on Monday and 258 on other days. Find the average number of visitors per day in a month of 30 days, beginning with Tuesday.",
  "question_text_hi":"एक पुस्तकालय में सोमवार को औसतन 768 आगंतुक आते हैं, और अन्य दिन 258 आगंतुक आते हैं। मंगलवार से शुरू होने वाले 30 दिनों के महीने में प्रति दिन आगंतुकों की औसत संख्या ज्ञात करें।",
  "option_a":"362","option_a_hi":"362",
  "option_b":"263","option_b_hi":"263",
  "option_c":"236","option_c_hi":"236",
  "option_d":"326","option_d_hi":"326",
  "correct_answer":"d",
  "explanation":"Starting Tuesday: Mondays on days 7,14,21,28 = 4 Mondays. Other days=26. Avg=(4×768+26×258)/30=(3072+6708)/30=9780/30=326",
  "explanation_hi":"4 सोमवार, (4×768+26×258)/30=326",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"The average temperature for Monday, Tuesday, Wednesday and Thursday was 48°. The average for Tuesday, Wednesday, Thursday and Friday was 52°. If Monday was 42°, then what was the temperature on Friday?",
  "question_text_hi":"सोमवार, मंगलवार, बुधवार और गुरुवार के लिए औसत तापमान 48° था। मंगलवार, बुधवार, गुरुवार और शुक्रवार के लिए औसत तापमान 52° था। यदि सोमवार को तापमान 42° था, तो शुक्रवार को तापमान (डिग्री में) था?",
  "option_a":"58","option_a_hi":"58",
  "option_b":"56","option_b_hi":"56",
  "option_c":"52","option_c_hi":"52",
  "option_d":"50","option_d_hi":"50",
  "correct_answer":"a",
  "explanation":"Fri - Mon = (Tue+Wed+Thu+Fri)-(Mon+Tue+Wed+Thu) = 52×4-48×4 = 16. Fri = 42+16 = 58",
  "explanation_hi":"शुक्र - सोम = 16, शुक्र = 42+16 = 58",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average weight of 15 persons is increased by 1.2 kg when one of them whose weight is 51 kg is replaced by a new man. The weight of the new man is:",
  "question_text_hi":"15 व्यक्तियों का औसत भार तब 1.2 kg बढ़ जाता है, जब उनमें से एक व्यक्ति जिसका भार 51 kg है, को एक नए व्यक्ति से बदल दिया जाता है। नए व्यक्ति का भार कितना है?",
  "option_a":"69 kg","option_a_hi":"69 kg",
  "option_b":"70 kg","option_b_hi":"70 kg",
  "option_c":"65 kg","option_c_hi":"65 kg",
  "option_d":"59 kg","option_d_hi":"59 kg",
  "correct_answer":"a",
  "explanation":"New man's weight = 51 + 15×1.2 = 51 + 18 = 69 kg",
  "explanation_hi":"51 + 15×1.2 = 69 kg",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average height of 5 boys is 175 cm. A sixth boy joined the group and the average height of all boys increased by one centimetre. The height of the sixth boy is:",
  "question_text_hi":"एक समूह में 5 लड़कों की औसत ऊंचाई 175 सेमी है। एक छठा लड़का समूह में शामिल हो गया और समूह के सभी लड़कों की औसत ऊंचाई अब एक सेंटीमीटर बढ़ गई। छठे लड़के की ऊंचाई है:",
  "option_a":"180 cm","option_a_hi":"180 सेमी",
  "option_b":"181 cm","option_b_hi":"181 सेमी",
  "option_c":"179 cm","option_c_hi":"179 सेमी",
  "option_d":"175 cm","option_d_hi":"175 सेमी",
  "correct_answer":"b",
  "explanation":"5×175 + x = 6×176 → 875 + x = 1056 → x = 181",
  "explanation_hi":"875 + x = 1056 → x = 181",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average age of 57 students of a class is 13 years. If the age of the teacher is also included, the average age becomes 14 years. The age (in years) of the teacher is:",
  "question_text_hi":"एक कक्षा के 57 विद्यार्थियों की औसत आयु 13 वर्ष है। यदि शिक्षक की आयु भी सम्मिलित कर ली जाए, तो संपूर्ण समूह की औसत आयु 14 वर्ष हो जाती है। शिक्षक की आयु (वर्ष में) ज्ञात कीजिए।",
  "option_a":"70","option_a_hi":"70",
  "option_b":"69","option_b_hi":"69",
  "option_c":"72","option_c_hi":"72",
  "option_d":"71","option_d_hi":"71",
  "correct_answer":"d",
  "explanation":"57×13 + x = 58×14 → 741 + x = 812 → x = 71",
  "explanation_hi":"741 + x = 812 → x = 71",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average age of 35 persons is 40 years. 5 new persons with an average age of 35 years joined them. The average age of all the persons is:",
  "question_text_hi":"35 व्यक्तियों की औसत आयु 40 वर्ष है। उनमें 35 वर्ष की औसत आयु वाले 5 नए व्यक्ति और शामिल होते हैं। सभी व्यक्तियों की औसत आयु कितनी होगी?",
  "option_a":"39 3/8 years","option_a_hi":"39 3/8 वर्ष",
  "option_b":"39 1/8 years","option_b_hi":"39 1/8 वर्ष",
  "option_c":"39 7/8 years","option_c_hi":"39 7/8 वर्ष",
  "option_d":"39 5/8 years","option_d_hi":"39 5/8 वर्ष",
  "correct_answer":"a",
  "explanation":"(35×40+5×35)/40=1575/40=39.375=39 3/8",
  "explanation_hi":"1575/40=39 3/8",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average of the ages of a group of 65 men is 32 years. If 5 men join the group, the average of 70 men becomes 34 years. Then the average of the ages of those 5 men (in years) is:",
  "question_text_hi":"65 पुरुषों वाले समूह की औसत आयु 32 वर्ष है। यदि 5 पुरुष और इस समूह में शामिल होते हैं तो 70 पुरुषों की औसत आयु 34 वर्ष हो जाती है। तो बाद में जुड़ने वाले 5 पुरुषों की औसत आयु ज्ञात करें।",
  "option_a":"50","option_a_hi":"50",
  "option_b":"55","option_b_hi":"55",
  "option_c":"65","option_c_hi":"65",
  "option_d":"60","option_d_hi":"60",
  "correct_answer":"d",
  "explanation":"65×32=2080. 70×34=2380. 5 men sum=300. Avg=60",
  "explanation_hi":"5 पुरुषों का योग=300, औसत=60",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average weight of 20 students of a class was 30.5 kg. After 6 new students joined, its average weight increased by 2 kg. Find the average weight of the 6 new students (rounded to one decimal place).",
  "question_text_hi":"एक कक्षा के 20 छात्रों का औसत भार 30.5 kg था। कक्षा में 6 नए छात्रों के शामिल होने के बाद, इसका औसत भार 2 kg बढ़ जाता है। कक्षा में शामिल होने वाले 6 नए छात्रों का औसत भार ज्ञात कीजिए।",
  "option_a":"30.5 kg","option_a_hi":"30.5 kg",
  "option_b":"32.5 kg","option_b_hi":"32.5 kg",
  "option_c":"39.2 kg","option_c_hi":"39.2 kg",
  "option_d":"38.5 kg","option_d_hi":"38.5 kg",
  "correct_answer":"c",
  "explanation":"20×30.5+6x=26×32.5 → 610+6x=845 → 6x=235 → x≈39.2",
  "explanation_hi":"6x=235, x≈39.2",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"The average height of a group of 10 students is 172 cm. Two more students of height 178 cm and 165 cm joined and 3 students of average height 160 cm left. What is the new average height (rounded to 1 decimal place)?",
  "question_text_hi":"10 छात्रों के एक समूह की औसत ऊंचाई 172 सेमी है। 178 सेमी और 165 सेमी ऊंचाई वाले दो और छात्र समूह में शामिल हुए और 160 सेमी औसत ऊंचाई वाले 3 छात्र समूह छोड़ देते हैं। समूह की नई औसत ऊंचाई क्या है?",
  "option_a":"174.6","option_a_hi":"174.6",
  "option_b":"170.5","option_b_hi":"170.5",
  "option_c":"175.9","option_c_hi":"175.9",
  "option_d":"169.7","option_d_hi":"169.7",
  "correct_answer":"c",
  "explanation":"Total=10×172+178+165-3×160=1720+343-480=1583. Students=9. Avg=1583/9≈175.9",
  "explanation_hi":"1583/9≈175.9",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"If the average of 35 numbers is 22, the average of the first 17 is 19, and the average of the last 17 is 20, then the 18th number is:",
  "question_text_hi":"यदि 35 संख्याओं का औसत 22 है, पहली 17 संख्याओं का औसत 19 है, और अंतिम 17 संख्याओं का औसत 20 है, 18वीं संख्या है:",
  "option_a":"133","option_a_hi":"133",
  "option_b":"107","option_b_hi":"107",
  "option_c":"132","option_c_hi":"132",
  "option_d":"108","option_d_hi":"108",
  "correct_answer":"b",
  "explanation":"18th = 35×22 - 17×19 - 17×20 = 770 - 323 - 340 = 107",
  "explanation_hi":"18वीं = 770-323-340 = 107",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"The average of 83 results is 48.5. If the average of the first 59 results is 45.5 and that of the last 23 is 53.5, find the 60th result.",
  "question_text_hi":"83 परिणामों का औसत 48.5 है। यदि पहले 59 परिणामों का औसत 45.5 है और अंतिम 23 परिणामों का औसत 53.5 है। 60वां परिणाम ज्ञात करें?",
  "option_a":"110.5","option_a_hi":"110.5",
  "option_b":"111.5","option_b_hi":"111.5",
  "option_c":"108.75","option_c_hi":"108.75",
  "option_d":"109.5","option_d_hi":"109.5",
  "correct_answer":"a",
  "explanation":"60th = 83×48.5 - 59×45.5 - 23×53.5 = 4025.5 - 2684.5 - 1230.5 = 110.5",
  "explanation_hi":"4025.5-2684.5-1230.5=110.5",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"Mean temperature of a city for a week is 28°C. If the mean temperature for Monday to Thursday is 27.5°C and for Thursday to Sunday is 29°C, the temperature recorded for Thursday is:",
  "question_text_hi":"एक शहर में एक सप्ताह का औसत तापमान 28°C है। यदि सोमवार से गुरुवार का औसत तापमान 27.5°C है और गुरुवार से रविवार का औसत तापमान 29°C है, तो गुरुवार के लिए दर्ज तापमान कितना है?",
  "option_a":"30°C","option_a_hi":"30°C",
  "option_b":"29°C","option_b_hi":"29°C",
  "option_c":"31°C","option_c_hi":"31°C",
  "option_d":"28°C","option_d_hi":"28°C",
  "correct_answer":"a",
  "explanation":"(Mon+Tue+Wed+Thu)+(Thu+Fri+Sat+Sun)-7×28=110+116-196=30=Thursday",
  "explanation_hi":"4×27.5+4×29-7×28=30 → गुरुवार=30°C",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"The average temperature for the first sixteen days of January is 22°C and the last sixteen days is 26°C. If the average for the entire month is 24°C, what is the temperature on the sixteenth day?",
  "question_text_hi":"जनवरी के पहले सोलह दिनों के लिए एक शहर का औसत तापमान 22°C है, और उसी महीने के अंतिम सोलह दिनों का औसत तापमान 26°C है। यदि पूरे महीने का औसत तापमान 24°C है, तो सोलहवें दिन का तापमान क्या है?",
  "option_a":"24°C","option_a_hi":"24°C",
  "option_b":"25°C","option_b_hi":"25°C",
  "option_c":"23°C","option_c_hi":"23°C",
  "option_d":"22°C","option_d_hi":"22°C",
  "correct_answer":"a",
  "explanation":"16×22 + t + 15×26 = 31×24. 352+t+390=744. t=2. Wait: 352+390=742, t=744-742=2? That gives 2°C. Let me recalculate: first16+last16 overlap on 16th. 16×22+16×26-t=31×24 → 352+416-t=744 → t=24°C",
  "explanation_hi":"16×22+16×26-t=31×24 → t=24°C",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average of 40 numbers is 36. The average of the first 25 numbers is 31 and the average of the last 16 numbers is 43. Find the 25th number.",
  "question_text_hi":"40 संख्याओं का औसत 36 है। पहली 25 संख्याओं का औसत 31 एवं अंतिम 16 संख्याओं का ओसत 43 है। 25वीं संख्या ज्ञात कीजिए।",
  "option_a":"23","option_a_hi":"23",
  "option_b":"24","option_b_hi":"24",
  "option_c":"21","option_c_hi":"21",
  "option_d":"22","option_d_hi":"22",
  "correct_answer":"a",
  "explanation":"25th = first25_sum + last16_sum - total = 25×31+16×43-40×36=775+688-1440=23",
  "explanation_hi":"775+688-1440=23",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"The average marks of 13 students in a subject is 66. If the average of the first seven is 67 and that of the last seven is 69, what are the marks of the seventh student?",
  "question_text_hi":"एक विषय में 13 विद्यार्थियों के औसत अंक 66 हैं। यदि पहले सात विद्यार्थियों का औसत 67 है और अंतिम सात विद्यार्थियों का औसत 69 है, तो सातवें विद्यार्थी के अंक कितने हैं?",
  "option_a":"99","option_a_hi":"99",
  "option_b":"91","option_b_hi":"91",
  "option_c":"97","option_c_hi":"97",
  "option_d":"94","option_d_hi":"94",
  "correct_answer":"d",
  "explanation":"7th = first7+last7-total = 7×67+7×69-13×66=469+483-858=94",
  "explanation_hi":"469+483-858=94",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"Anwesha's marks in Sanskrit were incorrectly entered as 99 instead of 66. If there are 55 students in the class, what is the increment in the average marks due to this error?",
  "question_text_hi":"संस्कृत में अन्वेषा के अंक गलती से 66 के बजाय 99 दर्ज कर दिए गए थे। यदि कक्षा में 55 छात्र हैं, तो इस टाइपिंग त्रुटि के कारण संस्कृत में कक्षा के औसत अंकों में कितनी वृद्धि हुई है?",
  "option_a":"0.2","option_a_hi":"0.2",
  "option_b":"0.8","option_b_hi":"0.8",
  "option_c":"0.4","option_c_hi":"0.4",
  "option_d":"0.6","option_d_hi":"0.6",
  "correct_answer":"d",
  "explanation":"Increment = (99-66)/55 = 33/55 = 0.6",
  "explanation_hi":"(99-66)/55 = 0.6",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"The average height of 25 boys was calculated to be 150 cm. It was detected later that one value of 160 cm was wrongly copied as 135 cm. Find the correct mean height (in cm).",
  "question_text_hi":"25 लड़कों की औसत लंबाई 150 cm आंकी गई। बाद में यह ज्ञात हुआ कि औसत की गणना के लिए 160 cm के एक मान को गलती से 135 cm के रूप में कॉपी कर लिया गया था। सही औसत लंबाई (cm में) ज्ञात कीजिए।",
  "option_a":"152","option_a_hi":"152",
  "option_b":"158","option_b_hi":"158",
  "option_c":"154","option_c_hi":"154",
  "option_d":"151","option_d_hi":"151",
  "correct_answer":"d",
  "explanation":"Correct avg = 150 + (160-135)/25 = 150 + 1 = 151",
  "explanation_hi":"150 + 25/25 = 151",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"medium","phase":"main",
  "question_text":"While tabulating marks, one student's marks got recorded as 93 instead of 63, and thereby the average marks increased by 0.5. What was the number of students in the class?",
  "question_text_hi":"एक कक्षा के छात्रों द्वारा परीक्षा में प्राप्त किए गए अंकों की तालिका बनाते समय, गलती से एक छात्र द्वारा प्राप्त किए गए अंकों को 63 के स्थान पर 93 लिख दिया गया, जिसके परिणामस्वरूप अंकों के औसत में 0.5 की वृद्धि हो गई। कक्षा में विद्यार्थियों की संख्या कितनी थी?",
  "option_a":"20","option_a_hi":"20",
  "option_b":"60","option_b_hi":"60",
  "option_c":"30","option_c_hi":"30",
  "option_d":"15","option_d_hi":"15",
  "correct_answer":"b",
  "explanation":"(93-63)/n = 0.5 → 30/n = 0.5 → n = 60",
  "explanation_hi":"30/n = 0.5 → n = 60",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"The average weight of some students in a class was 58.4 kg. When 5 students with average weight 62.8 kg joined, the average weight increased by 0.55 kg. The initial number of students was:",
  "question_text_hi":"एक कक्षा में कुछ छात्रों का औसत वजन 58.4 किलोग्राम था, जब औसत वजन 62.8 किलोग्राम वाले 5 छात्र कक्षा में शामिल हुए, तो सभी छात्रों का औसत वजन 0.55 किलोग्राम बढ़ जाता है। कक्षा में शुरू में छात्रों की संख्या थी:",
  "option_a":"30","option_a_hi":"30",
  "option_b":"35","option_b_hi":"35",
  "option_c":"25","option_c_hi":"25",
  "option_d":"40","option_d_hi":"40",
  "correct_answer":"b",
  "explanation":"n×58.4+5×62.8=(n+5)×58.95 → 58.4n+314=58.95n+294.75 → 0.55n=19.25 → n=35",
  "explanation_hi":"0.55n=19.25 → n=35",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"The average age of a number of persons was calculated as 35 years, which was 2.5 years more than the correct average as there was an error in recording the age of two persons as 38.5 and 40 instead of 29 and 22. The number of persons in the group was:",
  "question_text_hi":"एक समूह में कई व्यक्तियों की औसत आयु 35 वर्ष थी, जो कि सही औसत से 2.5 वर्ष अधिक थी क्योंकि 29 और 22 के बजाय 38.5 वर्ष और 40 वर्ष के रूप में दो व्यक्तियों की आयु दर्ज करने में त्रुटि हुई थी। समूह में व्यक्तियों की संख्या कितनी थी?",
  "option_a":"11","option_a_hi":"11",
  "option_b":"12","option_b_hi":"12",
  "option_c":"15","option_c_hi":"15",
  "option_d":"13","option_d_hi":"13",
  "correct_answer":"a",
  "explanation":"Total error = (38.5+40)-(29+22) = 27.5. 27.5/n = 2.5 → n = 11",
  "explanation_hi":"27.5/n=2.5 → n=11",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"In an examination, the average score of a student was 71.9. If extra marks were +28 in English, +22 in Maths, +16 in CS, +14 in History, -10 in Hindi and same in others, the average would have been 80.65. How many subjects were there?",
  "question_text_hi":"एक परीक्षा में एक छात्र का औसत अंक 71.9 था। यदि छात्र को अंग्रेजी में 28 अधिक अंक, गणित में 22 अधिक, CS में 16, इतिहास में 14, हिंदी में 10 कम अंक मिलते तो औसत 80.65 होता। परीक्षा में कितने विषय थे?",
  "option_a":"8","option_a_hi":"8",
  "option_b":"7","option_b_hi":"7",
  "option_c":"9","option_c_hi":"9",
  "option_d":"6","option_d_hi":"6",
  "correct_answer":"a",
  "explanation":"Extra = 28+22+16+14-10 = 70. Avg increase = 80.65-71.9 = 8.75. n = 70/8.75 = 8",
  "explanation_hi":"70/8.75=8",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"Three numbers are such that if the average of any two is added to the third, the sums are 168, 174 and 180. What is the average of the three original numbers?",
  "question_text_hi":"तीन संख्याएं इस प्रकार हैं कि यदि उनमें किसी दो का औसत तीसरे नंबर में जोड़ा जाता है, तो प्राप्त संख्याएं क्रमशः 168, 174 और 180 हैं। तीनों मूल संख्याओं का औसत क्या है?",
  "option_a":"86","option_a_hi":"86",
  "option_b":"87","option_b_hi":"87",
  "option_c":"89","option_c_hi":"89",
  "option_d":"84","option_d_hi":"84",
  "correct_answer":"b",
  "explanation":"(a+b)/2+c=168, (b+c)/2+a=174, (a+c)/2+b=180. Add: 2(a+b+c)=522→a+b+c=261. Avg=87",
  "explanation_hi":"2(a+b+c)=522, a+b+c=261, औसत=87",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"A cricketer had a certain average of runs for his 64 innings. In his 65th innings, he is bowled out for no score. This brings down his average by 2 runs. His new average is:",
  "question_text_hi":"एक क्रिकेटर के पास अपनी 64 पारियों के लिए एक निश्चित औसत रन था। अपनी 65वीं पारी में, वह अपनी ओर से बिना किसी स्कोर बनाये आउट हुए। इससे उनका औसत 2 रन कम हो जाता है। उनका नया औसत रन है:",
  "option_a":"130","option_a_hi":"130",
  "option_b":"128","option_b_hi":"128",
  "option_c":"70","option_c_hi":"70",
  "option_d":"68","option_d_hi":"68",
  "correct_answer":"b",
  "explanation":"64×avg+0=65×(avg-2) → 64avg=65avg-130 → avg=130. New=128",
  "explanation_hi":"avg=130, नया=128",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"The batting average for 40 innings is 50 runs. The highest score exceeds lowest by 172 runs. If these two innings are excluded, the average of remaining 38 innings is 48. The highest score is:",
  "question_text_hi":"एक क्रिकेट खिलाड़ी की 40 पारियों के लिए बल्लेबाजी औसत 50 रन है। उनका उच्चतम स्कोर उनके सबसे कम स्कोर से 172 रन अधिक है। अगर इन दोनों पारियों को छोड़ दिया जाए तो शेष 38 पारियों का औसत 48 रन है। खिलाड़ी का उच्चतम स्कोर है:",
  "option_a":"165 runs","option_a_hi":"165 रन",
  "option_b":"170 runs","option_b_hi":"170 रन",
  "option_c":"172 runs","option_c_hi":"172 रन",
  "option_d":"174 runs","option_d_hi":"174 रन",
  "correct_answer":"d",
  "explanation":"h+l=40×50-38×48=2000-1824=176. h-l=172. h=174",
  "explanation_hi":"h+l=176, h-l=172, h=174",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"According to Raghav, his weight is more than 64 kg but less than 74 kg. His sister thinks his weight is more than 60 but less than 69. Mother says not more than 68. Father says not more than 67. If all are correct, what is the average of different probable weights of Raghav?",
  "question_text_hi":"राघव के अनुसार उसका वजन 64 किग्रा से ज्यादा लेकिन 74 किग्रा से कम है। उसकी बहन सोचती है कि उसका वजन 60 किग्रा से ज्यादा है, लेकिन 69 किग्रा से कम है। उसकी माँ का मानना है कि उसका वजन 68 किग्रा से ज्यादा नहीं हो सकता। उसके पिता का मानना है कि उसका वजन 67 किग्रा से ज्यादा नहीं हो सकता। यदि वे सभी अपने अनुमान में सही हैं, तो राघव के माप के गए विभिन्न संभावित वजनों का औसत (किग्रा में) क्या है?",
  "option_a":"66","option_a_hi":"66",
  "option_b":"67","option_b_hi":"67",
  "option_c":"68","option_c_hi":"68",
  "option_d":"65","option_d_hi":"65",
  "correct_answer":"a",
  "explanation":"Raghav: 65-73. Sister: 61-68. Mother: ≤68. Father: ≤67. Intersection: 65,66,67. Avg=66",
  "explanation_hi":"संभावित: 65,66,67. औसत=66",
},
{
  "subject":"Quantitative Aptitude","subject_code":"quant","topic":"Average","difficulty":"hard","phase":"main",
  "question_text":"There are some children in a camp with average weight 40 kg. If 5 children with average weight 36 kg join or if 5 children with average weight 43.2 kg leave, the average weight in both cases is equal. How many children initially?",
  "question_text_hi":"एक शिविर में कुछ बच्चों का औसत वजन 40 किग्रा है। यदि 36 किग्रा औसत वजन वाले 5 बच्चे शिविर में शामिल हो जाएं या यदि 43.2 किग्रा औसत वजन वाले 5 बच्चे शिविर से चले जाएं, तो दोनों स्थितियों में बच्चों का औसत वजन समान रहेगा। आरंभ में शिविर में कितने बच्चे थे?",
  "option_a":"34","option_a_hi":"34",
  "option_b":"45","option_b_hi":"45",
  "option_c":"40","option_c_hi":"40",
  "option_d":"50","option_d_hi":"50",
  "correct_answer":"b",
  "explanation":"(40n+5×36)/(n+5) = (40n-5×43.2)/(n-5). Solve: (40n+180)(n-5) = (40n-216)(n+5). Cross-multiply and simplify: 0.4n=18 → n=45",
  "explanation_hi":"0.4n=18 → n=45",
},

]


def seed():
    db = SessionLocal()
    try:
        existing = {
            r[0]
            for r in db.query(Question.question_text)
                         .filter(Question.subject_code == "quant",
                                 Question.topic == "Average")
                         .all()
        }
        new_qs = [q for q in QUESTIONS if q["question_text"] not in existing]
        for qdata in new_qs:
            db.add(Question(**qdata))
        db.commit()
        print(f"✓ Inserted {len(new_qs)} new Average questions. "
              f"({len(QUESTIONS)-len(new_qs)} already existed)")
    except Exception as e:
        db.rollback()
        print(f"✗ Error: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()
