import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app.database.connection import SessionLocal
from app.models.question_model import Question

QUESTIONS = [
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "Express the following as decimals, respectively: 2%, 0.5%, 0.3%",
        "option_a": "0.02, 0.005, 0.003",
        "option_b": "0.2, 0.05, 0.03",
        "option_c": "0.02, 0.005, 0.0003",
        "option_d": "0.2, 0.0005, 0.0003",
        "correct_answer": "a",
        "explanation": "2% = 2/100 = 0.02; 0.5% = 0.5/100 = 0.005; 0.3% = 0.3/100 = 0.003.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "12.75% is equivalent to which of the following fractions? (SSC CHSL 2024)",
        "option_a": "53/400",
        "option_b": "51/400",
        "option_c": "49/400",
        "option_d": "47/400",
        "correct_answer": "b",
        "explanation": "12.75% = 12.75/100 = 1275/10000 = 51/400.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "What is the value of √(64%)? (UPSC CDS-2 2024)",
        "option_a": "0.4",
        "option_b": "0.8",
        "option_c": "0.64",
        "option_d": "0.08",
        "correct_answer": "b",
        "explanation": "64% = 64/100. √(64/100) = 8/10 = 0.8.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "What is 28% of 525? (UP Constable 18/06/2018 2nd Shift)",
        "option_a": "140",
        "option_b": "147",
        "option_c": "154",
        "option_d": "133",
        "correct_answer": "b",
        "explanation": "28% of 525 = (28/100) × 525 = 14700/100 = 147.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "Which of the following is the least?",
        "option_a": "12% of 625",
        "option_b": "15% of 555",
        "option_c": "10% of 720",
        "option_d": "9% of 845",
        "correct_answer": "c",
        "explanation": "12% of 625 = 75; 15% of 555 = 83.25; 10% of 720 = 72; 9% of 845 = 76.05. Least = 72 = 10% of 720.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "What is 0.08% of 120% of 50,000?",
        "option_a": "40",
        "option_b": "48",
        "option_c": "56",
        "option_d": "36",
        "correct_answer": "b",
        "explanation": "0.08% of 120% of 50000 = (0.08/100) × (120/100) × 50000 = 0.0008 × 1.2 × 50000 = 48.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "hard",
        "phase": "main",
        "question_text": "What is the value of 17½% of 3¼% of 33⅓% of 7200?",
        "option_a": "7.65",
        "option_b": "11.68",
        "option_c": "13.65",
        "option_d": "9.65",
        "correct_answer": "c",
        "explanation": "33⅓% of 7200 = 2400. 3¼% of 2400 = 0.0325 × 2400 = 78. 17½% of 78 = 0.175 × 78 = 13.65.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "What is 34% of 12 km? (Express in cm)",
        "option_a": "3,96,000 cm",
        "option_b": "4,08,000 cm",
        "option_c": "4,20,000 cm",
        "option_d": "3,84,000 cm",
        "correct_answer": "b",
        "explanation": "12 km = 1,200,000 cm. 34% of 1,200,000 = (34/100) × 1,200,000 = 4,08,000 cm.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "10 quintals is what percent of 10 metric tons? (UPSC CDS-1 2025)",
        "option_a": "1%",
        "option_b": "10%",
        "option_c": "5%",
        "option_d": "0.1%",
        "correct_answer": "b",
        "explanation": "1 quintal = 100 kg; 1 metric ton = 1000 kg. 10 quintals = 1000 kg; 10 metric tons = 10000 kg. (1000/10000) × 100 = 10%.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "1 hour 45 minutes is what percent of a day?",
        "option_a": "7.218%",
        "option_b": "7.292%",
        "option_c": "7.435%",
        "option_d": "7.378%",
        "correct_answer": "b",
        "explanation": "1 hr 45 min = 105 min. 1 day = 1440 min. (105/1440) × 100 = 7.2916...% ≈ 7.292%.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "If 5% of a = b, then b% of 20 is the same as:",
        "option_a": "20% of a/2",
        "option_b": "50% of a/20",
        "option_c": "50% of a/2",
        "option_d": "20% of a/20",
        "correct_answer": "d",
        "explanation": "b = 5a/100 = a/20. b% of 20 = (b/100) × 20 = (a/20)/100 × 20 = a/100. 20% of a/20 = (20/100) × (a/20) = a/100. ✓",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "If x% of a is the same as y% of b, then z% of b equals:",
        "option_a": "(yz/x)% of a",
        "option_b": "(xz/y)% of a",
        "option_c": "(x/yz)% of a",
        "option_d": "(xy/z)% of a",
        "correct_answer": "b",
        "explanation": "x% of a = y% of b → b = xa/y. z% of b = (z/100) × xa/y = (xz/y)/100 × a = (xz/y)% of a.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "If A is 95% of B, then what percent of A is B? (SSC CGL 2023 Pre)",
        "option_a": "110 17/19%",
        "option_b": "104 17/19%",
        "option_c": "107 17/19%",
        "option_d": "105 5/19%",
        "correct_answer": "d",
        "explanation": "A = 0.95B → B = A/0.95 = 100A/95 = 20A/19. B as % of A = (20/19) × 100 = 2000/19 = 105 5/19%.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "By what percent does a number increase if it becomes 6 times its original value?",
        "option_a": "400%",
        "option_b": "100%",
        "option_c": "600%",
        "option_d": "500%",
        "correct_answer": "d",
        "explanation": "Increase = 6x - x = 5x. % increase = (5x/x) × 100 = 500%.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "A₁ is 19 times more than A₂. By what percent is A₂ less than A₁? (IB ACIO 2023)",
        "option_a": "90%",
        "option_b": "80%",
        "option_c": "95%",
        "option_d": "85%",
        "correct_answer": "c",
        "explanation": "A₁ = A₂ + 19A₂ = 20A₂. A₂ is less than A₁ by (20A₂ - A₂)/(20A₂) × 100 = 19/20 × 100 = 95%.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "If 91% of A = 39% of B, and B is x% of A, then find x.",
        "option_a": "200/3",
        "option_b": "700/3",
        "option_c": "400/3",
        "option_d": "500/3",
        "correct_answer": "b",
        "explanation": "91A/100 = 39B/100 → 91A = 39B → B = 91A/39 = 7A/3. x% of A = B → x = (7/3) × 100 = 700/3.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "hard",
        "phase": "main",
        "question_text": "If (x - y) = 45% of (x + y) and y = k% of x, then 21% of k equals:",
        "option_a": "1",
        "option_b": "6",
        "option_c": "7",
        "option_d": "3",
        "correct_answer": "c",
        "explanation": "x - y = 0.45(x+y) → 55x = 145y → y/x = 11/29. k = 1100/29. 21% of k = 21 × 11/29 ≈ 7.97 ≈ 7.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "2% of 13% of a number is what percent of that number? (RPF Constable 2025)",
        "option_a": "0.26%",
        "option_b": "2.6%",
        "option_c": "0.026%",
        "option_d": "26%",
        "correct_answer": "a",
        "explanation": "2% of 13% = (2/100) × (13/100) = 26/10000 = 0.26% of the number.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "[25% of (50% of (30% of 150))] / (40% of 2250) is equal to:",
        "option_a": "0.825%",
        "option_b": "0.25%",
        "option_c": "0.625%",
        "option_d": "0.225%",
        "correct_answer": "c",
        "explanation": "30% of 150 = 45. 50% of 45 = 22.5. 25% of 22.5 = 5.625. 40% of 2250 = 900. 5.625/900 = 0.00625 = 0.625%.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "If 25% of 400 + 35% of 1260 + 27% of 1800 = 1020 + x, then x lies between:",
        "option_a": "6 to 10",
        "option_b": "10 to 20",
        "option_c": "0 to 5",
        "option_d": "20 to 30",
        "correct_answer": "a",
        "explanation": "25% of 400 = 100; 35% of 1260 = 441; 27% of 1800 = 486. Total = 1027. x = 1027 - 1020 = 7. 7 lies between 6 and 10.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "Find the value of: 91.6% of 640 + 136% of 916",
        "option_a": "1832",
        "option_b": "1382",
        "option_c": "1512",
        "option_d": "1976",
        "correct_answer": "a",
        "explanation": "0.916 × 640 = 586.24. 1.36 × 916 = 1245.76. Sum = 586.24 + 1245.76 = 1832.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "Find the value of: 78.5% of 640 + 36% of 785 - 29 × 21",
        "option_a": "173",
        "option_b": "143",
        "option_c": "151",
        "option_d": "176",
        "correct_answer": "d",
        "explanation": "78.5% of 640 = 502.4. 36% of 785 = 282.6. 29 × 21 = 609. 502.4 + 282.6 - 609 = 785 - 609 = 176.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "If a% of 240 = c and c% of a = 117.6, find the value of (a + c).",
        "option_a": "238",
        "option_b": "144",
        "option_c": "260",
        "option_d": "196",
        "correct_answer": "a",
        "explanation": "c = 2.4a. (2.4a × a)/100 = 117.6 → a² = 4900 → a = 70. c = 168. a + c = 238.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "If A% of A is 9604, what is the value of A? (SSC GD 2024)",
        "option_a": "1020",
        "option_b": "980",
        "option_c": "920",
        "option_d": "880",
        "correct_answer": "b",
        "explanation": "A²/100 = 9604 → A² = 960400 → A = √960400 = 980.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "If 35% of k is 20 less than 1200% of 25, find the value of k. (RPF Constable 2025)",
        "option_a": "840",
        "option_b": "760",
        "option_c": "800",
        "option_d": "780",
        "correct_answer": "c",
        "explanation": "1200% of 25 = 300. 35% of k = 300 - 20 = 280. k = 280/0.35 = 800.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "In a basket, the ratio of apples to pears is 5:8. What is the percentage of pears (correct to 2 decimal places)? (SSC MTS 2024)",
        "option_a": "69.50%",
        "option_b": "63.45%",
        "option_c": "61.54%",
        "option_d": "59.44%",
        "correct_answer": "c",
        "explanation": "Total parts = 5+8 = 13. Percentage of pears = (8/13) × 100 = 61.538...% ≈ 61.54%.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "If the word PHOTOGRAPH is written with F in place of PH everywhere, what is the percentage reduction in the number of letters?",
        "option_a": "20%",
        "option_b": "10%",
        "option_c": "25%",
        "option_d": "15%",
        "correct_answer": "a",
        "explanation": "PHOTOGRAPH has 10 letters. PH appears twice (at start and end). Replacing both PH with F gives FOTOGRAF = 8 letters. Reduction = 2, % = (2/10) × 100 = 20%.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "A person's monthly expenditure decreased from Rs.12,800 to Rs.11,712. What is the percentage decrease? (SSC CHSL 2024)",
        "option_a": "7.7%",
        "option_b": "6.25%",
        "option_c": "8.5%",
        "option_d": "9.25%",
        "correct_answer": "c",
        "explanation": "Decrease = 12800 - 11712 = 1088. % decrease = (1088/12800) × 100 = 8.5%.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "A person's monthly salary increased from Rs.36,890 to Rs.47,980. What is the percentage increase (nearest integer)? (RPF Constable 2025)",
        "option_a": "30%",
        "option_b": "32%",
        "option_c": "35%",
        "option_d": "25%",
        "correct_answer": "a",
        "explanation": "Increase = 47980 - 36890 = 11090. % increase = (11090/36890) × 100 ≈ 30.07% ≈ 30%.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "A shopping complex had sales of Rs.1,24,645 last year and Rs.1,41,449 this year. What is the percentage increase (rounded to nearest integer)? (RPF Constable 2025)",
        "option_a": "13%",
        "option_b": "12%",
        "option_c": "9%",
        "option_d": "18%",
        "correct_answer": "a",
        "explanation": "Increase = 141449 - 124645 = 16804. % increase = (16804/124645) × 100 ≈ 13.48% ≈ 13%.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "In a class, 48% of the males equal two-thirds of the females. What is the ratio of males to females? (SSC CGL 2023 Pre)",
        "option_a": "25:12",
        "option_b": "18:25",
        "option_c": "12:25",
        "option_d": "25:18",
        "correct_answer": "d",
        "explanation": "0.48M = (2/3)F → F = 0.72M. M:F = 1:0.72 = 100:72 = 25:18.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "The sum of 8% of A and 5% of B is three-fifths of the sum of 12% of A and 10% of B. Find A:B. (ICAR Technician 2023)",
        "option_a": "6:11",
        "option_b": "5:4",
        "option_c": "11:6",
        "option_d": "4:5",
        "correct_answer": "b",
        "explanation": "8A/100 + 5B/100 = (3/5)(12A/100 + 10B/100). 8A+5B = 0.6(12A+10B) = 7.2A+6B. 0.8A = B. A:B = 1:0.8 = 5:4.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "The monthly income of Amara is Rs.80,200. If it decreased by 11%, what is her new monthly income? (DP Constable 2023)",
        "option_a": "Rs.71,500",
        "option_b": "Rs.71,378",
        "option_c": "Rs.71,820",
        "option_d": "Rs.71,250",
        "correct_answer": "b",
        "explanation": "New income = 80200 × (1 - 0.11) = 80200 × 0.89 = 71,378.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "easy",
        "phase": "main",
        "question_text": "A number, when increased by 16%, becomes 1914. What is the original number?",
        "option_a": "2220",
        "option_b": "1650",
        "option_c": "2010",
        "option_d": "1780",
        "correct_answer": "b",
        "explanation": "x × 1.16 = 1914 → x = 1914/1.16 = 1650.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "Farida's monthly salary at her current job is 28% less than her previous job. If her current salary is Rs.27,000, what was her previous salary? (DP Constable 2023)",
        "option_a": "Rs.37,500",
        "option_b": "Rs.36,000",
        "option_c": "Rs.38,250",
        "option_d": "Rs.38,500",
        "correct_answer": "a",
        "explanation": "27000 = Previous × (1 - 0.28) = Previous × 0.72. Previous = 27000/0.72 = 37,500.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "A number when decreased by 37.5% gives 378. What is the number? (SSC MTS 2023)",
        "option_a": "606.4",
        "option_b": "608.0",
        "option_c": "602.2",
        "option_d": "604.8",
        "correct_answer": "d",
        "explanation": "x × (1 - 0.375) = 378 → x × 0.625 = 378 → x = 378/0.625 = 604.8.",
    },
    {
        "subject": "Quantitative Aptitude",
        "subject_code": "quant",
        "topic": "Percentage",
        "difficulty": "medium",
        "phase": "main",
        "question_text": "In a factory, 11% of the total output was found to be defective. If the number of correct products is 4984, how many products were defective? (RPF SI 19/12/2018 Evening)",
        "option_a": "616",
        "option_b": "456",
        "option_c": "676",
        "option_d": "586",
        "correct_answer": "a",
        "explanation": "Correct = 89% of Total = 4984 → Total = 4984/0.89 = 5600. Defective = 11% of 5600 = 616.",
    },
]


def seed():
    db = SessionLocal()
    try:
        added = 0
        for q in QUESTIONS:
            exists = db.query(Question).filter(
                Question.question_text == q["question_text"]
            ).first()
            if not exists:
                db.add(Question(**q))
                added += 1
        db.commit()
        print(f"Seeded {added} new Percentage questions (skipped {len(QUESTIONS) - added} duplicates).")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
