import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app.database.connection import SessionLocal
from app.models.question_model import Question

QUESTIONS = [
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "hard", "phase": "main",
        "question_text": "For a number greater than one, the difference between itself and its reciprocal is 20% of the sum of itself and its reciprocal. By how much percentage (nearest integer) is the square of the number less than its cube? (CHSL 2018)",
        "option_a": "12", "option_b": "18", "option_c": "29", "option_d": "33",
        "correct_answer": "b",
        "explanation": "x - 1/x = 0.2(x + 1/x) → 0.8x = 1.2/x → x² = 1.5. x = √1.5 ≈ 1.2247. % less = (1-1/x)×100 = (1-0.8165)×100 ≈ 18%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "easy", "phase": "main",
        "question_text": "A student mistakenly reads the number 97 as 79. Find the percentage decrease in its calculation. (DP Constable 2023)",
        "option_a": "19.55% Increase", "option_b": "19% decrease", "option_c": "18% decrease", "option_d": "18.55% decrease",
        "correct_answer": "d",
        "explanation": "% decrease = (97 - 79)/97 × 100 = 18/97 × 100 ≈ 18.55% decrease.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "If a student multiplied a number by 7/12 instead of 11/16, then find the % error in the calculation.",
        "option_a": "16.16%", "option_b": "15.15%", "option_c": "14.28%", "option_d": "12.50%",
        "correct_answer": "b",
        "explanation": "Error = 11/16 - 7/12 = 33/48 - 28/48 = 5/48. % error = (5/48)/(11/16) × 100 = (5×16)/(48×11) × 100 = 500/33 ≈ 15.15%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "The price of oil has increased by 35%. By what percentage should the increased price of oil be reduced so that the price of oil remains the same?",
        "option_a": "33.33%", "option_b": "35%", "option_c": "27.92%", "option_d": "25.93%",
        "correct_answer": "d",
        "explanation": "Reduce = 35/(100+35) × 100 = 35/135 × 100 = 700/27 ≈ 25.93%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "The price of sugar increased by 22.5%. Anita wants to keep her expenditure the same. By what % must she reduce consumption (correct to two decimal places)?",
        "option_a": "19.24%", "option_b": "18.37%", "option_c": "18.80%", "option_d": "17.12%",
        "correct_answer": "b",
        "explanation": "Reduction = 22.5/(100+22.5) × 100 = 22.5/122.5 × 100 = 900/49 ≈ 18.37%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "If the price of petrol increased by 7%, by what % should consumption decrease to keep expenditure unchanged? (SSC CGL 2023 Pre)",
        "option_a": "6 58/107%", "option_b": "5 11/107%", "option_c": "3 37/107%", "option_d": "4 37/107%",
        "correct_answer": "a",
        "explanation": "Reduction = 7/(100+7) × 100 = 700/107 = 6 58/107%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "A person increases his consumption of sugar by 42.84% because the price of sugar is reduced by x%. Find x (expenditure remains constant). (SSC CGL 2023 Pre)",
        "option_a": "32%", "option_b": "35%", "option_c": "30%", "option_d": "28%",
        "correct_answer": "c",
        "explanation": "(1 - x/100) × 1.4284 = 1 → 1 - x/100 = 0.70 → x = 30%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "The price of LPG cylinder has increased from Rs.656 to Rs.820. What % of consumption should be reduced so that amount spent on LPG remains the same? (SSC CPO 2020)",
        "option_a": "25%", "option_b": "20%", "option_c": "30%", "option_d": "35%",
        "correct_answer": "b",
        "explanation": "% increase = (820-656)/656 × 100 = 25%. Reduction = 25/125 × 100 = 20%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "If the price of petrol becomes Rs.110/litre from Rs.95/litre, by how much % should consumption be reduced by Ravi so that his expenditure remains the same? (correct to two decimals) (SSC GD 2023)",
        "option_a": "15.29%", "option_b": "16.34%", "option_c": "14.63%", "option_d": "13.64%",
        "correct_answer": "d",
        "explanation": "Increase = 15/95 × 100 ≈ 15.79%. Reduction = 15/(95+15) × 100 = 15/110 × 100 ≈ 13.64%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "Rice is now sold at ₹29/kg (was ₹25/kg). By how much % should a family reduce consumption to keep expenditure the same? (correct to nearest integer)",
        "option_a": "14%", "option_b": "13%", "option_c": "15%", "option_d": "12%",
        "correct_answer": "a",
        "explanation": "Reduction = (29-25)/29 × 100 = 4/29 × 100 ≈ 13.79% ≈ 14%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "The price of rice falls by 35%. How much extra rice can be bought with money sufficient to buy 104 kg of rice previously?",
        "option_a": "42 kg", "option_b": "45.5 kg", "option_c": "56 kg", "option_d": "52 kg",
        "correct_answer": "c",
        "explanation": "Budget = 104P. New qty = 104P/(0.65P) = 160 kg. Extra = 160 - 104 = 56 kg.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "The price of a commodity decreased by 25% and a household increased consumption by 20 kg to keep expenditure the same. What was the earlier consumption? (SSC CHSL Tier-I 2022)",
        "option_a": "60 kg", "option_b": "55 kg", "option_c": "75 kg", "option_d": "45 kg",
        "correct_answer": "a",
        "explanation": "P×C = 0.75P×(C+20) → C = 0.75C + 15 → 0.25C = 15 → C = 60 kg.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "Petrol price shot up 10%. A person travels 2200 km/month; car gives 16 km/litre. By how many km should he reduce travel to maintain expenditure at previous level? (UPSC CSAT 2025)",
        "option_a": "180 km", "option_b": "200 km", "option_c": "220 km", "option_d": "240 km",
        "correct_answer": "b",
        "explanation": "Old litres = 2200/16 = 137.5. New litres = 137.5/1.1 = 125. New distance = 125×16 = 2000 km. Reduction = 200 km.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "A 20% reduction in rate of sugar enables Sudhir to get 6 kg more sugar for Rs.960. What is the reduced rate of sugar per kg?",
        "option_a": "Rs.35", "option_b": "Rs.36", "option_c": "Rs.32", "option_d": "Rs.40",
        "correct_answer": "c",
        "explanation": "240/R = 6 (extra qty = 960/0.8R - 960/R = 240/R = 6) → R = 40. Reduced rate = 0.8×40 = Rs.32.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "A 15% reduction in price of wheat enables a housewife to buy 6 kg more for ₹2,720. The reduced price of wheat per kg (in ₹) is:",
        "option_a": "75", "option_b": "68", "option_c": "70", "option_d": "65",
        "correct_answer": "b",
        "explanation": "2720×0.15/(0.85P) = 6 → P = 408/5.1 = 80. Reduced price = 0.85×80 = 68.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "If due to a 12% decrease in price of sugar, Akshat can buy 7 kg more sugar for Rs.1200, find the actual price of sugar (in Rs.). (MTS 2023)",
        "option_a": "23.38", "option_b": "28.25", "option_c": "25.79", "option_d": "26.35",
        "correct_answer": "a",
        "explanation": "1200×0.12/(0.88P) = 7 → 144/(0.88P) = 7 → P = 144/6.16 = 1800/77 ≈ 23.38.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "A family spends ₹240/month on sugar. A 25% rise in price compels 1.5 kg reduction to spend same amount. What is the increased price per kg?",
        "option_a": "Rs.32", "option_b": "Rs.35", "option_c": "Rs.40", "option_d": "Rs.38",
        "correct_answer": "c",
        "explanation": "pq=240. 1.25p(q-1.5)=240 → 300-1.875p=240 → p=32. Increased price=1.25×32=Rs.40.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "x is inversely proportional to y. If x is increased by 37.5%, find % change in the value of y.",
        "option_a": "27.27% decrease", "option_b": "33.33% decrease", "option_c": "45% decrease", "option_d": "31.25% decrease",
        "correct_answer": "a",
        "explanation": "xy=k. New y = y/1.375. % decrease = 0.375/1.375 × 100 = 300/11 ≈ 27.27%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "Due to decrease in manpower, production in a factory decreases by 12%. By what % (two decimal places) should working hours be increased to restore original production?",
        "option_a": "6.2%", "option_b": "12.33%", "option_c": "13.64%", "option_d": "23.23%",
        "correct_answer": "c",
        "explanation": "% increase = 12/(100-12) × 100 = 12/88 × 100 = 150/11 ≈ 13.64%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "A contractor reduces working time from 48 hours to 36 hours per week without changing payment. What is the % increase in the hourly rate? (SSC MTS 2023)",
        "option_a": "30%", "option_b": "33⅓%", "option_c": "67%", "option_d": "70%",
        "correct_answer": "b",
        "explanation": "Hourly rate ratio: (P/36)/(P/48) = 48/36 = 4/3. % increase = 1/3 × 100 = 33⅓%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "In a triangle, base is increased by 66⅔%. By how much % should height be reduced so that area of triangle remains constant?",
        "option_a": "60%", "option_b": "40%", "option_c": "30%", "option_d": "45%",
        "correct_answer": "b",
        "explanation": "New base = 5B/3. For area constant: new H = 3H/5. % decrease = (1-3/5)×100 = 40%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "If the length of a rectangle is increased by 11.11%, then by how much % should its breadth be reduced to keep area same? (MTS 2023)",
        "option_a": "11.11%", "option_b": "20%", "option_c": "9.09%", "option_d": "10%",
        "correct_answer": "d",
        "explanation": "11.11% = 1/9. New length = 10L/9. New breadth = L×B/(10L/9) = 9B/10. Reduction = 10%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "If the radius of a cylinder is decreased by 20%, then by how much % must height increase so that volume remains same? (CGL 2017)",
        "option_a": "44%", "option_b": "36.25%", "option_c": "56.25%", "option_d": "62.5%",
        "correct_answer": "c",
        "explanation": "(0.8r)²×new_h = r²×h → 0.64×new_h = h → new_h = h/0.64. % increase = (1/0.64-1)×100 = 56.25%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "In a cuboid, length is increased by 20% and breadth is decreased by 10%. By what % should height be increased/decreased so that volume remains constant?",
        "option_a": "6.2% increase", "option_b": "6.2% decrease", "option_c": "7.4% increase", "option_d": "7.4% decrease",
        "correct_answer": "d",
        "explanation": "1.2 × 0.9 = 1.08. Height must decrease: (1 - 1/1.08) × 100 = 0.08/1.08 × 100 ≈ 7.4% decrease.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "hard", "phase": "main",
        "question_text": "A solution contains 16.5% salt. 18 litres of water are evaporated. Concentration becomes 20.9%. Find initial quantity of solution.",
        "option_a": "85.5 litres", "option_b": "95 litres", "option_c": "88 litres", "option_d": "75 litres",
        "correct_answer": "a",
        "explanation": "0.165V/(V-18) = 0.209 → 0.044V = 0.209×18 = 3.762 → V = 85.5 litres.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "hard", "phase": "main",
        "question_text": "How much water should be added to 1440 ml of 38% sugar solution so that it becomes a 17.1% sugar solution? (Level 2 13/06/2022 Shift 1)",
        "option_a": "1.76 L", "option_b": "1.32 L", "option_c": "2.42 L", "option_d": "2.09 L",
        "correct_answer": "a",
        "explanation": "Sugar = 0.38×1440 = 547.2 ml. New volume = 547.2/0.171 = 3200 ml. Water to add = 3200-1440 = 1760 ml = 1.76 L.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "A 28-litre solution of sugar and water has 26.4% sugar. After boiling, 6 litres of water evaporate. What % of sugar is left in the solution?",
        "option_a": "29.4%", "option_b": "31.2%", "option_c": "30.8%", "option_d": "33.6%",
        "correct_answer": "d",
        "explanation": "Sugar = 0.264×28 = 7.392 L. New volume = 22 L. % sugar = 7.392/22×100 = 33.6%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "hard", "phase": "main",
        "question_text": "A man's annual income increased by Rs.4.2 lakhs but tax rate reduced from 24% to 15%. He pays same tax as before. What is his increased income (in Rs. lakhs)? (SSC CGL 2020 Pre)",
        "option_a": "8.4", "option_b": "7.2", "option_c": "11.2", "option_d": "7",
        "correct_answer": "c",
        "explanation": "0.24I = 0.15(I+4.2) → 0.09I = 0.63 → I = 7. New income = 7 + 4.2 = 11.2 lakhs.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "hard", "phase": "main",
        "question_text": "A man's annual income increased by 4.5 lakhs, but tax rate reduced from 26% to 20%. He now pays ₹12,000 MORE income tax. What is his increased income (in lakhs)?",
        "option_a": "17.5", "option_b": "15.5", "option_c": "18.5", "option_d": "16.5",
        "correct_answer": "a",
        "explanation": "0.20(I+4.5) = 0.26I + 0.12 → 0.9-0.12 = 0.06I → I = 13. New income = 13+4.5 = 17.5 lakhs.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "hard", "phase": "main",
        "question_text": "Income tax rate increases from 15.2% to 20.9%. Gaurav pays 5.55% more tax. Simultaneously his income decreases by ₹18,400. Find Gaurav's income last year.",
        "option_a": "79200", "option_b": "72900", "option_c": "92700", "option_d": "97200",
        "correct_answer": "a",
        "explanation": "1.0555×0.152I = 0.209(I-18400) → 0.160436I = 0.209I - 3845.6 → 0.04856I = 3845.6 → I ≈ 79200.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "Price of oil increased by 20%. However, its consumption decreased by 18⅓%. What is the percentage increase or decrease in the expenditure on it?",
        "option_a": "Decrease by 1%", "option_b": "Increase by 4%", "option_c": "Increase by 2%", "option_d": "Decrease by 2%",
        "correct_answer": "d",
        "explanation": "18⅓% = 55/3%. New exp = 1.20 × (1-55/300) = 1.20 × 49/60 = 0.98. Decrease by 2%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "hard", "phase": "main",
        "question_text": "The price per litre of petrol increases by 85%. By what percent should its consumption be reduced so that expenditure on it increases by 11% only? (SSC GD 2025)",
        "option_a": "46%", "option_b": "60%", "option_c": "40%", "option_d": "53%",
        "correct_answer": "c",
        "explanation": "1.85 × new_C = 1.11 × C → new_C = 1.11/1.85 × C = 0.6C. Reduction = 40%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "Price of diesel increased by 26%. A person wants to increase expenditure by 15% only. By what % (one decimal place) should he decrease consumption?",
        "option_a": "7.2%", "option_b": "9.5%", "option_c": "8.7%", "option_d": "6.5%",
        "correct_answer": "c",
        "explanation": "new_C = 1.15/1.26 × C = 0.9127C. Decrease = (1-0.9127)×100 ≈ 8.7%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "When the price of a commodity increased by 23%, a family reduced its consumption so that expenditure was only 5% more. By what % (one decimal place) has the family reduced its consumption?",
        "option_a": "14%", "option_b": "15.2%", "option_c": "15.8%", "option_d": "14.6%",
        "correct_answer": "d",
        "explanation": "new_C/C = 1.05/1.23 = 0.8537. Reduction = (1-0.8537)×100 ≈ 14.6%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "When sugar price increased by 53%, a family reduced consumption so expenditure was only 19% more. If family consumed 38.7 kg per month earlier, find reduction in monthly consumption.",
        "option_a": "8.6 kg", "option_b": "8.4 kg", "option_c": "8.7 kg", "option_d": "8.1 kg",
        "correct_answer": "a",
        "explanation": "New C = 38.7×(1.19/1.53) = 38.7×0.7778 ≈ 30.1 kg. Reduction = 38.7-30.1 = 8.6 kg.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "In a triangle, height is increased by 37.5% and base is increased by 45.45%. Find the % increase in the area of the triangle.",
        "option_a": "200%", "option_b": "100%", "option_c": "125%", "option_d": "150%",
        "correct_answer": "b",
        "explanation": "37.5% = 3/8 → new H = 11H/8. 45.45% = 5/11 → new B = 16B/11. New area = (11H/8)(16B/11) = 2BH. % increase = 100%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "The base of a triangle is increased by 40%. By what % (correct to two decimal places) should its height be increased so that the area increases by 60%?",
        "option_a": "14.29%", "option_b": "20.01%", "option_c": "15.54%", "option_d": "18.62%",
        "correct_answer": "a",
        "explanation": "1.4 × new_H = 1.6H → new_H = (8/7)H. % increase = 1/7 × 100 ≈ 14.29%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "If the diagonal of a square is decreased by 45%, find the % decrease in its area.",
        "option_a": "75.50%", "option_b": "69.75%", "option_c": "70.25%", "option_d": "62.5%",
        "correct_answer": "b",
        "explanation": "Area ∝ d². New area = (0.55d)² = 0.3025d². % decrease = (1-0.3025)×100 = 69.75%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "If the area of a square is decreased by 19%, then the diagonal of the square is decreased by:",
        "option_a": "10%", "option_b": "15%", "option_c": "5%", "option_d": "12%",
        "correct_answer": "a",
        "explanation": "Area ∝ d². If area = 0.81d², then diagonal = √0.81 × d = 0.9d. % decrease = 10%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "The radius of a cylinder is increased by 120% and its height is decreased by 40%. What is the % increase in its volume?",
        "option_a": "180.6%", "option_b": "212.8%", "option_c": "175.4%", "option_d": "190.4%",
        "correct_answer": "d",
        "explanation": "New V = π(2.2r)²(0.6h) = 4.84×0.6×πr²h = 2.904V. % increase = 190.4%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "The radius and height of a right circular cone are increased by 25%. Find the % increase in volume of the cone (rounded off to two decimal places). (CHSL Mains 2023)",
        "option_a": "94.31%", "option_b": "95.31%", "option_c": "94.51%", "option_d": "93.51%",
        "correct_answer": "b",
        "explanation": "V = (1/3)πr²h. New V = (1.25)³ × V = 1.953125V. % increase = 95.3125% ≈ 95.31%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "If the radius of a sphere is increased by 16⅔%, then by what % would its surface area increase? (correct to one decimal place)",
        "option_a": "34.8%", "option_b": "36.1%", "option_c": "33.9%", "option_d": "37.4%",
        "correct_answer": "b",
        "explanation": "16⅔% = 1/6. New r = 7r/6. SA ∝ r². New SA = (7/6)² = 49/36. % increase = 13/36×100 ≈ 36.1%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "The radius of a spherical balloon is inflated from 3.5 cm to 4.9 cm by pushing air. What is the % increase in volume of the original balloon?",
        "option_a": "74.4%", "option_b": "73.6%", "option_c": "173.6%", "option_d": "174.4%",
        "correct_answer": "d",
        "explanation": "V ∝ r³. (4.9/3.5)³ = (1.4)³ = 2.744. % increase = (2.744-1)×100 = 174.4%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "The diameter of a sphere is increased by 140%. By what percent will its volume increase?",
        "option_a": "1282.4%", "option_b": "1382.4%", "option_c": "274.4%", "option_d": "174.4%",
        "correct_answer": "a",
        "explanation": "New diameter = 2.4D → new radius = 2.4r/... actually original r, new r = 1.2×original_diameter? No: new r = 2.4D/2 = 1.2×(2r)... Let me redo. r_new = 2.4r (since diameter increases by 140%, new d = 2.4d, new r = 1.2d = 2.4r_original). V ∝ r³. (2.4)³ = 13.824. % = 1282.4%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "medium", "phase": "main",
        "question_text": "Volume of a sphere is increased by 119.7% when its radius is increased. Find % change in TSA of sphere.",
        "option_a": "61.29%", "option_b": "69%", "option_c": "96%", "option_d": "82.25%",
        "correct_answer": "b",
        "explanation": "New V = 2.197V = (1.3)³ × V → new r = 1.3r. TSA ∝ r². % change = (1.3²-1)×100 = 0.69×100 = 69%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "hard", "phase": "main",
        "question_text": "If the radius of a cylinder is increased by 25%, by how much % should height be decreased so that volume of cylinder increases by 32% only?",
        "option_a": "14.73%", "option_b": "16.65%", "option_c": "15.52%", "option_d": "15.76%",
        "correct_answer": "c",
        "explanation": "(1.25r)² × new_h = 1.32r²h → 1.5625×new_h = 1.32h → new_h = 0.8448h. % decrease = 15.52%.",
    },
    {
        "subject": "Quantitative Aptitude", "subject_code": "quant", "topic": "Percentage",
        "difficulty": "hard", "phase": "main",
        "question_text": "Volume of a cylinder is increased by 43% when its height is reduced by 15⅝%. Find % change in CSA of cylinder.",
        "option_a": "15%", "option_b": "13%", "option_c": "10%", "option_d": "12%",
        "correct_answer": "c",
        "explanation": "new_h=27h/32. (new_r)²×27/32=1.43r² → new_r=1.302r. CSA change=(1.302×27/32-1)×100=(1.0985-1)×100≈10%.",
    },
]


def seed():
    db = SessionLocal()
    try:
        added = 0
        for q in QUESTIONS:
            exists = db.query(Question).filter(
                Question.question_text == q["question_text"]
            ).first()
            if not exists:
                db.add(Question(**q))
                added += 1
        db.commit()
        print(f"Seeded {added} new Percentage questions Q76-Q122 (skipped {len(QUESTIONS) - added} duplicates).")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
